### ISSUE TITLE
Hypertable error when trying to compress - version 1.5 TimescaleDB

### ISSUE THREAD

**Issue by gmisagm** [timescale/timescaledb#1522]
Windows 10 x64,
PostgreSQL version 11.5
TimescaleDB version 1.5.0

Install using timescaledb-postgresql-11_1.5.0-windows-amd64.zip

**Describe the bug**
After upgrading TimeScaleDB from version 1.4.2 to 1.5.0 I wanted to try compressing a large hypertable. 

The statement:

ALTER TABLE public.largetimetable SET (timescaledb.compress, timescaledb.compress_orderby = 'mytimecolumn');

failed with the error:
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [0A000]: ERROR: cannot compress internal compression hypertable
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:134)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:480)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:419)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:152)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:411)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:781)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2852)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:99)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:152)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:97)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$17.run(ResultSetViewer.java:3431)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.postgresql.util.PSQLException: ERROR: cannot compress internal compression hypertable
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:307)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:293)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:270)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:266)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:338)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
	... 12 more

**To Reproduce**
1. Stop postgresql11 service
2. Install TimescaleDB 1.5.0
3. Start postgresql 11.5
4. Run the ALTER table statement above.

**Expected behavior**
No error, table to have compression set

**Actual behavior**
Error message above

**Comment by cevian** [comment]
Please try running `VACUUM FULL _timescaledb_catalog.hypertable;` Let us know if that fixes the problem

**Comment by gmisagm** [comment]
Yes that fixed it thanks.

Gordon

**Comment by cevian** [comment]
Fixed by #1523. Leaving open for reference before 1.5.1 release.

**Comment by bboule** [comment]
Will be fixing the need to issue the vacuum command in the 1.5.1 release...
