### ISSUE TITLE
Issue with replication slot after upgrading from 1.3.2 to 1.5.1

### ISSUE THREAD

**Issue by maltalex** [timescale/timescaledb#1562]
We've upgraded a containerized timescaledb instance from 1.3.2 to 1.5.1 and ran into a problem with a logical replication slot that existed before the update.

A Java process that read the WAL via the replication slot started failing with `OID lookup failed for table index "chunk_compressed_chunk_id_idx`. Here's the full stacktrace from pgjdbc (version 42.2.8):

```
org.postgresql.util.PSQLException:
ERROR: OID lookup failed for table index "chunk_compressed_chunk_id_idx"
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2497)
        at org.postgresql.core.v3.QueryExecutorImpl.processCopyResults(QueryExecutorImpl.java:1155)
        at org.postgresql.core.v3.QueryExecutorImpl.readFromCopy(QueryExecutorImpl.java:1062)
        at org.postgresql.core.v3.CopyDualImpl.readFromCopy(CopyDualImpl.java:37)
        at org.postgresql.core.v3.replication.V3PGReplicationStream.receiveNextData(V3PGReplicationStream.java:158)
        at org.postgresql.core.v3.replication.V3PGReplicationStream.readInternal(V3PGReplicationStream.java:123)
        at org.postgresql.core.v3.replication.V3PGReplicationStream.readPending(V3PGReplicationStream.java:80)
```

Strangely enough, when we manually ran `SELECT * FROM pg_indexes WHERE indexname = 'chunk_compressed_chunk_id_idx` against the database, the "missing" index was there.

We verified that the plugin has indeed been updated:

```
postgres=# \dx
                                      List of installed extensions
    Name     | Version |   Schema   |                            Description
-------------+---------+------------+-------------------------------------------------------------------
 timescaledb | 1.5.1   | public     | Enables scalable inserts and complex queries for time-series data
```

And also tried restarting the database several times.

The replication slot uses the wal2json plugin (https://github.com/eulerto/wal2json), and we're using postgres 11, with the oss version of timescale. For the update, we've (re)compiled the wal2json  plugin (v1.0) into the timescale container.

Eventually, the issue was solved by dropping and re-creating the replication slot. However, this might be something worth looking into.

**Comment by msabatier** [comment]
I would like to report that we faced a similar issue when upgrading from timescale 1.3.2 to 1.6.1 on an Ubuntu 18.04 / postgresql-10 production setup.
This came as a surprise as we are using logical replication and the publication is restricted to regular postgres tables, not hypertables, even if there are hypertables present in the same schema.

In details what we did:
1- Suspend the replication with ALTER SUBSCRIPTION xxxxxx DISABLE on the slave
2- Upgrade the master (apt upgrade, reboot for kernel patches...)
3- Upgrade the timescaledb extension with ALTER EXTENSION timescaledb UPDATE TO "1.6.1"
4- Master was put back in production and slave put in maintenance
5- Upgrade the slave (apt upgrade, reboot for kernel patches...)
6- Upgrade the timescaledb extension with ALTER EXTENSION timescaledb UPDATE TO "1.6.1"
7- Reenable replication ALTER SUBSCRIPTION xxxxxx ENABLE
8- at that point we observed the following error messages
> Apr 22 12:52:08 db2 postgres[3263]: [1] LOG:  logical replication apply worker for subscription "xxxxxx" has started
> Apr 22 12:52:08 db2 postgres[3263]: [1] ERROR:  could not receive data from WAL stream: ERROR:  OID lookup failed for table index "chunk_compressed_chunk_id_idx"
> 

At that point we applied the workaround mentioned by the op, dropping and recreating the replication_slot which came with its own challenges... but worked in the end.

Let me know if I can provide any further info to help prevent this in future upgrades.

And many thanks for this great software!

**Comment by maltalex** [comment]
@NunoFilipeSantos Unfortunately, no. That system is no longer around.
