### ISSUE TITLE
Segfault in the hypertable cache on insert path.

### ISSUE THREAD

**Issue by olofr** [timescale/timescaledb#184]
Using parallel inserts the hypertable_cache segfaults. The bug is present in `0.4.0` but not present in `0.3.0`.

```
#0  cache_fetch (cache=0x0, query=query@entry=0x7fffccd19430) at src/cache.c:106
#1  0x00007fe01a5c63bc in hypertable_cache_get_entry_with_table (cache=<optimized out>, relid=<optimized out>, schema=schema@entry=0x0,
    table=table@entry=0x0) at src/hypertable_cache.c:159
#2  0x00007fe01a5c63e2 in hypertable_cache_get_entry (cache=<optimized out>, relid=<optimized out>) at src/hypertable_cache.c:148
```

Reported by @yadid. Thank you.

**Comment by olofr** [comment]
Reported by @yadid. Thank you.
