### ISSUE TITLE
Segfault on COPY to hypertable on 1.7.0

### ISSUE THREAD

**Issue by fvannee** [timescale/timescaledb#1840]
- OS: CentOS
 - PostgreSQL version (output of `postgres --version`): 11.2 as well as 12.2
 - TimescaleDB version (output of `\dx` in `psql`): 1.7.0
 - Installation method: Source

**Describe the bug**
Postgres segfaults when COPYing to a hypertable with a `NOT NULL` constraint that you're violating in the `COPY`.

**To Reproduce**
Setup:
```
create table test (a int not null, b timestamptz);
select create_hypertable('public.test', 'b');
```

Then copy:
```
=# copy test (a,b) from stdin (delimiter ',', null 'N');
Enter data to be copied followed by a newline.
End with a backslash and a period on a line by itself, or an EOF signal.
>> N,'2020-01-01'
>> server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
Time: 13372.671 ms (00:13.373)
```

Stack trace:
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000630b1a in exec_rt_fetch (estate=0x2505aa0, rti=3907656) at ../../../src/include/executor/executor.h:539
539		return estate->es_range_table_array[rti - 1];
Missing separate debuginfos, use: debuginfo-install postgresql-12.2-rosmerta0002.el7.x86_64
(gdb) bt
#0  0x0000000000630b1a in exec_rt_fetch (estate=0x2505aa0, rti=3907656) at ../../../src/include/executor/executor.h:539
#1  ExecConstraints (resultRelInfo=resultRelInfo@entry=0x2565cf0, slot=slot@entry=0x250bff8, estate=estate@entry=0x2505aa0) at execMain.c:1951
#2  0x00007f517de36e5e in copyfrom (ccstate=ccstate@entry=0x250c4b8, ht=0x25cb630, range_table=0x0) at /home/florisvannee/timescaledb/src/copy.c:390
#3  0x00007f517de37220 in timescaledb_DoCopy (stmt=stmt@entry=0x23f17f8, queryString=0x23f0b10 "copy test (a,b) from stdin (delimiter ',', null 'N');", processed=processed@entry=0x7ffdc0f8c9a0, ht=ht@entry=0x25cb630)
    at /home/florisvannee/timescaledb/src/copy.c:702
#4  0x00007f517de4c29a in process_copy (args=0x7ffdc0f8c9e0) at /home/florisvannee/timescaledb/src/process_utility.c:405
#5  process_ddl_command_start (args=0x7ffdc0f8c9e0) at /home/florisvannee/timescaledb/src/process_utility.c:3140
#6  timescaledb_ddl_command_start (pstmt=<optimized out>, query_string=<optimized out>, context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=<optimized out>, dest=<optimized out>, completion_tag=0x7ffdc0f8cf50 "")
    at /home/florisvannee/timescaledb/src/process_utility.c:3403
```

Cause seems to be that the `ExecConstraints` call is passed a `resultRelInfo` that's not been properly initialized with all necessary values.

**Comment by gayyappan** [comment]
am able to repro this on 1.7.  See expected behavior on 1.6.1
```
test2=# copy test (a,b) from stdin (delimiter ',', null 'N');
Enter data to be copied followed by a newline.
End with a backslash and a period on a line by itself, or an EOF signal.
>> N,'2020-01-01'
>> 
>> 1, '2020-01-02'
>> ERROR:  null value in column "a" violates not-null constraint
DETAIL:  Failing row contains (null, 2020-01-01 00:00:00-05).
CONTEXT:  COPY test, line 1: "N,'2020-01-01'"
```
