### ISSUE TITLE
Segfault in create_trigger_handler

### ISSUE THREAD

**Issue by svenklemm** [timescale/timescaledb#2013]
````
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fa95e1febbc in create_trigger_handler (trigger=0x7f7f7f7f7f7f7fd7, 
    arg=0x5620158652b0)
    at /home/runner/work/timescaledb/timescaledb/src/trigger.c:106
106		if (TRIGGER_USES_TRANSITION_TABLE(trigger->tgnewtable) ||
(gdb) #0  0x00007fa95e1febbc in create_trigger_handler (trigger=0x7f7f7f7f7f7f7fd7, 
    arg=0x5620158652b0)
    at /home/runner/work/timescaledb/timescaledb/src/trigger.c:106
#1  0x00007fa95e1feb26 in for_each_trigger (relid=89308, 
    on_trigger=0x7fa95e1feb8d <create_trigger_handler>, arg=0x5620158652b0)
    at /home/runner/work/timescaledb/timescaledb/src/trigger.c:93
#2  0x00007fa95e1feeba in ts_trigger_create_all_on_chunk (
    chunk=0x5620158652b0)
    at /home/runner/work/timescaledb/timescaledb/src/trigger.c:151
#3  0x00007fa95e18c768 in chunk_create_table_after_lock (
    chunk=0x5620158652b0, ht=0x5620158de5a0)
    at /home/runner/work/timescaledb/timescaledb/src/chunk.c:933
#4  0x00007fa95e18c90f in chunk_create_from_hypercube_after_lock (
    ht=0x5620158de5a0, cube=0x5620158660d0, 
    schema_name=0x5620158de624 "_timescaledb_internal", table_name=0x0, 
    prefix=0x5620158de664 "_hyper_1")
    at /home/runner/work/timescaledb/timescaledb/src/chunk.c:962
#5  0x00007fa95e18c9fa in chunk_create_from_point_after_lock (
    ht=0x5620158de5a0, p=0x562015864f18, 
    schema_name=0x5620158de624 "_timescaledb_internal", table_name=0x0, 
    prefix=0x5620158de664 "_hyper_1")
    at /home/runner/work/timescaledb/timescaledb/src/chunk.c:986
#6  0x00007fa95e18cff4 in ts_chunk_create_from_point (ht=0x5620158de5a0, 
    p=0x562015864f18, schema=0x5620158de624 "_timescaledb_internal", 
    prefix=0x5620158de664 "_hyper_1")
    at /home/runner/work/timescaledb/timescaledb/src/chunk.c:1056
#7  0x00007fa95e1c8d0b in hypertable_get_chunk (h=0x5620158de5a0, 
    point=0x562015864f18, create_if_not_exists=true)
    at /home/runner/work/timescaledb/timescaledb/src/hypertable.c:1147
#8  0x00007fa95e1c8e16 in ts_hypertable_get_or_create_chunk (
    h=0x5620158de5a0, point=0x562015864f18)
    at /home/runner/work/timescaledb/timescaledb/src/hypertable.c:1172
#9  0x00007fa95e1a207c in ts_chunk_dispatch_get_chunk_insert_state (
    dispatch=0x5620158a9b38, point=0x562015864f18, 
    on_chunk_changed=0x7fa95e1a2982 <on_chunk_insert_state_changed>, 
    data=0x5620158a9b90)
    at /home/runner/work/timescaledb/timescaledb/src/chunk_dispatch.c:128
#10 0x00007fa95e1a2dc7 in chunk_dispatch_exec (node=0x5620158a9b90)
    at /home/runner/work/timescaledb/timescaledb/src/chunk_dispatch_state.c:137
#11 0x0000562014057c7b in ExecProcNode (node=0x5620158a9b90)
    at ../../../src/include/executor/executor.h:247
#12 ExecModifyTable (pstate=0x5620158a98e0) at nodeModifyTable.c:2025
#13 0x00007fa95e1d1446 in ExecProcNode (node=0x5620158a98e0)
    at /home/runner/postgresql/include/server/executor/executor.h:247
#14 0x00007fa95e1d18a8 in hypertable_insert_exec (node=0x5620158a94a8)
    at /home/runner/work/timescaledb/timescaledb/src/hypertable_insert.c:110
#15 0x000056201402f73a in ExecProcNode (node=0x5620158a94a8)
    at ../../../src/include/executor/executor.h:247
#16 ExecutePlan (execute_once=<optimized out>, dest=0x5620158e9b20, 
    direction=<optimized out>, numberTuples=0, sendTuples=<optimized out>, 
    operation=CMD_INSERT, use_parallel_mode=<optimized out>, 
    planstate=0x5620158a94a8, estate=0x5620158a7e68) at execMain.c:1723
#17 standard_ExecutorRun (queryDesc=0x5620157d2638, 
    direction=<optimized out>, count=0, execute_once=<optimized out>)
    at execMain.c:364
#18 0x0000562014197e32 in ProcessQuery (plan=<optimized out>, 
    sourceText=0x5620157a04d8 "INSERT INTO hyper(time, device_id,sensor_1) VALUES\n(12579876", '0' <repeats 11 times>, ", 'dev1', 1);", params=0x0, 
    queryEnv=0x0, dest=0x5620158e9b20, completionTag=0x7ffcd8deca10 "")
    at pquery.c:161
#19 0x00005620141980ab in PortalRunMulti (portal=portal@entry=0x562015812df8, 
    isTopLevel=isTopLevel@entry=true, 
    setHoldSnapshot=setHoldSnapshot@entry=false, 
    dest=dest@entry=0x5620158e9b20, altdest=altdest@entry=0x5620158e9b20, 
    completionTag=completionTag@entry=0x7ffcd8deca10 "") at pquery.c:1286
#20 0x0000562014198daa in PortalRun (portal=portal@entry=0x562015812df8, 
    count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true, 
    run_once=run_once@entry=true, dest=dest@entry=0x5620158e9b20, 
    altdest=altdest@entry=0x5620158e9b20, completionTag=0x7ffcd8deca10 "")
    at pquery.c:799
#21 0x0000562014194762 in exec_simple_query (
    query_string=0x5620157a04d8 "INSERT INTO hyper(time, device_id,sensor_1) VALUES\n(12579876", '0' <repeats 11 times>, ", 'dev1', 1);") at postgres.c:1145
#22 0x00005620141966fc in PostgresMain (argc=<optimized out>, 
    argv=argv@entry=0x5620157d7a50, dbname=<optimized out>, 
    username=<optimized out>) at postgres.c:4193
#23 0x0000562013e65bda in BackendRun (port=0x5620157cfc50)
    at postmaster.c:4364
#24 BackendStartup (port=0x5620157cfc50) at postmaster.c:4036
#25 ServerLoop () at postmaster.c:1707
#26 0x0000562014113dd5 in PostmasterMain (argc=8, argv=0x562015799d80)
    at postmaster.c:1380
#27 0x0000562013e67855 in main (argc=8, argv=0x562015799d80) at main.c:228
(gdb) quit
           PID: 10164 (postgres)
           UID: 1001 (runner)
           GID: 116 (docker)
        Signal: 11 (SEGV)
     Timestamp: Thu 2020-06-18 21:00:00 UTC (6min ago)
  Command Line: postgres: default_perm_user db_triggers 127.0.0.1(44152) INSERT
    Executable: /home/runner/postgresql/bin/postgres
 Control Group: /system.slice/runner-provisioner.service
          Unit: runner-provisioner.service
         Slice: system.slice
       Boot ID: a64b6233ad614fe78a47287c4cc3beb7
    Machine ID: d9b6a7f69a6e46d6ae2045d9811234fc
      Hostname: fv-az92
```

**Comment by svenklemm** [comment]
```
#0  0x00007ff7816588d6 in create_trigger_handler (trigger=0x7f7f7f7f7f7f8347,
    arg=0x562aaa79fb40)
    at /home/runner/work/timescaledb/timescaledb/src/trigger.c:106
106   if (TRIGGER_USES_TRANSITION_TABLE(trigger->tgnewtable) ||
(gdb) #0  0x00007ff7816588d6 in create_trigger_handler (trigger=0x7f7f7f7f7f7f8347,
    arg=0x562aaa79fb40)
    at /home/runner/work/timescaledb/timescaledb/src/trigger.c:106
        chunk = 0x562aaa79fb40
        __func__ = "create_trigger_handler"
#1  0x00007ff781658840 in for_each_trigger (relid=88824,
    on_trigger=0x7ff7816588a7 <create_trigger_handler>, arg=0x562aaa79fb40)
    at /home/runner/work/timescaledb/timescaledb/src/trigger.c:93
        trigger = 0x7f7f7f7f7f7f8347
        trigdesc = 0x7ff780935290
        i = 11
        rel = 0x7ff78091de18
#2  0x00007ff781658bd4 in ts_trigger_create_all_on_chunk (
    chunk=0x562aaa79fb40)
    at /home/runner/work/timescaledb/timescaledb/src/trigger.c:151
        sec_ctx = 0
        saved_uid = 16386
        owner = 16386
#3  0x00007ff7815e5888 in chunk_create_table_after_lock (
    chunk=0x562aaa79fb40, ht=0x562aaa8191a0)
    at /home/runner/work/timescaledb/timescaledb/src/chunk.c:933
        tablespace = 0x0
        __func__ = "chunk_create_table_after_lock"
#4  0x00007ff7815e5a2f in chunk_create_from_hypercube_after_lock (
    ht=0x562aaa8191a0, cube=0x562aaa7a0960,
    schema_name=0x562aaa819224 "_timescaledb_internal", table_name=0x0,
    prefix=0x562aaa819264 "_hyper_1")
    at /home/runner/work/timescaledb/timescaledb/src/chunk.c:962
        chunk = 0x562aaa79fb40
#5  0x00007ff7815e5b1a in chunk_create_from_point_after_lock (
    ht=0x562aaa8191a0, p=0x562aaa79f7a8,
    schema_name=0x562aaa819224 "_timescaledb_internal", table_name=0x0,
    prefix=0x562aaa819264 "_hyper_1")
    at /home/runner/work/timescaledb/timescaledb/src/chunk.c:986
        hs = 0x562aaa8193b8
        cube = 0x562aaa7a0960
#6  0x00007ff7815e6114 in ts_chunk_create_from_point (ht=0x562aaa8191a0,
    p=0x562aaa79f7a8, schema=0x562aaa819224 "_timescaledb_internal",
    prefix=0x562aaa819264 "_hyper_1")
    at /home/runner/work/timescaledb/timescaledb/src/chunk.c:1056
        chunk = 0x0
        __func__ = "ts_chunk_create_from_point"
#7  0x00007ff78162207a in hypertable_get_chunk (h=0x562aaa8191a0,
    point=0x562aaa79f7a8, create_if_not_exists=true)
    at /home/runner/work/timescaledb/timescaledb/src/hypertable.c:1147
        chunk = 0x0
        cse = 0x0
#8  0x00007ff781622185 in ts_hypertable_get_or_create_chunk (
    h=0x562aaa8191a0, point=0x562aaa79f7a8)
    at /home/runner/work/timescaledb/timescaledb/src/hypertable.c:1172
No locals.
#9  0x00007ff7815fb1d8 in ts_chunk_dispatch_get_chunk_insert_state (
    dispatch=0x562aaa7e4b48, point=0x562aaa79f7a8,
    on_chunk_changed=0x7ff7815fbade <on_chunk_insert_state_changed>,
    data=0x562aaa7e4ba0)
    at /home/runner/work/timescaledb/timescaledb/src/chunk_dispatch.c:128
        new_chunk = 0x562aaa7e2e78
        cis = 0x0
        cis_changed = true
        __func__ = "ts_chunk_dispatch_get_chunk_insert_state"
#10 0x00007ff7815fbf23 in chunk_dispatch_exec (node=0x562aaa7e4ba0)
    at /home/runner/work/timescaledb/timescaledb/src/chunk_dispatch_state.c:137
        state = 0x562aaa7e4ba0
        substate = 0x562aaa7f50c0
        slot = 0x562aaa7f5f90
        point = 0x562aaa79f7a8
        cis = 0x562aa9b7f109 <ExecProcNodeFirst+9>
        dispatch = 0x562aaa7e4b48
        ht = 0x562aaa8191a0
        estate = 0x562aaa7e2e78
        old = 0x562aaa7e2d60
#11 0x0000562aa9b9fc7b in ExecProcNode (node=0x562aaa7e4ba0)
    at ../../../src/include/executor/executor.h:247
No locals.
#12 ExecModifyTable (pstate=0x562aaa7e48f0) at nodeModifyTable.c:2025
        node = <optimized out>
        proute = 0x0
        estate = 0x562aaa7e2e78
        operation = CMD_INSERT
        saved_resultRelInfo = 0x0
        resultRelInfo = 0x562aaa7e3120
        subplanstate = 0x562aaa7e4ba0
        junkfilter = 0x0
        slot = <optimized out>
        planSlot = <optimized out>
        tupleid = <optimized out>
        tuple_ctid = {ip_blkid = {bi_hi = 43646, bi_lo = 22058}, ip_posid = 0}
        oldtupdata = {t_len = 2860402928, t_self = {ip_blkid = {
              bi_hi = 22058, bi_lo = 0}, ip_posid = 26680},
          t_tableOid = 22058, t_data = 0x562aaa6dcaa0}
        oldtuple = <optimized out>
        __func__ = "ExecModifyTable"
#13 0x00007ff78162a7fa in ExecProcNode (node=0x562aaa7e48f0)
    at /home/runner/postgresql/include/server/executor/executor.h:247
No locals.
#14 0x00007ff78162ac5c in hypertable_insert_exec (node=0x562aaa7e44b8)
    at /home/runner/work/timescaledb/timescaledb/src/hypertable_insert.c:110
No locals.
#15 0x0000562aa9b7773a in ExecProcNode (node=0x562aaa7e44b8)
    at ../../../src/include/executor/executor.h:247
No locals.
#16 ExecutePlan (execute_once=<optimized out>, dest=0x562aaa823b30,
    direction=<optimized out>, numberTuples=0, sendTuples=<optimized out>,
    operation=CMD_INSERT, use_parallel_mode=<optimized out>,
    planstate=0x562aaa7e44b8, estate=0x562aaa7e2e78) at execMain.c:1723
        slot = <optimized out>
        current_tuple_count = 0
        slot = <optimized out>
        current_tuple_count = <optimized out>
#17 standard_ExecutorRun (queryDesc=0x562aaa7d75b8,
    direction=<optimized out>, count=0, execute_once=<optimized out>)
    at execMain.c:364
        estate = 0x562aaa7e2e78
        operation = CMD_INSERT
        dest = 0x562aaa823b30
        sendTuples = <optimized out>
        oldcontext = <optimized out>
        __func__ = "standard_ExecutorRun"
#18 0x0000562aa9cdfe32 in ProcessQuery (plan=<optimized out>,
    sourceText=0x562aaa6db4d8 "INSERT INTO hyper(time, device_id,sensor_1) VALUES\n(12579876", '0' <repeats 11 times>, ", 'dev1', 1);", params=0x0,
    queryEnv=0x0, dest=0x562aaa823b30, completionTag=0x7ffd6a4e7740 "")
    at pquery.c:161
        queryDesc = 0x562aaa7d75b8
#19 0x0000562aa9ce00ab in PortalRunMulti (portal=portal@entry=0x562aaa74b1f8,
    isTopLevel=isTopLevel@entry=true,
    setHoldSnapshot=setHoldSnapshot@entry=false,
    dest=dest@entry=0x562aaa823b30, altdest=altdest@entry=0x562aaa823b30,
    completionTag=completionTag@entry=0x7ffd6a4e7740 "") at pquery.c:1286
        pstmt = <optimized out>
        active_snapshot_set = true
        stmtlist_item = 0x562aaa7e1ff8
#20 0x0000562aa9ce0daa in PortalRun (portal=portal@entry=0x562aaa74b1f8,
    count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true,
    run_once=run_once@entry=true, dest=dest@entry=0x562aaa823b30,
    altdest=altdest@entry=0x562aaa823b30, completionTag=0x7ffd6a4e7740 "")
    at pquery.c:799
        save_exception_stack = 0x7ffd6a4e7930
        save_context_stack = 0x0
        local_sigjmp_buf = {{__jmpbuf = {1, -2209730387282435251,
              94741247935880, 140726386980672, 94741248389624, 2,
              -5549853531148328115, -2209734015583722675},
            __mask_was_saved = 0, __saved_mask = {__val = {94741240702133,
                94741248401208, 94741248397984, 0, 94738388615168, 64,
                94741248397832, 94741240702133, 94741248389624,
                94741240702133, 1, 112, 94741247931328, 94741247935880,
                94741240576005, 94741249005024}}}}
        result = <optimized out>
        nprocessed = <optimized out>
        saveTopTransactionResourceOwner = 0x562aaa7161e8
        saveTopTransactionContext = 0x562aaa767a50
        saveActivePortal = 0x0
        saveResourceOwner = 0x562aaa7161e8
        savePortalContext = 0x0
        saveMemoryContext = 0x562aaa767a50
        __func__ = "PortalRun"
#21 0x0000562aa9cdc762 in exec_simple_query (
    query_string=0x562aaa6db4d8 "INSERT INTO hyper(time, device_id,sensor_1) VALUES\n(12579876", '0' <repeats 11 times>, ", 'dev1', 1);") at postgres.c:1145
        parsetree = <optimized out>
        portal = 0x562aaa74b1f8
        snapshot_set = <optimized out>
        commandTag = <optimized out>
        completionTag = "\000wNj\375\177\000\000Ș]j\375\177\000\000\020\364o\252*V\000\000Ș]j\375\177\000\000y\314\365^\000\000\000\000ﺵm\252*V\000\000ﺵm\252*V\000\000\230\tq\252*V\000"
        querytree_list = <optimized out>
        plantree_list = <optimized out>
        receiver = 0x562aaa823b30
        format = 0
        dest = DestRemote
        oldcontext = <optimized out>
        parsetree_list = 0x562aaa6dc5b0
        parsetree_item = 0x562aaa6dc588
        save_log_statement_stats = false
        was_logged = false
        use_implicit_block = false
        msec_str = "\000wNj\375\177\000\000Ș]j\375\177\000\000\020\364o\252*V\000\000Ș]j\375\177\000"
        __func__ = "exec_simple_query"
#22 0x0000562aa9cde6fc in PostgresMain (argc=<optimized out>,
    argv=argv@entry=0x562aaa710c80, dbname=<optimized out>,
    username=<optimized out>) at postgres.c:4193
        query_string = 0x562aaa6db4d8 "INSERT INTO hyper(time, device_id,sensor_1) VALUES\n(12579876", '0' <repeats 11 times>, ", 'dev1', 1);"
        firstchar = <optimized out>
        input_message = {
          data = 0x562aaa6db4d8 "INSERT INTO hyper(time, device_id,sensor_1) VALUES\n(12579876", '0' <repeats 11 times>, ", 'dev1', 1);", len = 85,
          maxlen = 1024, cursor = 85}
        local_sigjmp_buf = {{__jmpbuf = {140726386981104,
              5548493224828658509, 94741248149912, 94741248150656,
              94741243899456, 94741248078864, -5549853531072830643,
              -2209734039126088883}, __mask_was_saved = 1, __saved_mask = {
              __val = {0, 94741247937184, 94741238804048, 94741247931848,
                94741248150192, 94741248150584, 4700153639258432000,
                94741248079136, 94741240361991, 140726386982000, 0,
                140726386983040, 94741248149912, 94741248078864,
                140701163970709, 206158430256}}}}
        send_ready_for_query = false
        disable_idle_in_transaction_timeout = false
        __func__ = "PostgresMain"
#23 0x0000562aa99adbda in BackendRun (port=0x562aaa6ff520)
    at postmaster.c:4364
        ac = 1
        secs = 646482169
        usecs = 730577
        i = 1
        av = 0x562aaa710c80
        maxac = <optimized out>
        av = <optimized out>
        maxac = <optimized out>
        ac = <optimized out>
        secs = <optimized out>
        usecs = <optimized out>
        i = <optimized out>
#24 BackendStartup (port=0x562aaa6ff520) at postmaster.c:4036
        bn = 0x562aaa6ff410
        pid = <optimized out>
        bn = <optimized out>
        pid = <optimized out>
        save_errno = <optimized out>
#25 ServerLoop () at postmaster.c:1707
        port = <optimized out>
        i = <optimized out>
        rmask = {fds_bits = {16, 0 <repeats 15 times>}}
        selres = <optimized out>
        now = <optimized out>
        readmask = {fds_bits = {16, 0 <repeats 15 times>}}
        nSockets = <optimized out>
        last_lockfile_recheck_time = 1593166967
        last_touch_time = 1593166907
        __func__ = "ServerLoop"
#26 0x0000562aa9c5bdd5 in PostmasterMain (argc=8, argv=0x562aaa6d4d80)
    at postmaster.c:1380
        opt = <optimized out>
        status = <optimized out>
        userDoption = <optimized out>
        listen_addr_saved = <optimized out>
        i = <optimized out>
        output_config_variable = <optimized out>
        __func__ = "PostmasterMain"
#27 0x0000562aa99af855 in main (argc=8, argv=0x562aaa6d4d80) at main.c:228
No locals.
(gdb) quit
           PID: 10606 (postgres)
           UID: 1001 (runner)
           GID: 116 (docker)
        Signal: 11 (SEGV)
     Timestamp: Fri 2020-06-26 10:22:49 UTC (2min 33s ago)
  Command Line: postgres: default_perm_user db_triggers 127.0.0.1(53784) INSERT
    Executable: /home/runner/postgresql/bin/postgres
 Control Group: /system.slice/runner-provisioner.service
          Unit: runner-provisioner.service
         Slice: system.slice
       Boot ID: e3dc300457554fc6a0c463c245589ab5
    Machine ID: 148a6750218645a5a5c641e7072ea97f
      Hostname: fv-az148
       Storage: /var/lib/systemd/coredump/core.postgres.1001.e3dc300457554fc6a0c463c245589ab5.10606.1593166969000000.lz4
       Message: Process 10606 (postgres) of user 1001 dumped core.

                Stack trace of thread 10606:
                #0  0x00007ff7816588d6 n/a (/home/runner/postgresql/lib/timescaledb-2.0.0-dev.so)
                #1  0x00007ff781658840 n/a (/home/runner/postgresql/lib/timescaledb-2.0.0-dev.so)
                #2  0x00007ff781658bd4 n/a (/home/runner/postgresql/lib/timescaledb-2.0.0-dev.so)
                #3  0x00007ff7815e5888 n/a (/home/runner/postgresql/lib/timescaledb-2.0.0-dev.so)
                #4  0x00007ff7815e5a2f n/a (/home/runner/postgresql/lib/timescaledb-2.0.0-dev.so)
                #5  0x00007ff7815e5b1a n/a (/home/runner/postgresql/lib/timescaledb-2.0.0-dev.so)
                #6  0x00007ff7815e6114 n/a (/home/runner/postgresql/lib/timescaledb-2.0.0-dev.so)
                #7  0x00007ff78162207a n/a (/home/runner/postgresql/lib/timescaledb-2.0.0-dev.so)
                #8  0x00007ff781622185 n/a (/home/runner/postgresql/lib/timescaledb-2.0.0-dev.so)
                #9  0x00007ff7815fb1d8 n/a (/home/runner/postgresql/lib/timescaledb-2.0.0-dev.so)
                #10 0x00007ff7815fbf23 n/a (/home/runner/postgresql/lib/timescaledb-2.0.0-dev.so)
                #11 0x0000562aa9b9fc7b n/a (/home/runner/postgresql/bin/postgres)
```
