### ISSUE TITLE
Assertion failure in ts_subspace_store_init

### ISSUE THREAD

**Issue by svenklemm** [timescale/timescaledb#2293]
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
(gdb) #0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
        set = {__val = {0, 140518645804808, 140721559927968, 140518643122581, 
            140721559928016, 140721559928208, 0, 0, 140518645804808, 
            7464772681257476352, 140721559927968, 140518642850415, 
            94629023039600, 7464772681257476352, 94629021885548, 
            94628991947216}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007fcd158088b1 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x7fcd0bd3cf38, 
            sa_sigaction = 0x7fcd0bd3cf38}, sa_mask = {__val = {
              140518643453672, 82, 1716304128, 94629023039984, 
              94629023039984, 0, 94629021885548, 140721559928496, 
              94628991947216, 140721559930944, 94629022215616, 
              94629022248128, 140518642851078, 94629022945952, 
              140518809618048, 140518809600672}}, sa_flags = 360999149, 
          sa_restorer = 0x561089412dc0}
        sigs = {__val = {32, 0 <repeats 15 times>}}
        __cnt = <optimized out>
        __set = <optimized out>
        __cnt = <optimized out>
        __set = <optimized out>
#2  0x00005610872394a3 in ExceptionalCondition (
    conditionName=<optimized out>, errorType=<optimized out>, 
    fileName=<optimized out>, lineNumber=<optimized out>) at assert.c:54
No locals.
#3  0x00007fcd0bcee140 in ts_subspace_store_init (space=0x5610894dc070, 
    mcxt=0x5610894c52a0, max_items=100)
    at /home/runner/work/timescaledb/timescaledb/src/subspace_store.c:82
        old = 0x5610894c52a0
        sst = 0x5610894dd900
#4  0x00007fcd0bcba5ba in ts_hypertable_from_tupleinfo (ti=0x7ffc4a977f70)
    at /home/runner/work/timescaledb/timescaledb/src/hypertable.c:249
        namespace_oid = 2200
        h = 0x5610894e9f48
#5  0x00007fcd0bcbae78 in hypertable_tuple_add_stat (ti=0x7ffc4a977f70, 
    data=0x7ffc4a978110)
    at /home/runner/work/timescaledb/timescaledb/src/hypertable.c:400
        stat = 0x7ffc4a978110
        ht = 0x679833341b646100
        isnull = 127
        datum = 94629021885548
#6  0x00007fcd0bcec293 in ts_scanner_scan (ctx=0x7ffc4a978030)
    at /home/runner/work/timescaledb/timescaledb/src/scanner.c:356
        ictx = {tablerel = 0x7fcd0bbff830, indexrel = 0x7fcd0bc03c88, 
          tinfo = {scanrel = 0x7fcd0bbff830, slot = 0x5610894c70d0, tid = {
              ip_blkid = {bi_hi = 0, bi_lo = 0}, ip_posid = 2}, ituple = 0x0, 
            ituple_desc = 0x7fcd0bc03fb8, lockresult = HeapTupleMayBeUpdated, 
            count = 1, mctx = 0x5610894c52a0}, scan = {
            index_scan = 0x5610894c60b0, table_scan = 0x5610894c60b0}, 
          sctx = 0x7ffc4a978030, registered_snapshot = true, closed = false}
        tinfo = 0x7ffc4a977f70
#7  0x00007fcd0bcbad78 in hypertable_scan_limit_internal (scankey=0x0, 
    num_scankeys=0, indexid=0, 
    on_tuple_found=0x7fcd0bcbae33 <hypertable_tuple_add_stat>, 
    scandata=0x7ffc4a978110, limit=-1, lock=1, tuplock=false, 
    mctx=0x5610894c52a0, filter=0x0)
    at /home/runner/work/timescaledb/timescaledb/src/hypertable.c:384
        catalog = 0x7fcd0bf898c0 <s_catalog>
        scanctx = {table = 26718, index = 26728, scankey = 0x0, nkeys = 0, 
          norderbys = 0, limit = -1, want_itup = false, keeplock = false, 
          lockmode = 1, result_mctx = 0x5610894c52a0, tuplock = 0x0, 
          scandirection = ForwardScanDirection, snapshot = 0x5610894e8588, 
          data = 0x7ffc4a978110, prescan = 0x0, postscan = 0x0, filter = 0x0, 
          tuple_found = 0x7fcd0bcbae33 <hypertable_tuple_add_stat>}
#8  0x00007fcd0bcbb0ee in ts_number_of_hypertables (stat=0x7ffc4a978110)
    at /home/runner/work/timescaledb/timescaledb/src/hypertable.c:446
No locals.
#9  0x00007fcd0bd0f2e3 in get_num_hypertables ()
    at /home/runner/work/timescaledb/timescaledb/src/telemetry/telemetry.c:191
        stat = {num_hypertables_user = 0, num_hypertables_compressed = 0, 
          num_hypertables_distributed_members = 0, 
          num_hypertables_distributed = 0, 
          num_hypertables_distributed_and_replicated = 0, 
          num_hypertables_total = 0}
        buf = 0x5610894db3d0
#10 0x00007fcd0bd0fe9e in build_version_body ()
    at /home/runner/work/timescaledb/timescaledb/src/telemetry/telemetry.c:353
        ext_key = {type = jbvNull, val = {numeric = 0x679833341b646100, 
            boolean = false, string = {len = 459563264, val = 0x0}, array = {
              nElems = 459563264, elems = 0x0, rawScalar = 224}, object = {
              nPairs = 459563264, pairs = 0x0}, binary = {len = 459563264, 
              data = 0x0}}}
        license_info_key = {type = 2303499744, val = {
            numeric = 0x679833341b646100, boolean = false, string = {
              len = 459563264, val = 0x0}, array = {nElems = 459563264, 
              elems = 0x0, rawScalar = 224}, object = {nPairs = 459563264, 
              pairs = 0x0}, binary = {len = 459563264, data = 0x0}}}
        result = 0x5610894c9de0
        jb = 0x0
        jtext = 0x7fcd16408c95
        osinfo = {sysname = "Linux", '\000' <repeats 122 times>, 
          version = "#35~18.04.1-Ubuntu SMP Mon Jul 13 12:54:45 UTC 2020", '\000' <repeats 76 times>, 
          release = "5.3.0-1034-azure", '\000' <repeats 111 times>, 
          pretty_version = "Ubuntu 18.04.5 LTS", '\000' <repeats 109 times>, 
          has_pretty_version = true}
        parse_state = 0x5610894c5fd0
        sizes = {uncompressed_heap_size = 0, uncompressed_toast_size = 0, 
          uncompressed_index_size = 0, compressed_heap_size = 0, 
          compressed_toast_size = 0, compressed_index_size = 0}
#11 0x00007fcd0bd106c9 in ts_build_version_request (
    host=0x7fcd0bd420f8 "telemetry.timescale.com", 
    path=0x7fcd0bd420ec "/v1/metrics")
    at /home/runner/work/timescaledb/timescaledb/src/telemetry/telemetry.c:439
        body_len_string = "\211\020V\000"
        req = 0x561087741700 <TopTransactionStateData>
        jtext = 0x5610894c53b8
#12 0x00007fcd0bd10cbe in ts_telemetry_main (
    host=0x7fcd0bd420f8 "telemetry.timescale.com", 
    path=0x7fcd0bd420ec "/v1/metrics", service=0x7fcd0bd4208f "https")
    at /home/runner/work/timescaledb/timescaledb/src/telemetry/telemetry.c:519
        err = 22032
        conn = 0x5610894c53b8
        req = 0x7fcd0bd3f3aa
        rsp = 0x0
        started = true
        json = 0x0
        __func__ = "ts_telemetry_main"
#13 0x00007fcd0bd10b94 in ts_telemetry_main_wrapper ()
    at /home/runner/work/timescaledb/timescaledb/src/telemetry/telemetry.c:495
No locals.
#14 0x00007fcd0bcfda5c in ts_bgw_job_run_and_set_next_start (
    job=0x5610894208c8, func=0x7fcd0bd10b64 <ts_telemetry_main_wrapper>, 
    initial_runs=12, next_interval=0x7ffc4a9785f0)
    at /home/runner/work/timescaledb/timescaledb/src/bgw/job.c:818
        job_stat = 0x56108941acc0
        ret = false
#15 0x00007fcd0bcfccc7 in ts_bgw_job_execute (job=0x5610894208c8)
    at /home/runner/work/timescaledb/timescaledb/src/bgw/job.c:606
        one_hour = {time = 3600000000, day = 0, month = 0}
#16 0x00007fcd0bcfd56e in ts_bgw_job_entrypoint (fcinfo=0x684c)
    at /home/runner/work/timescaledb/timescaledb/src/bgw/job.c:726
        save_exception_stack = 0x7ffc4a978750
        save_context_stack = 0x0
        local_sigjmp_buf = {{__jmpbuf = {94629021885548, 8818841156810399646, 
              94628991947216, 140721559930944, 94629022215616, 
              94629022248128, 8818841156778942366, 8791118824986599326}, 
            __mask_was_saved = 0, __saved_mask = {__val = {140518813434231, 
                94629022248128, 94629021885548, 94629022241984, 
                94629021885548, 94628986751975, 140518643192227, 0, 
                94628986882669, 94629022269368, 140518643192227, 
                94629021885548, 94628986751996, 0, 94629021885548, 
                94629021885452}}}}
        db_oid = 26700
        user_uid = 16388
        job_id = 1
        job = 0x5610894208c8
        res = JOB_FAILURE
        got_lock = true
        __func__ = "ts_bgw_job_entrypoint"
#17 0x000056108708ec54 in StartBackgroundWorker () at bgworker.c:834
        local_sigjmp_buf = {{__jmpbuf = {94629021885248, 
              -8819661733155610722, 94628991947216, 140721559930944, 
              94629022215616, 94629022248128, 8818841156816691102, 
              3007079021253975966}, __mask_was_saved = 1, __saved_mask = {
              __val = {18446744066192964103, 140721559930944, 94629022215616, 
                94629022248128, 94628986882286, 94629021906416, 
                94629021906416, 0, 94628986909905, 94629021906632, 
                94628986882104, 0, 0, 140721559930944, 0, 0}}}}
        worker = 0x5610893c2340
        entrypt = <optimized out>
        __func__ = "StartBackgroundWorker"
#18 0x000056108709afdb in do_start_bgworker (rw=0x56108941aa80)
    at postmaster.c:5713
        worker_pid = <optimized out>
        worker_pid = <optimized out>
#19 maybe_start_bgworkers () at postmaster.c:5939
        rw = 0x56108941aa80
        num_launched = 0
        now = 0
        iter = {cur = 0x56108941acc0, next = 0x56108941a820, 
          prev = 0x561087744900 <BackgroundWorkerList>}
#20 0x000056108709b998 in sigusr1_handler (
    postgres_signal_arg=<optimized out>) at postmaster.c:5086
        save_errno = 4
        __func__ = "sigusr1_handler"
#21 <signal handler called>
No locals.
#22 0x00007fcd158df0f7 in __GI___select (nfds=nfds@entry=6, 
    readfds=readfds@entry=0x7ffc4a978f30, writefds=writefds@entry=0x0, 
    exceptfds=exceptfds@entry=0x0, timeout=timeout@entry=0x7ffc4a978e90)
    at ../sysdeps/unix/sysv/linux/select.c:41
        resultvar = 18446744073709551612
        sc_ret = <optimized out>
#23 0x0000561086dee492 in ServerLoop () at postmaster.c:1671
        timeout = {tv_sec = 59, tv_usec = 997136}
        rmask = {fds_bits = {48, 0 <repeats 15 times>}}
        selres = <optimized out>
        now = <optimized out>
        readmask = {fds_bits = {48, 0 <repeats 15 times>}}
        nSockets = <optimized out>
        last_lockfile_recheck_time = 1598949261
        last_touch_time = 1598949261
        __func__ = "ServerLoop"
#24 0x000056108709ce65 in PostmasterMain (argc=8, argv=0x5610893c0f70)
    at postmaster.c:1380
        opt = <optimized out>
        status = <optimized out>
        userDoption = <optimized out>
        listen_addr_saved = <optimized out>
        i = <optimized out>
        output_config_variable = <optimized out>
        __func__ = "PostmasterMain"
#25 0x0000561086df08c5 in main (argc=8, argv=0x5610893c0f70) at main.c:228
No locals.
(gdb) quit
           PID: 13057 (postgres)
           UID: 1001 (runner)
           GID: 116 (docker)
        Signal: 6 (ABRT)
     Timestamp: Tue 2020-09-01 08:34:33 UTC (1min 46s ago)
  Command Line: postgres: Telemetry Reporter [1]   
    Executable: /home/runner/postgresql/bin/postgres
 Control Group: /system.slice/runner-provisioner.service
          Unit: runner-provisioner.service
         Slice: system.slice
       Boot ID: c1ec073eb74e4b92b2bd60b9b5572c16
    Machine ID: f49a0ad817d846c783a5b12e783fdf6c
      Hostname: fv-az50
       Storage: /var/lib/systemd/coredump/core.postgres.1001.c1ec073eb74e4b92b2bd60b9b5572c16.13057.1598949273000000.lz4
       Message: Process 13057 (postgres) of user 1001 dumped core.
```

**Comment by svenklemm** [comment]
The code thinks it has a hypertable with closed dimension as primary dimension:
```
(gdb) p *space
$17 = {hypertable_id = 1, main_table_relid = 27262, capacity = 2, num_dimensions = 1, dimensions = 0x5610894dc080}
(gdb) p space->dimensions[0].type
$18 = DIMENSION_TYPE_CLOSED
``´

**Comment by svenklemm** [comment]
closing this since it is an old issue and we havent seen this recently
