### ISSUE TITLE
Segmentation Fault on Continuous Aggregate Data Refresh 

### ISSUE THREAD

**Issue by brianbenns** [timescale/timescaledb#2655]
**Relevant system information:**
 - OS: Ubuntu 18.04.5 LTS
 - PostgreSQL version: 12.5
 - TimescaleDB version: 2.0.0-rc3 
 - Installation method: apt install
 - `raw_data` hypertable contains about 2.5M rows per minute and few hundred million rows in total. Though I also tested this on a 100 row table and got the same result.

**Describe the bug**
When a continuous aggregate is created or refreshed with a `GROUP BY...HAVING...` clause it causes a segmentation fault. .

**To Reproduce**

```
CREATE MATERIALIZED VIEW search_query_count_1m
WITH (timescaledb.continuous) as
SELECT  search_query, 
        count(search_query) as count,
        time_bucket(INTERVAL '1 minute', time) AS bucket
FROM raw_data 
WHERE search_query is not null 
AND LENGTH(TRIM(both from search_query))>0 
GROUP BY search_query, bucket
HAVING count(search_query) > 50;
```

**Expected behavior**
The continuous aggregate to be successfully created and the view to only contain search queries with counts> 50. 

**Actual behavior**
A segmentation fault crashes the Postgres server

Logs:

```
2020-11-17 20:41:46.357 UTC [28429] LOG:  server process (PID 4039) was terminated by signal 11: Segmentation fault
2020-11-17 20:41:46.357 UTC [28429] DETAIL:  Failed process was running: CALL refresh_continuous_aggregate('search_query_count_1m', NULL, NULL);
2020-11-17 20:41:46.357 UTC [28429] LOG:  terminating any other active server processes
2020-11-17 20:41:46.357 UTC [3834] repuser@[unknown] WARNING:  terminating connection because of crash of another server process
2020-11-17 20:41:46.357 UTC [3834] repuser@[unknown] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory. 
```

**Additional context**
In some additional testing this seems to not happen if the `HAVING` clause contains an `avg()` function instead of a `count()` function based off of the same hypertable. But two differeing `HAVING count()...` queries caused the same issue. The same query when ran standalone and not for creating a continuous aggregate completes fine.

**Comment by k-rus** [comment]
Thank you for reporting!
Have you used the same view in earlier version of TimescaleDB, e.g., one of 1.7?

**Comment by brianbenns** [comment]
> Thank you for reporting!
> Have you used the same view in earlier version of TimescaleDB, e.g., one of 1.7?

No I didn't try this specific view when I was running 1.7.

**Comment by svenklemm** [comment]
Testcase to reproduce:
```
create table raw_data(time timestamptz, search_query text);
select create_hypertable('raw_data','time');
insert into raw_data select '2000-01-01','Q1';

CREATE MATERIALIZED VIEW search_query_count_1m WITH (timescaledb.continuous) as SELECT  search_query,count(search_query) as count,time_bucket(INTERVAL '1 minute', time) AS bucket FROM raw_data WHERE search_query is not null AND LENGTH(TRIM(both from search_query))>0 GROUP BY search_query, bucket HAVING count(search_query) > 50;
```

**Comment by mkindahl** [comment]
Seems to be related to #2815

**Comment by mkindahl** [comment]
Stack trace for this is:

```
(gdb) bt
#0  0x0000560ed6753b6d in heap_compute_data_size (tupleDesc=0x560ed8710e50, values=0x560ed875f170, isnull=0x560ed875f190) at heaptuple.c:139
#1  0x0000560ed67564c4 in heap_form_minimal_tuple (tupleDescriptor=0x560ed8710e50, values=0x560ed875f170, isnull=0x560ed875f190) at heaptuple.c:1396
#2  0x0000560ed69b2b6e in tts_virtual_copy_minimal_tuple (slot=0x560ed875f128) at execTuples.c:282
#3  0x0000560ed6d5e717 in ExecCopySlotMinimalTuple (slot=0x560ed875f128) at ../../../../src/include/executor/tuptable.h:465
#4  0x0000560ed6d65ab5 in copytup_heap (state=0x560ed87a1110, stup=0x7ffefa308060, tup=0x560ed875f128) at tuplesort.c:3584
#5  0x0000560ed6d60ff9 in tuplesort_puttupleslot (state=0x560ed87a1110, slot=0x560ed875f128) at tuplesort.c:1443
#6  0x0000560ed69e0b73 in ExecSort (pstate=0x560ed875db68) at nodeSort.c:112
#7  0x0000560ed69ae297 in ExecProcNodeFirst (node=0x560ed875db68) at execProcnode.c:445
#8  0x0000560ed69bbe4d in ExecProcNode (node=0x560ed875db68) at ../../../src/include/executor/executor.h:239
#9  0x0000560ed69bc2d0 in fetch_input_tuple (aggstate=0x560ed8734a90) at nodeAgg.c:406
#10 0x0000560ed69be5d8 in agg_retrieve_direct (aggstate=0x560ed8734a90) at nodeAgg.c:1748
#11 0x0000560ed69be224 in ExecAgg (pstate=0x560ed8734a90) at nodeAgg.c:1563
#12 0x0000560ed69ae297 in ExecProcNodeFirst (node=0x560ed8734a90) at execProcnode.c:445
#13 0x00007eff528a951a in ExecProcNode (node=0x560ed8734a90) at /usr/local/pgsql/12.3/include/server/executor/executor.h:239
#14 0x00007eff528a96b6 in chunk_dispatch_exec (node=0x560ed8733e90) at /home/mats/repos/timescaledb-bugs/src/chunk_dispatch_state.c:110
#15 0x0000560ed69c4c1f in ExecCustomScan (pstate=0x560ed8733e90) at nodeCustom.c:116
#16 0x0000560ed69ae297 in ExecProcNodeFirst (node=0x560ed8733e90) at execProcnode.c:445
#17 0x0000560ed69d8632 in ExecProcNode (node=0x560ed8733e90) at ../../../src/include/executor/executor.h:239
#18 0x0000560ed69db637 in ExecModifyTable (pstate=0x560ed8733918) at nodeModifyTable.c:2079
#19 0x0000560ed69ae297 in ExecProcNodeFirst (node=0x560ed8733918) at execProcnode.c:445
#20 0x00007eff528c4029 in ExecProcNode (node=0x560ed8733918) at /usr/local/pgsql/12.3/include/server/executor/executor.h:239
#21 0x00007eff528c4235 in hypertable_insert_exec (node=0x560ed8733438) at /home/mats/repos/timescaledb-bugs/src/hypertable_insert.c:110
#22 0x0000560ed69c4c1f in ExecCustomScan (pstate=0x560ed8733438) at nodeCustom.c:116
#23 0x0000560ed69ae297 in ExecProcNodeFirst (node=0x560ed8733438) at execProcnode.c:445
#24 0x0000560ed69a3c1c in ExecProcNode (node=0x560ed8733438) at ../../../src/include/executor/executor.h:239
#25 0x0000560ed69a611a in ExecutePlan (estate=0x560ed8732ed0, planstate=0x560ed8733438, use_parallel_mode=false, operation=CMD_INSERT, sendTuples=false, numberTuples=0, direction=ForwardScanDirection, 
    dest=0x560ed6fe1aa0 <spi_printtupDR>, execute_once=true) at execMain.c:1646
#26 0x0000560ed69a4140 in standard_ExecutorRun (queryDesc=0x560ed88585f0, direction=ForwardScanDirection, count=0, execute_once=true) at execMain.c:364
#27 0x0000560ed69a3fde in ExecutorRun (queryDesc=0x560ed88585f0, direction=ForwardScanDirection, count=0, execute_once=true) at execMain.c:308
#28 0x0000560ed69f3298 in _SPI_pquery (queryDesc=0x560ed88585f0, fire_triggers=true, tcount=0) at spi.c:2521
#29 0x0000560ed69f2d36 in _SPI_execute_plan (plan=0x7ffefa3087a0, paramLI=0x0, snapshot=0x0, crosscheck_snapshot=0x0, read_only=false, fire_triggers=true, tcount=0) at spi.c:2296
#30 0x0000560ed69efed0 in SPI_execute_with_args (
    src=0x560ed879dae0 "INSERT INTO _timescaledb_internal._materialized_hypertable_2 SELECT * FROM _timescaledb_internal._partial_view_2 AS I WHERE I.bucket >= 'Sun Nov 23 16:00:00 4714 PST BC' AND I.bucket < 'Sat Jan 01 00:"..., 
    nargs=0, argtypes=0x0, Values=0x0, Nulls=0x0, read_only=false, tcount=0) at spi.c:665
#31 0x00007eff528160b1 in spi_insert_materializations (partial_view=..., materialization_table=..., time_column_name=0x560ed86aaec8, materialization_range=..., chunk_condition=0x560ed879d120 "")
    at /home/mats/repos/timescaledb-bugs/tsl/src/continuous_aggs/materialize.c:299
#32 0x00007eff52815d7a in spi_update_materializations (partial_view=..., materialization_table=..., time_column_name=0x560ed86aaec8, invalidation_range=..., chunk_id=0)
    at /home/mats/repos/timescaledb-bugs/tsl/src/continuous_aggs/materialize.c:226
#33 0x00007eff528159a5 in continuous_agg_update_materialization (partial_view=..., materialization_table=..., time_column_name=0x560ed86aaec8, new_materialization_range=..., invalidation_range=..., bucket_width=60000000, chunk_id=0)
    at /home/mats/repos/timescaledb-bugs/tsl/src/continuous_aggs/materialize.c:92
#34 0x00007eff52816bd7 in continuous_agg_refresh_execute (refresh=0x7ffefa308b40, bucketed_refresh_window=0x7ffefa308b20, chunk_id=0) at /home/mats/repos/timescaledb-bugs/tsl/src/continuous_aggs/refresh.c:259
#35 0x00007eff52816e6b in continuous_agg_refresh_with_window (cagg=0x560ed86aa150, refresh_window=0x7ffefa308dc0, invalidations=0x560ed86aa020, chunk_id=0) at /home/mats/repos/timescaledb-bugs/tsl/src/continuous_aggs/refresh.c:330
#36 0x00007eff528172cf in process_cagg_invalidations_and_refresh (cagg=0x560ed86aa150, refresh_window=0x7ffefa308dc0, verbose=false, chunk_id=0) at /home/mats/repos/timescaledb-bugs/tsl/src/continuous_aggs/refresh.c:443
#37 0x00007eff52817535 in continuous_agg_refresh_internal (cagg=0x560ed86aa150, refresh_window_arg=0x7ffefa308e20, verbose=false) at /home/mats/repos/timescaledb-bugs/tsl/src/continuous_aggs/refresh.c:544
#38 0x00007eff5281717d in continuous_agg_refresh (fcinfo=0x7ffefa308fd0) at /home/mats/repos/timescaledb-bugs/tsl/src/continuous_aggs/refresh.c:402
#39 0x00007eff528afba6 in ts_continuous_agg_refresh (fcinfo=0x7ffefa308fd0) at /home/mats/repos/timescaledb-bugs/src/cross_module_fn.c:70
#40 0x0000560ed6926388 in ExecuteCallStmt (stmt=0x560ed85c0fe8, params=0x0, atomic=false, dest=0x560ed85c1728) at functioncmds.c:2410
#41 0x0000560ed6b9fa45 in standard_ProcessUtility (pstmt=0x560ed85c1698, queryString=0x560ed85c0380 "CALL refresh_continuous_aggregate('search_query_count_1m', NULL, NULL);", context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, 
    dest=0x560ed85c1728, completionTag=0x7ffefa309bf0 "") at utility.c:652
#42 0x00007eff5cbd724f in loader_process_utility_hook (pstmt=0x560ed85c1698, query_string=0x560ed85c0380 "CALL refresh_continuous_aggregate('search_query_count_1m', NULL, NULL);", context=PROCESS_UTILITY_TOPLEVEL, params=0x0, 
    queryEnv=0x0, dest=0x560ed85c1728, completion_tag=0x7ffefa309bf0 "") at /home/mats/repos/timescaledb-bugs/src/loader/loader.c:510
#43 0x00007eff528d0c78 in prev_ProcessUtility (args=0x7ffefa309880) at /home/mats/repos/timescaledb-bugs/src/process_utility.c:88
#44 0x00007eff528d7b2f in timescaledb_ddl_command_start (pstmt=0x560ed85c1698, query_string=0x560ed85c0380 "CALL refresh_continuous_aggregate('search_query_count_1m', NULL, NULL);", context=PROCESS_UTILITY_TOPLEVEL, params=0x0, 
    queryEnv=0x0, dest=0x560ed85c1728, completion_tag=0x7ffefa309bf0 "") at /home/mats/repos/timescaledb-bugs/src/process_utility.c:3936
#45 0x0000560ed6b9f1e5 in ProcessUtility (pstmt=0x560ed85c1698, queryString=0x560ed85c0380 "CALL refresh_continuous_aggregate('search_query_count_1m', NULL, NULL);", context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, 
    dest=0x560ed85c1728, completionTag=0x7ffefa309bf0 "") at utility.c:356
#46 0x0000560ed6b9e323 in PortalRunUtility (portal=0x560ed8667a80, pstmt=0x560ed85c1698, isTopLevel=true, setHoldSnapshot=false, dest=0x560ed85c1728, completionTag=0x7ffefa309bf0 "") at pquery.c:1175
--Type <RET> for more, q to quit, c to continue without paging-- 
#47 0x0000560ed6b9e513 in PortalRunMulti (portal=0x560ed8667a80, isTopLevel=true, setHoldSnapshot=false, dest=0x560ed85c1728, altdest=0x560ed85c1728, completionTag=0x7ffefa309bf0 "") at pquery.c:1321
#48 0x0000560ed6b9da39 in PortalRun (portal=0x560ed8667a80, count=9223372036854775807, isTopLevel=true, run_once=true, dest=0x560ed85c1728, altdest=0x560ed85c1728, completionTag=0x7ffefa309bf0 "") at pquery.c:796
#49 0x0000560ed6b9758a in exec_simple_query (query_string=0x560ed85c0380 "CALL refresh_continuous_aggregate('search_query_count_1m', NULL, NULL);") at postgres.c:1215
#50 0x0000560ed6b9bb88 in PostgresMain (argc=1, argv=0x560ed861d2b0, dbname=0x560ed861cff8 "db_continuous_aggs_create", username=0x560ed85bc150 "default_perm_user") at postgres.c:4247
#51 0x0000560ed6af6d13 in BackendRun (port=0x560ed86129c0) at postmaster.c:4448
#52 0x0000560ed6af640e in BackendStartup (port=0x560ed86129c0) at postmaster.c:4139
#53 0x0000560ed6af2646 in ServerLoop () at postmaster.c:1704
#54 0x0000560ed6af1ddd in PostmasterMain (argc=8, argv=0x560ed85b9fd0) at postmaster.c:1377
#55 0x0000560ed6a134ed in main (argc=8, argv=0x560ed85b9fd0) at main.c:228
```

**Comment by erimatnor** [comment]
I wonder if this isn't specific to continuous aggregates at all. The error seems to occur when executing the INSERT statement into the materialized hypertable. My guess is that this is an issue with the hypertable insert path and a similar insert executed manually would also crash. At least it is an interesting thing to test.

**Comment by mkindahl** [comment]
Expanding the partial view and doing the insert works fine:

```
WITH partial_view AS (
  SELECT raw_data.search_query, 
     _timescaledb_internal.partialize_agg(count(raw_data.search_query)) AS agg_2_2, 
     time_bucket('@ 1 min'::interval, raw_data."time") AS bucket, 
     _timescaledb_internal.partialize_agg(count(raw_data."time")) AS agg_0_4, 
     _timescaledb_internal.chunk_id_from_relid(raw_data.tableoid) AS chunk_id 
    FROM raw_data 
   WHERE raw_data.search_query IS NOT NULL AND length(btrim(raw_data.search_query)) > 0 
   GROUP BY raw_data.search_query, (time_bucket('@ 1 min'::interval, raw_data."time")), (_timescaledb_internal.chunk_id_from_relid(raw_data.tableoid))
) INSERT INTO _timescaledb_internal._materialized_hypertable_2
SELECT * FROM partial_view AS I
WHERE I.bucket >= 'Sun Nov 23 16:00:00 4714 PST BC' AND I.bucket < 'Sat Jan 01 00:01:00 2000 PST';
```

Inserting into the partial view directly causes the same crash as the refresh method:

```
INSERT INTO _timescaledb_internal._materialized_hypertable_2
SELECT * FROM _timescaledb_internal._partial_view_2 AS I
WHERE I.bucket >= 'Sun Nov 23 16:00:00 4714 PST BC' AND I.bucket < 'Sat Jan 01 00:01:00 2000 PST';
```

@svenklemm Suggested that the internal references in the partial view is broken, which the above seems to confirm.

**Comment by gayyappan** [comment]
When the having clause entry also appears in the targetlist for the query, the having clause entry is not correctly processed. This appears to be the root cause of the error.
