### ISSUE TITLE
ERROR: right sibling's left-link doesn't match

### ISSUE THREAD

**Issue by brettwooldridge** [timescale/timescaledb#2773]
**Relevant system information:**
 - OS: Tinycore Linux 10
 - postgres (PostgreSQL) 11.9
 - TimescaleDB version: 1.7.4
 - Installation method: source

**Describe the bug**
Batch insert through JDBC is failing with the following error:
```
Caused by: org.postgresql.util.PSQLException: ERROR: right sibling's left-link doesn't match: block 1942051 links to 1947220 instead of expected 4344 in index "_hyper_2_2_chunk_monitor_data3_ndx"
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553) ~[postgresql-42.2.18.jar:42.2.18]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285) ~[postgresql-42.2.18.jar:42.2.18]
	at org.postgresql.core.v3.QueryExecutorImpl.flushIfDeadlockRisk(QueryExecutorImpl.java:1404) ~[postgresql-42.2.18.jar:42.2.18]
	at org.postgresql.core.v3.QueryExecutorImpl.sendQuery(QueryExecutorImpl.java:1429) ~[postgresql-42.2.18.jar:42.2.18]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:507) ~[postgresql-42.2.18.jar:42.2.18]
	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:870) ~[postgresql-42.2.18.jar:42.2.18]
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:893) ~[postgresql-42.2.18.jar:42.2.18]
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1644) ~[postgresql-42.2.18.jar:42.2.18]
 ...
```
This error suddenly started appearing, I do not know the cause, or how to reproduce.  What is this an indication of?

**Comment by brettwooldridge** [comment]
Dropping and re-creating the index seems to have resolved the continuing error in our logs. However, I am curious is this is a known issue or whether the fact that this error occurred leads TimescaleDB devs to some conclusion?

**Comment by mfreed** [comment]
Hi @brettwooldridge Can you saw anything more about scenario which led to this?  I don't recall ever seeing such an error before.

**Comment by brettwooldridge** [comment]
Unfortunately I do not have much additional information. From what I understand this occurred on a VM running in our lab. One of our engineers reports that the machine 1) seems to have encountered out of memory errors, according to logs viewed at the time, and 2) was unresponsive and was restarted with a hard reset. It was after the VM was restarted that the error started to appear. At that point it seem to have been logged upon every attempted insert (and thus flooded and rolled all of the logs). I surmise that either the out of memory error led to an inconsistent index state, or the hard reset resulted in partially written data to disk that left the index in an inconsistent state.

**Comment by krvajal** [comment]
I am having the same issue, it started happening after a node crashed on timescale cloud

**Comment by NunoFilipeSantos** [comment]
@brettwooldridge and @krvajal can you please try with our latest TimescaleDB 2.4.2 (PG 12 or PG13) and get back to us?

**Comment by NunoFilipeSantos** [comment]
Hi @brettwooldridge ! We're closing this issue. If you can reproduce it on TimescaleDB 2.5.0, feel free to reopen it. 👍
