### ISSUE TITLE
chunk_map null in call to translate_clause

### ISSUE THREAD

**Issue by kitwestneat** [timescale/timescaledb#3037]
**Relevant system information:**
- docker image 2.1.0-pg12 running on fedora host
- postgres (PostgreSQL) 12.6
- TimescaleDB version 2.1.0

**Describe the bug**
When inserting a row into tsdb, it segfaults. I recompiled with debugging symbols and found that translate_clause is called with chunk_map NULL, which causes a segfault here:
```
156             clause = castNode(List,
157                 map_variable_attnos_compat((Node *) clause,
158                     INNER_VAR,
159                     0,
160                     chunk_map->attrMap,
```

setup_on_conflict_state is also called with a NULL chunk_map. 

chunk_map appears to be set in setup_on_conflict_state by calling convert_tuples_by_name, which looks like can return NULL if no map is needed. 

**Backtrace**
```
#0  0x00007f9406ba61ac in translate_clause (inclause=0x7f94069ee420, chunk_map=0x0, varno=1, hyper_rel=0x7f9406c977f0, chunk_rel=0x7f9406976278) at /build/timescaledb/src/chunk_insert_state.c:156
#1  0x00007f9406ba6708 in setup_on_conflict_state (state=0x7f940695f480, dispatch=0x7f9406a3ecf8, chunk_map=0x0) at /build/timescaledb/src/chunk_insert_state.c:395
#2  0x00007f9406ba6a91 in adjust_projections (cis=0x7f940695f480, dispatch=0x7f9406a3ecf8, rowtype=496969) at /build/timescaledb/src/chunk_insert_state.c:521
#3  0x00007f9406ba6de1 in ts_chunk_insert_state_create (chunk=0x7f9406a08340, dispatch=0x7f9406a3ecf8) at /build/timescaledb/src/chunk_insert_state.c:613
#4  0x00007f9406ba2ea4 in ts_chunk_dispatch_get_chunk_insert_state (dispatch=0x7f9406a3ecf8, point=0x7f9406a07ca0, on_chunk_changed=0x7f9406ba336a <on_chunk_insert_state_changed>, data=0x7f9406a34d28) at /build/timescaledb/src/chunk_dispatch.c:133
#5  0x00007f9406ba34fa in chunk_dispatch_exec (node=0x7f9406a34d28) at /build/timescaledb/src/chunk_dispatch_state.c:133
#6  0x00005651a5d6e060 in ExecModifyTable ()
```

**To Reproduce**
I haven't tried reproducing it on a clean DB, but here are the query and values we are trying to run:
```
query "INSERT INTO campaign_dates \n
        (cd_name,cd_date,cd_dfp_revenue,cd_dfp_impressions,cd_dfp_georev,cd_dfp_devrev,cd_ga_pageviews,cd_ga_sessions,cd_ga_instant_pageviews,cd_ga_instant_sessions,cd_ga_geo,cd_fb_est_instant_revenue,cd_credits) 
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)\n        
ON CONFLICT  (cd_date, cd_name) 
DO UPDATE SET\n        
(cd_dfp_revenue,cd_dfp_impressions,cd_dfp_georev,cd_dfp_devrev,cd_ga_pageviews,cd_ga_sessions,cd_ga_instant_pageviews,cd_ga_instant_sessions,cd_ga_geo,cd_fb_est_instant_revenue,cd_fb_campaign_id,cd_fb_impressions,cd_fb_account_id,cd_fb_budget,cd_fb_start_time,cd_fb_spend,cd_fb_is_instant,cd_credits) = 
row(EXCLUDED.cd_dfp_revenue,EXCLUDED.cd_dfp_impressions,EXCLUDED.cd_dfp_georev,EXCLUDED.cd_dfp_devrev,EXCLUDED.cd_ga_pageviews,EXCLUDED.cd_ga_sessions,EXCLUDED.cd_ga_instant_pageviews,EXCLUDED.cd_ga_instant_sessions,EXCLUDED.cd_ga_geo,EXCLUDED.cd_fb_est_instant_revenue,EXCLUDED.cd_fb_campaign_id,EXCLUDED.cd_fb_impressions,EXCLUDED.cd_fb_account_id,EXCLUDED.cd_fb_budget,EXCLUDED.cd_fb_start_time,EXCLUDED.cd_fb_spend,EXCLUDED.cd_fb_is_instant,EXCLUDED.cd_credits)\n        \n    "
values [
    "campaign",
    "2021-03-11",
    0.006983,
    10,
    "[{\"country\":\"Australia\",\"revenue\":0.00273},{\"country\":\"United States\",\"revenue\":0.004253}]",
    "[{\"device\":\"Desktop\",\"revenue\":0.006853},{\"device\":\"Smartphone\",\"revenue\":0.00013}]",
    1,
    1,
    0,
    0,
    "[{\"country\":\"Australia\",\"sessions\":1,\"pageviews\":1}]",
    0,
    "[]"
]
```

Let me know if the schema information would be helpful, or if there is any other information that'd be useful. Thanks.

**Comment by svenklemm** [comment]
Could you provide a minimal example script that fails in a fresh database.
