### ISSUE TITLE
ERROR: new row for relation "_hyper_4_25_chunk" violates check constraint "constraint_25"

### ISSUE THREAD

**Issue by jonmd** [timescale/timescaledb#306]
Hi there

I'm experiencing constraint errors when **upserting values in TimescaleDB 0.6 and 0.6.1 via the PostgreSQL JDBC driver**. I'm using v42.1.4 (also tested with v42.1.3). The problematic statements are the ones that insert the **first** row in a chunk (in my case "2011-01-26" is one such example).

Keep in mind that this table uses a **date** type column, I have not had similar problems with timestamptz columns.

When copy-pasting the exact same statement into psql, it just works.

**Statement:**

```
insert into plain_data_d(curve_id, at, value) VALUES (657, '2011-01-26', 999999.9) on conflict (curve_id, at) do update set value = 999999.0
```

**Java error/stacktrace:**

```
Exception in thread "main" org.postgresql.util.PSQLException: ERROR: new row for relation "_hyper_4_25_chunk" violates check constraint "constraint_25"
  Detail: Failing row contains (657, 2011-01-26, 999999.900000000023).
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2476)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2189)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:300)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:301)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:287)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:264)
	at org.postgresql.jdbc.PgStatement.executeUpdate(PgStatement.java:244)
	at timescaledb.TimescaleDB.main(TimescaleDB.java:25)
```

**Postgresql log:** Using your docker image with no extra configuration.

```
ERROR:  new row for relation "_hyper_4_25_chunk" violates check constraint "constraint_25"
DETAIL:  Failing row contains (657, 2011-01-26, 999999.900000000023).
STATEMENT:  insert into plain_data_d(curve_id, at, value) VALUES (657, '2011-01-26', 999999.9) on conflict (curve_id, at) do update set value = 999999.0
```

**Schema:** As you can see, 2011-01-26 is the start of chunk 4_26. Running the same code on other dates at the start of chunks causes the same constraint errors.

```
data1=# \d plain_data_d
                     Table "public.plain_data_d"
  Column  |           Type           | Collation | Nullable | Default 
----------+--------------------------+-----------+----------+---------
 curve_id | integer                  |           | not null | 
 at       | date                     |           | not null | 
 value    | double precision         |           | not null | 
Indexes:
    "plain_data_d_pkey" PRIMARY KEY, btree (curve_id, at)
    "plain_data_d_at_idx" btree (at DESC)

data1=# \d _timescaledb_internal._hyper_4_25_chunk
           Table "_timescaledb_internal._hyper_4_25_chunk"
  Column  |           Type           | Collation | Nullable | Default 
----------+--------------------------+-----------+----------+---------
 curve_id | integer                  |           | not null | 
 at       | date                     |           | not null | 
 value    | double precision         |           | not null | 
Indexes:
    "25_25_plain_data_d_pkey" PRIMARY KEY, btree (curve_id, at)
    "_hyper_4_25_chunk_plain_data_d_at_idx" btree (at DESC)
Check constraints:
    "constraint_25" CHECK (at >= '2009-01-06'::date AND at < '2011-01-26'::date)
Inherits: plain_data_d

data1=# \d _timescaledb_internal._hyper_4_26_chunk
           Table "_timescaledb_internal._hyper_4_26_chunk"
  Column  |           Type           | Collation | Nullable | Default 
----------+--------------------------+-----------+----------+---------
 curve_id | integer                  |           | not null | 
 at       | date                     |           | not null | 
 value    | double precision         |           | not null | 
Indexes:
    "26_26_plain_data_d_pkey" PRIMARY KEY, btree (curve_id, at)
    "_hyper_4_26_chunk_plain_data_d_at_idx" btree (at DESC)
Check constraints:
    "constraint_26" CHECK (at >= '2011-01-26'::date AND at < '2013-02-14'::date)
Inherits: plain_data_d
```

**Example Java application:** (Requires the PostgreSQL driver in classpath to run.)

```
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.Properties;

public class TimescaleDB {

    /*
    create table plain_data_d(curve_id int, at date, value double precision, primary key (curve_id, at));
    select create_hypertable('plain_data_d', 'at', chunk_time_interval => interval '750 day');
     */

    public static void main(final String [] args) throws Exception {
        String url = "jdbc:postgresql://localhost:5432/data1";
        Properties props = new Properties();
        props.setProperty("user","user");
        props.setProperty("password","password");

        Connection connection = DriverManager.getConnection(url, props);
        Statement statement = connection.createStatement();

        final int updated = statement.executeUpdate("insert into data(curve_id, at, value) VALUES (657, '2011-01-26', 999999.9) on conflict (curve_id, at) do update set value = 999999.0");
        System.out.println(" -> " + updated);

        statement.close();
        connection.close();
    }
    
}
```

**Comment by cevian** [comment]
Hi @jonmd, thanks for reporting this bug. I just submitted a PR to fix this.

**Comment by jonmd** [comment]
Thanks, @cevian.
