### ISSUE TITLE
Assertion during regression testing in CI

### ISSUE THREAD

**Issue by mfundul** [timescale/timescaledb#3232]
**Relevant system information:**
 - OS: CI/CD PG13.2 Debug ubuntu-20.04
 - PostgreSQL version 13.2
 - TimescaleDB version 2.3.0-dev
 - Installation method: CI/CD in https://github.com/timescale/timescaledb/pull/3220

When the `PG13.2 Debug ubuntu-20.04` check runs in #3220 I got the following backtrace:

```
GNU gdb (Ubuntu 10.2-0ubuntu1~20.04~1) 10.2
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/runner/postgresql/bin/postgres...

warning: Can't open file /dev/shm/PostgreSQL.400693867 during file-backed mapping note processing

warning: Can't open file /dev/shm/PostgreSQL.1028535483 during file-backed mapping note processing

warning: Can't open file /dev/shm/PostgreSQL.1661398776 during file-backed mapping note processing

warning: Can't open file /dev/shm/PostgreSQL.202771827 during file-backed mapping note processing

warning: Can't open file /dev/zero (deleted) during file-backed mapping note processing

warning: Can't open file /SYSV0002b5d3 (deleted) during file-backed mapping note processing
[New LWP 13271]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `postgres: parallel worker for PID 13220                                       '.
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
(gdb) #0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {0, 0, 0, 0, 0, 94365966929744, 4611686018427387904, 
            0, 0, 140208896132314, 0, 94365966929790, 128, 0, 
            140729275952464, 140208890217920}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007f84ed04b859 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x7f84ed1debe4, 
            sa_sigaction = 0x7f84ed1debe4}, sa_mask = {__val = {1, 
              140208890576907, 3, 140729275952644, 12, 140208890576911, 2, 
              3703143295354929152, 7293410478706276660, 140729275952752, 
              7291948137683595756, 140208723674384, 17963909312303404544, 
              140729275952736, 0, 22}}, sa_flags = 377532016, 
          sa_restorer = 0x7ffe1680b1ec}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x000055d34a3c516b in ExceptionalCondition (
    conditionName=conditionName@entry=0x55d34a56be4a "result->tdrefcount == -1", errorType=errorType@entry=0x55d34a42001d "FailedAssertion", 
    fileName=fileName@entry=0x55d34a56be17 "typcache.c", 
    lineNumber=lineNumber@entry=2711) at assert.c:67
No locals.
#3  0x000055d34a3c2f14 in find_or_make_matching_shared_tupledesc (
    tupdesc=<optimized out>) at typcache.c:2711
        result = <optimized out>
        key = {u = {local_tupdesc = 0x55d34b6b3790, 
            shared_tupdesc = 94365991778192}, shared = false}
        record_table_entry = 0x7f84e2dc1070
        typmod_table_entry = <optimized out>
        shared_dp = 1099511698176
        found = true
        typmod = 2
        __func__ = "find_or_make_matching_shared_tupledesc"
#4  0x000055d34a3c47d7 in assign_record_type_typmod (tupDesc=<optimized out>, 
    tupDesc@entry=0x55d34b6b3790) at typcache.c:1873
        recentry = 0x55d34b6c83a8
        entDesc = <optimized out>
        found = false
        oldcxt = 0x55d34b6a9dc0
#5  0x000055d34a10962d in BlessTupleDesc (tupdesc=0x55d34b6b3790)
    at execTuples.c:2056
No locals.
#6  BlessTupleDesc (tupdesc=tupdesc@entry=0x55d34b6b3790) at execTuples.c:2052
No locals.
#7  0x000055d34a0f4487 in ExecEvalWholeRowVar (
    state=state@entry=0x55d34b6a77f8, op=op@entry=0x55d34b6b2920, 
    econtext=econtext@entry=0x55d34b6a76c0) at execExprInterp.c:4059
        variable = <optimized out>
        slot = 0x55d34b6a7158
        output_tupdesc = 0x55d34b6b3790
        oldcontext = 0x55d34b6a9dc0
        dtuple = <optimized out>
        tuple = <optimized out>
        __func__ = "ExecEvalWholeRowVar"
#8  0x000055d34a0f4e56 in ExecInterpExpr (state=0x55d34b6a77f8, 
    econtext=0x55d34b6a76c0, isnull=<optimized out>) at execExprInterp.c:569
        op = <optimized out>
        resultslot = 0x55d34b6a7758
        innerslot = <optimized out>
        outerslot = <optimized out>
        scanslot = 0x55d34b6a7158
        dispatch_table = {0x55d34a0f5040 <ExecInterpExpr+1424>, 
          0x55d34a0f5008 <ExecInterpExpr+1368>, 
          0x55d34a0f4fd0 <ExecInterpExpr+1312>, 
          0x55d34a0f4fa0 <ExecInterpExpr+1264>, 
          0x55d34a0f4f58 <ExecInterpExpr+1192>, 
          0x55d34a0f4f08 <ExecInterpExpr+1112>, 
          0x55d34a0f4ec0 <ExecInterpExpr+1040>, 
          0x55d34a0f4ea0 <ExecInterpExpr+1008>, 
          0x55d34a0f4e80 <ExecInterpExpr+976>, 
          0x55d34a0f4e60 <ExecInterpExpr+944>, 
          0x55d34a0f4e40 <ExecInterpExpr+912>, 
          0x55d34a0f4df0 <ExecInterpExpr+832>, 
          0x55d34a0f4da0 <ExecInterpExpr+752>, 
          0x55d34a0f4d50 <ExecInterpExpr+672>, 
          0x55d34a0f4d20 <ExecInterpExpr+624>, 
          0x55d34a0f4ce0 <ExecInterpExpr+560>, 
          0x55d34a0f4cc0 <ExecInterpExpr+528>, 
          0x55d34a0f4c90 <ExecInterpExpr+480>, 
          0x55d34a0f4c40 <ExecInterpExpr+400>, 
          0x55d34a0f4c20 <ExecInterpExpr+368>, 
          0x55d34a0f4c00 <ExecInterpExpr+336>, 
          0x55d34a0f4b10 <ExecInterpExpr+96>, 
          0x55d34a0f4b1b <ExecInterpExpr+107>, 
          0x55d34a0f55d0 <ExecInterpExpr+2848>, 
          0x55d34a0f4b40 <ExecInterpExpr+144>, 
          0x55d34a0f4b4b <ExecInterpExpr+155>, 
          0x55d34a0f55f0 <ExecInterpExpr+2880>, 
          0x55d34a0f55b0 <ExecInterpExpr+2816>, 
          0x55d34a0f5580 <ExecInterpExpr+2768>, 
          0x55d34a0f5568 <ExecInterpExpr+2744>, 
          0x55d34a0f5540 <ExecInterpExpr+2704>, 
          0x55d34a0f5518 <ExecInterpExpr+2664>, 
          0x55d34a0f54f0 <ExecInterpExpr+2624>, 
          0x55d34a0f54d0 <ExecInterpExpr+2592>, 
          0x55d34a0f54a0 <ExecInterpExpr+2544>, 
          0x55d34a0f5480 <ExecInterpExpr+2512>, 
          0x55d34a0f5460 <ExecInterpExpr+2480>, 
          0x55d34a0f5430 <ExecInterpExpr+2432>, 
          0x55d34a0f5400 <ExecInterpExpr+2384>, 
          0x55d34a0f53d0 <ExecInterpExpr+2336>, 
          0x55d34a0f53a0 <ExecInterpExpr+2288>, 
          0x55d34a0f5380 <ExecInterpExpr+2256>, 
          0x55d34a0f5360 <ExecInterpExpr+2224>, 
          0x55d34a0f5340 <ExecInterpExpr+2192>, 
          0x55d34a0f5310 <ExecInterpExpr+2144>, 
          0x55d34a0f52c0 <ExecInterpExpr+2064>, 
          0x55d34a0f5210 <ExecInterpExpr+1888>, 
          0x55d34a0f51d0 <ExecInterpExpr+1824>, 
          0x55d34a0f5190 <ExecInterpExpr+1760>, 
          0x55d34a0f5130 <ExecInterpExpr+1664>, 
          0x55d34a0f5110 <ExecInterpExpr+1632>, 
          0x55d34a0f6420 <ExecInterpExpr+6512>, 
          0x55d34a0f50f0 <ExecInterpExpr+1600>, 
          0x55d34a0f50d0 <ExecInterpExpr+1568>, 
          0x55d34a0f50a8 <ExecInterpExpr+1528>, 
          0x55d34a0f5870 <ExecInterpExpr+3520>, 
          0x55d34a0f5820 <ExecInterpExpr+3440>, 
          0x55d34a0f57b0 <ExecInterpExpr+3328>, 
          0x55d34a0f5790 <ExecInterpExpr+3296>, 
          0x55d34a0f5770 <ExecInterpExpr+3264>, 
          0x55d34a0f5750 <ExecInterpExpr+3232>, 
          0x55d34a0f5730 <ExecInterpExpr+3200>, 
          0x55d34a0f5710 <ExecInterpExpr+3168>, 
          0x55d34a0f56f0 <ExecInterpExpr+3136>, 
          0x55d34a0f56d0 <ExecInterpExpr+3104>, 
          0x55d34a0f56b0 <ExecInterpExpr+3072>, 
          0x55d34a0f52e0 <ExecInterpExpr+2096>, 
          0x55d34a0f5658 <ExecInterpExpr+2984>, 
          0x55d34a0f5630 <ExecInterpExpr+2944>, 
          0x55d34a0f5690 <ExecInterpExpr+3040>, 
          0x55d34a0f5670 <ExecInterpExpr+3008>, 
          0x55d34a0f5610 <ExecInterpExpr+2912>, 
          0x55d34a0f5f30 <ExecInterpExpr+5248>, 
          0x55d34a0f5f10 <ExecInterpExpr+5216>, 
          0x55d34a0f5ed0 <ExecInterpExpr+5152>, 
          0x55d34a0f5eb0 <ExecInterpExpr+5120>, 
          0x55d34a0f5f70 <ExecInterpExpr+5312>, 
          0x55d34a0f4b70 <ExecInterpExpr+192>, 
          0x55d34a0f4b82 <ExecInterpExpr+210>, 
          0x55d34a0f5f90 <ExecInterpExpr+5344>, 
          0x55d34a0f5e68 <ExecInterpExpr+5048>, 
          0x55d34a0f5e30 <ExecInterpExpr+4992>, 
          0x55d34a0f5d50 <ExecInterpExpr+4768>, 
          0x55d34a0f5c80 <ExecInterpExpr+4560>, 
          0x55d34a0f5bb8 <ExecInterpExpr+4360>, 
          0x55d34a0f5aa0 <ExecInterpExpr+4080>, 
          0x55d34a0f5990 <ExecInterpExpr+3808>, 
          0x55d34a0f5890 <ExecInterpExpr+3552>, 
          0x55d34a0f5088 <ExecInterpExpr+1496>, 
          0x55d34a0f5068 <ExecInterpExpr+1464>, 
          0x55d34a0f6430 <ExecInterpExpr+6528>}
#9  0x000055d34a105b15 in ExecEvalExprSwitchContext (isNull=0x7ffe1680b4a7, 
    econtext=0x55d34b6a76c0, state=0x55d34b6a77f8)
    at ../../../src/include/executor/executor.h:316
        retDatum = <optimized out>
        oldContext = 0x55d34b6a5da0
        retDatum = <optimized out>
        oldContext = <optimized out>
#10 ExecProject (projInfo=0x55d34b6a77f0)
    at ../../../src/include/executor/executor.h:350
        econtext = 0x55d34b6a76c0
        state = 0x55d34b6a77f8
        slot = 0x55d34b6a7758
        isnull = false
#11 ExecScan (node=<optimized out>, accessMtd=0x55d34a12f4b0 <SeqNext>, 
    recheckMtd=0x55d34a12f540 <SeqRecheck>) at execScan.c:238
        slot = <optimized out>
        econtext = <optimized out>
        qual = 0x0
        projInfo = 0x55d34b6a77f0
#12 0x000055d34a114a37 in ExecProcNode (node=0x55d34b6a6cf0)
    at ../../../src/include/executor/executor.h:248
No locals.
#13 ExecAppend (pstate=0x55d34b6a6380) at nodeAppend.c:267
        subnode = 0x55d34b6a6cf0
        result = <optimized out>
        node = 0x55d34b6a6380
#14 0x000055d34a1304d8 in ExecProcNode (node=0x55d34b6a6380)
    at ../../../src/include/executor/executor.h:248
No locals.
#15 ExecSort (pstate=0x55d34b6a6168) at nodeSort.c:108
        plannode = <optimized out>
        outerNode = 0x55d34b6a6380
        tupDesc = <optimized out>
        node = 0x55d34b6a6168
        estate = 0x55d34b6a5ec0
        dir = ForwardScanDirection
        tuplesortstate = 0x55d34b6b4a10
        slot = <optimized out>
#16 0x000055d34a0fa903 in ExecProcNode (node=0x55d34b6a6168)
    at ../../../src/include/executor/executor.h:248
No locals.
#17 ExecutePlan (execute_once=<optimized out>, dest=0x55d34b618a40, 
    direction=<optimized out>, numberTuples=0, sendTuples=<optimized out>, 
    operation=CMD_SELECT, use_parallel_mode=<optimized out>, 
    planstate=0x55d34b6a6168, estate=0x55d34b6a5ec0) at execMain.c:1632
        slot = <optimized out>
        current_tuple_count = 0
        slot = <optimized out>
        current_tuple_count = <optimized out>
#18 standard_ExecutorRun (queryDesc=0x55d34b69b7b8, 
    direction=<optimized out>, count=0, execute_once=<optimized out>)
    at execMain.c:350
        estate = 0x55d34b6a5ec0
        operation = CMD_SELECT
        dest = 0x55d34b618a40
        sendTuples = <optimized out>
        oldcontext = 0x55d34b616bb0
        __func__ = "standard_ExecutorRun"
#19 0x000055d34a0ffaa4 in ParallelQueryMain (seg=seg@entry=0x55d34b5684b0, 
    toc=toc@entry=0x7f84e330e000) at execParallel.c:1448
        fpes = 0x7f84e3331640
        buffer_usage = <optimized out>
        wal_usage = <optimized out>
        receiver = 0x55d34b618a40
        queryDesc = 0x55d34b69b7b8
        instrumentation = 0x0
        jit_instrumentation = 0x0
        instrument_options = <optimized out>
        area_space = <optimized out>
        area = <optimized out>
        pwcxt = {seg = 0x55d34b5684b0, toc = 0x7f84e330e000}
#20 0x000055d349fadfe8 in ParallelWorkerMain (main_arg=<optimized out>)
    at parallel.c:1470
        seg = 0x55d34b5684b0
        toc = 0x7f84e330e000
        fps = 0x7f84e333ae40
        error_queue_space = <optimized out>
        mq = <optimized out>
        mqh = <optimized out>
        libraryspace = <optimized out>
        entrypointstate = <optimized out>
        library_name = <optimized out>
        function_name = <optimized out>
        entrypt = 0x55d34a0ff890 <ParallelQueryMain>
        gucspace = <optimized out>
        combocidspace = <optimized out>
        tsnapspace = <optimized out>
        asnapspace = <optimized out>
        tstatespace = <optimized out>
        pendingsyncsspace = <optimized out>
        reindexspace = <optimized out>
        relmapperspace = <optimized out>
        enumblacklistspace = <optimized out>
        msgbuf = {data = 0x0, len = 8, maxlen = 1024, cursor = 75}
        session_dsm_handle_space = <optimized out>
        __func__ = "ParallelWorkerMain"
#21 0x000055d34a1f44f5 in StartBackgroundWorker () at bgworker.c:879
        local_sigjmp_buf = {{__jmpbuf = {94365990784864, 8663472795338053817, 
              0, 94365974891408, 94365990757088, 94365990757184, 
              3197675817297680569, 8663469969791948985}, 
            __mask_was_saved = 1, __saved_mask = {__val = {
                18446744066192964103, 8192, 0, 94365990757184, 
                94365972090896, 94365974891408, 94365990440960, 
                94365990440960, 94365990449152, 94365974891408, 
                94365972118889, 94365990441184, 94365972090664, 
                94365974891408, 94365990784864, 0}}}}
        worker = 0x55d34b567350
        entrypt = <optimized out>
        __func__ = "StartBackgroundWorker"
#22 0x000055d34a202373 in do_start_bgworker (rw=<optimized out>)
    at postmaster.c:5870
        worker_pid = <optimized out>
        worker_pid = <optimized out>
        __func__ = "do_start_bgworker"
        __errno_location = <optimized out>
        __errno_location = <optimized out>
#23 maybe_start_bgworkers () at postmaster.c:6095
        rw = <optimized out>
        num_launched = 0
        now = 0
        iter = {cur = 0x55d34b5c0f60, next = 0x55d34b5c0a30, 
          prev = 0x55d34a6a9800 <BackgroundWorkerList>}
#24 0x000055d34a202d52 in sigusr1_handler (
    postgres_signal_arg=<optimized out>) at postmaster.c:5255
        save_errno = 4
        __func__ = "sigusr1_handler"
#25 <signal handler called>
No locals.
#26 0x00007f84ed13e0da in __GI___select (nfds=nfds@entry=8, 
    readfds=readfds@entry=0x7ffe1680bea0, writefds=writefds@entry=0x0, 
    exceptfds=exceptfds@entry=0x0, timeout=timeout@entry=0x7ffe1680be00)
    at ../sysdeps/unix/sysv/linux/select.c:41
        resultvar = 18446744073709551612
        sc_ret = <optimized out>
#27 0x000055d34a20358e in ServerLoop () at postmaster.c:1703
        timeout = {tv_sec = 59, tv_usec = 999987}
        rmask = {fds_bits = {192, 0 <repeats 15 times>}}
        selres = <optimized out>
        now = <optimized out>
        readmask = {fds_bits = {192, 0 <repeats 15 times>}}
        nSockets = 8
        last_lockfile_recheck_time = 1621262829
        last_touch_time = 1621262829
        __func__ = "ServerLoop"
#28 0x000055d34a2052d4 in PostmasterMain (argc=argc@entry=8, 
    argv=argv@entry=0x55d34b566340) at postmaster.c:1412
        opt = <optimized out>
        status = <optimized out>
        userDoption = <optimized out>
        listen_addr_saved = true
        i = <optimized out>
        output_config_variable = <optimized out>
        __func__ = "PostmasterMain"
#29 0x000055d349f00ed0 in main (argc=8, argv=0x55d34b566340) at main.c:210
        do_check_root = <optimized out>
(gdb) quit
           PID: 13271 (postgres)
           UID: 1001 (runner)
           GID: 121 (docker)
        Signal: 6 (ABRT)
     Timestamp: Mon 2021-05-17 14:47:16 UTC (27s ago)
  Command Line: postgres: parallel worker for PID 13220
    Executable: /home/runner/postgresql/bin/postgres
 Control Group: /system.slice/runner-provisioner.service
          Unit: runner-provisioner.service
         Slice: system.slice
       Boot ID: b9786c5b2aea4b258e766f421bc542be
    Machine ID: 15bd0dad58cd48aa84fde0dc2b1a9cb8
      Hostname: fv-az216-414
       Storage: /var/lib/systemd/coredump/core.postgres.1001.b9786c5b2aea4b258e766f421bc542be.13271.1621262836000000000000.lz4
       Message: Process 13271 (postgres) of user 1001 dumped core.
                
                Stack trace of thread 13271:
                #0  0x00007f84ed06c18b __GI_raise (libc.so.6 + 0x4618b)
                #1  0x00007f84ed04b859 __GI_abort (libc.so.6 + 0x25859)
                #2  0x000055d34a3c516b n/a (/home/runner/postgresql/bin/postgres + 0x58416b)


warning: Can't open file /dev/shm/PostgreSQL.400693867 during file-backed mapping note processing

warning: Can't open file /dev/shm/PostgreSQL.1028535483 during file-backed mapping note processing

warning: Can't open file /dev/shm/PostgreSQL.1661398776 during file-backed mapping note processing

warning: Can't open file /dev/shm/PostgreSQL.202771827 during file-backed mapping note processing

warning: Can't open file /dev/zero (deleted) during file-backed mapping note processing

warning: Can't open file /SYSV0002b5d3 (deleted) during file-backed mapping note processing
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
Error: Process completed with exit code 1.
```

**Comment by RafiaSabih** [comment]
Closing since never found again.
