### ISSUE TITLE
Assertion failure in inheritance_planner

### ISSUE THREAD

**Issue by svenklemm** [timescale/timescaledb#3242]
Found by sqlsmith

```
#0  0x00007fcc45ee9ef5 in raise () from /usr/lib/libc.so.6
#1  0x00007fcc45ed3862 in abort () from /usr/lib/libc.so.6
#2  0x00005572321d4498 in ExceptionalCondition (conditionName=0x5572323666b0 "list_length(final_rtable) == list_length(subroot->parse->rtable)", errorType=0x5572323663d6 "FailedAssertion", fileName=0x5572323664ab "planner.c",
    lineNumber=1643) at assert.c:67
#3  0x0000557231f08f5b in inheritance_planner (root=0x557233018f68) at planner.c:1643
#4  0x0000557231f07f18 in subquery_planner (glob=0x55723319d2f8, parse=0x55723319d410, parent_root=0x0, hasRecursion=false, tuple_fraction=0) at planner.c:1013
#5  0x0000557231f06807 in standard_planner (parse=0x55723319d410,
    query_string=0x557233019380 "delete from public.metrics\nwhere \nEXISTS (\n  select  \n      public.metrics.device as c0, \n      case when EXISTS (\n          select  \n              sample_0.time as c0, \n              ref_0.device as c1, \n              public.metrics.device as c2\n            from \n              public.metrics as sample_0 tablesample system (4) \n            where cast(null as circle) ~ cast(null as circle)\n            limit 104) then public.metrics.value else public.metrics.value end\n         as c1, \n      ref_0.time as c2, \n      case when false then public.metrics.device else public.metrics.device end\n         as c3, \n      ref_0.value as c4\n    from \n      public.metrics as ref_0\n    where EXISTS (\n      select  \n          ref_0.time as c0\n        from \n          public.metrics as ref_1\n        where public.metrics.value >= ref_1.value\n        limit 198)\n    limit 71)\nreturning \n  public.metrics.value as c0, \n  public.metrics.device as c1, \n  pg_catalog.pg_stat_get_bgwriter_maxwritten_clean() as c2, \n  case when public.metrics.value < public.metrics.value then public.metrics.time else public.metrics.time end\n     as c3", cursorOptions=256, boundParams=0x0) at planner.c:405
#6  0x00007fcc3cae8614 in timescaledb_planner (parse=0x55723319d410,
    query_string=0x557233019380 "delete from public.metrics\nwhere \nEXISTS (\n  select  \n      public.metrics.device as c0, \n      case when EXISTS (\n          select  \n              sample_0.time as c0, \n              ref_0.device as c1, \n              public.metrics.device as c2\n            from \n              public.metrics as sample_0 tablesample system (4) \n            where cast(null as circle) ~ cast(null as circle)\n            limit 104) then public.metrics.value else public.metrics.value end\n         as c1, \n      ref_0.time as c2, \n      case when false then public.metrics.device else public.metrics.device end\n         as c3, \n      ref_0.value as c4\n    from \n      public.metrics as ref_0\n    where EXISTS (\n      select  \n          ref_0.time as c0\n        from \n          public.metrics as ref_1\n        where public.metrics.value >= ref_1.value\n        limit 198)\n    limit 71)\nreturning \n  public.metrics.value as c0, \n  public.metrics.device as c1, \n  pg_catalog.pg_stat_get_bgwriter_maxwritten_clean() as c2, \n  case when public.metrics.value < public.metrics.value then public.metrics.time else public.metrics.time end\n     as c3", cursor_opts=256, bound_params=0x0) at /home/sven/projects/timescaledb/src/planner.c:319
#7  0x0000557231f06527 in planner (parse=0x55723319d410,
    query_string=0x557233019380 "delete from public.metrics\nwhere \nEXISTS (\n  select  \n      public.metrics.device as c0, \n      case when EXISTS (\n          select  \n              sample_0.time as c0, \n              ref_0.device as c1, \n              public.metrics.device as c2\n            from \n              public.metrics as sample_0 tablesample system (4) \n            where cast(null as circle) ~ cast(null as circle)\n            limit 104) then public.metrics.value else public.metrics.value end\n         as c1, \n      ref_0.time as c2, \n      case when false then public.metrics.device else public.metrics.device end\n         as c3, \n      ref_0.value as c4\n    from \n      public.metrics as ref_0\n    where EXISTS (\n      select  \n          ref_0.time as c0\n        from \n          public.metrics as ref_1\n        where public.metrics.value >= ref_1.value\n        limit 198)\n    limit 71)\nreturning \n  public.metrics.value as c0, \n  public.metrics.device as c1, \n  pg_catalog.pg_stat_get_bgwriter_maxwritten_clean() as c2, \n  case when public.metrics.value < public.metrics.value then public.metrics.time else public.metrics.time end\n     as c3", cursorOptions=256, boundParams=0x0) at planner.c:273
#8  0x0000557232036ca3 in pg_plan_query (querytree=0x55723319d410,
    query_string=0x557233019380 "delete from public.metrics\nwhere \nEXISTS (\n  select  \n      public.metrics.device as c0, \n      case when EXISTS (\n          select  \n              sample_0.time as c0, \n              ref_0.device as c1, \n              public.metrics.device as c2\n            from \n              public.metrics as sample_0 tablesample system (4) \n            where cast(null as circle) ~ cast(null as circle)\n            limit 104) then public.metrics.value else public.metrics.value end\n         as c1, \n      ref_0.time as c2, \n      case when false then public.metrics.device else public.metrics.device end\n         as c3, \n      ref_0.value as c4\n    from \n      public.metrics as ref_0\n    where EXISTS (\n      select  \n          ref_0.time as c0\n        from \n          public.metrics as ref_1\n        where public.metrics.value >= ref_1.value\n        limit 198)\n    limit 71)\nreturning \n  public.metrics.value as c0, \n  public.metrics.device as c1, \n  pg_catalog.pg_stat_get_bgwriter_maxwritten_clean() as c2, \n  case when public.metrics.value < public.metrics.value then public.metrics.time else public.metrics.time end\n     as c3", cursorOptions=256, boundParams=0x0) at postgres.c:875
#9  0x0000557232036ddf in pg_plan_queries (querytrees=0x5572337a61f0,
    query_string=0x557233019380 "delete from public.metrics\nwhere \nEXISTS (\n  select  \n      public.metrics.device as c0, \n      case when EXISTS (\n          select  \n              sample_0.time as c0, \n              ref_0.device as c1, \n              public.metrics.device as c2\n            from \n              public.metrics as sample_0 tablesample system (4) \n            where cast(null as circle) ~ cast(null as circle)\n            limit 104) then public.metrics.value else public.metrics.value end\n         as c1, \n      ref_0.time as c2, \n      case when false then public.metrics.device else public.metrics.device end\n         as c3, \n      ref_0.value as c4\n    from \n      public.metrics as ref_0\n    where EXISTS (\n      select  \n          ref_0.time as c0\n        from \n          public.metrics as ref_1\n        where public.metrics.value >= ref_1.value\n        limit 198)\n    limit 71)\nreturning \n  public.metrics.value as c0, \n  public.metrics.device as c1, \n  pg_catalog.pg_stat_get_bgwriter_maxwritten_clean() as c2, \n  case when public.metrics.value < public.metrics.value then public.metrics.time else public.metrics.time end\n     as c3", cursorOptions=256, boundParams=0x0) at postgres.c:966
#10 0x00005572320371ad in exec_simple_query (
    query_string=0x557233019380 "delete from public.metrics\nwhere \nEXISTS (\n  select  \n      public.metrics.device as c0, \n      case when EXISTS (\n          select  \n              sample_0.time as c0, \n              ref_0.device as c1, \n              public.metrics.device as c2\n            from \n              public.metrics as sample_0 tablesample system (4) \n            where cast(null as circle) ~ cast(null as circle)\n            limit 104) then public.metrics.value else public.metrics.value end\n         as c1, \n      ref_0.time as c2, \n      case when false then public.metrics.device else public.metrics.device end\n         as c3, \n      ref_0.value as c4\n    from \n      public.metrics as ref_0\n    where EXISTS (\n      select  \n          ref_0.time as c0\n        from \n          public.metrics as ref_1\n        where public.metrics.value >= ref_1.value\n        limit 198)\n    limit 71)\nreturning \n  public.metrics.value as c0, \n  public.metrics.device as c1, \n  pg_catalog.pg_stat_get_bgwriter_maxwritten_clean() as c2, \n  case when public.metrics.value < public.metrics.value then public.metrics.time else public.metrics.time end\n     as c3") at postgres.c:1158
```

**Comment by RafiaSabih** [comment]
Closing since we never found this again.
