### ISSUE TITLE
Crash with CREATE TABLE AS

### ISSUE THREAD

**Issue by mfundul** [timescale/timescaledb#3442]
**Relevant system information:**
 - OS: Ubuntu 20.04
 - PostgreSQL version 12.6
 - TimescaleDB version (output of `\dx` in `psql`): 2.4.0-dev
 - Installation method: "source"

**Describe the bug**

**To Reproduce**
```
CREATE TABLE drop_chunks_table(time BIGINT, data INTEGER);
CREATE TABLE drop_chunks_table_id AS
  SELECT hypertable_id
      FROM create_hypertable('drop_chunks_table', 'time', chunk_time_interval => 10);
```

**Expected behavior**
Not crash.

**Actual behavior**
When compiled with ASAN the stack trace is:
```
=================================================================
==postgres==21945==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000010 (pc 0x564da9f1d969 bp 0x7ffe7fe712c0 sp 0x7ffe7fe712c0 T0)
==postgres==21945==The signal is caused by a WRITE memory access.
==postgres==21945==Hint: address points to the zero page.
    #0 0x564da9f1d968 in EventTriggerAlterTableRelid /home/mfundul/Development/timescale/postgresql-12.6/src/backend/commands/event_trigger.c:1749
    #1 0x564da9fd34ee in AlterTableInternal /home/mfundul/Development/timescale/postgresql-12.6/src/backend/commands/tablecmds.c:3656
    #2 0x7efe839b414c in dimension_add_not_null_on_column /home/mfundul/Development/timescale/timescaledb/src/dimension.c:1071
    #3 0x7efe839b8849 in ts_dimension_add_from_info /home/mfundul/Development/timescale/timescaledb/src/dimension.c:1405
    #4 0x7efe839cf5bf in ts_hypertable_create_from_info /home/mfundul/Development/timescale/timescaledb/src/hypertable.c:2182
    #5 0x7efe839d07b8 in ts_hypertable_create_internal /home/mfundul/Development/timescale/timescaledb/src/hypertable.c:1938
    #6 0x7efe839d08fe in ts_hypertable_create /home/mfundul/Development/timescale/timescaledb/src/hypertable.c:1964
    #7 0x564daa05ba4d in ExecMakeTableFunctionResult /home/mfundul/Development/timescale/postgresql-12.6/src/backend/executor/execSRF.c:234
    #8 0x564daa0897d9 in FunctionNext /home/mfundul/Development/timescale/postgresql-12.6/src/backend/executor/nodeFunctionscan.c:95
    #9 0x564daa05930e in ExecScanFetch /home/mfundul/Development/timescale/postgresql-12.6/src/backend/executor/execScan.c:133
    #10 0x564daa059509 in ExecScan /home/mfundul/Development/timescale/postgresql-12.6/src/backend/executor/execScan.c:200
    #11 0x564daa089480 in ExecFunctionScan /home/mfundul/Development/timescale/postgresql-12.6/src/backend/executor/nodeFunctionscan.c:270
    #12 0x564daa054ec5 in ExecProcNodeFirst /home/mfundul/Development/timescale/postgresql-12.6/src/backend/executor/execProcnode.c:445
    #13 0x564daa03ee98 in ExecProcNode ../../../src/include/executor/executor.h:242
    #14 0x564daa03efa3 in ExecutePlan /home/mfundul/Development/timescale/postgresql-12.6/src/backend/executor/execMain.c:1632
    #15 0x564daa04124c in standard_ExecutorRun /home/mfundul/Development/timescale/postgresql-12.6/src/backend/executor/execMain.c:350
    #16 0x564daa041390 in ExecutorRun /home/mfundul/Development/timescale/postgresql-12.6/src/backend/executor/execMain.c:294
    #17 0x564da9f0bc80 in ExecCreateTableAs /home/mfundul/Development/timescale/postgresql-12.6/src/backend/commands/createas.c:354
    #18 0x564daa44c799 in ProcessUtilitySlow /home/mfundul/Development/timescale/postgresql-12.6/src/backend/tcop/utility.c:1541
    #19 0x564daa44a44e in standard_ProcessUtility /home/mfundul/Development/timescale/postgresql-12.6/src/backend/tcop/utility.c:927
    #20 0x7efe8d05e6f0 in loader_process_utility_hook /home/mfundul/Development/timescale/timescaledb/src/loader/loader.c:510
    #21 0x7efe839fa420 in prev_ProcessUtility /home/mfundul/Development/timescale/timescaledb/src/process_utility.c:89
    #22 0x7efe839fa990 in timescaledb_ddl_command_start /home/mfundul/Development/timescale/timescaledb/src/process_utility.c:4030
    #23 0x564daa44a4fc in ProcessUtility /home/mfundul/Development/timescale/postgresql-12.6/src/backend/tcop/utility.c:356
    #24 0x564daa4429c6 in PortalRunUtility /home/mfundul/Development/timescale/postgresql-12.6/src/backend/tcop/pquery.c:1175
    #25 0x564daa444254 in PortalRunMulti /home/mfundul/Development/timescale/postgresql-12.6/src/backend/tcop/pquery.c:1321
    #26 0x564daa446552 in PortalRun /home/mfundul/Development/timescale/postgresql-12.6/src/backend/tcop/pquery.c:796
    #27 0x564daa43e7b3 in exec_simple_query /home/mfundul/Development/timescale/postgresql-12.6/src/backend/tcop/postgres.c:1215
    #28 0x564daa442152 in PostgresMain /home/mfundul/Development/timescale/postgresql-12.6/src/backend/tcop/postgres.c:4261
    #29 0x564daa2ea8ef in BackendRun /home/mfundul/Development/timescale/postgresql-12.6/src/backend/postmaster/postmaster.c:4484
    #30 0x564daa2ee219 in BackendStartup /home/mfundul/Development/timescale/postgresql-12.6/src/backend/postmaster/postmaster.c:4167
    #31 0x564daa2eeaf6 in ServerLoop /home/mfundul/Development/timescale/postgresql-12.6/src/backend/postmaster/postmaster.c:1725
    #32 0x564daa2f0abb in PostmasterMain /home/mfundul/Development/timescale/postgresql-12.6/src/backend/postmaster/postmaster.c:1398
    #33 0x564daa129939 in main /home/mfundul/Development/timescale/postgresql-12.6/src/backend/main/main.c:228
    #34 0x7efe8fd920b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
    #35 0x564da9a6941d in _start (/usr/local/pgsql/postgresql-12.6/bin/postgres+0x36541d)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/mfundul/Development/timescale/postgresql-12.6/src/backend/commands/event_trigger.c:1749 in EventTriggerAlterTableRelid
==postgres==21945==ABORTING
```

**Comment by nikkhils** [comment]
I am working on a fix for this.

**Comment by nikkhils** [comment]
Am working on a fix for this.
