### ISSUE TITLE
Assertion failure in continuous aggregate ddl test

### ISSUE THREAD

**Issue by svenklemm** [timescale/timescaledb#3478]
Link to coredump: https://github.com/timescale/timescaledb/runs/3315697509?check_suite_focus=true

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
(gdb) #0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {0, 94627782306224, 679936, 94627752885655, 
            94627782313680, 16612149935684452353, 157, 0, 94627783108000, 
            94627755371769, 139700154020160, 1777, 94627782306224, 
            94627782620480, 94627782622464, 88}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007f0e8371c859 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x56103deecc68, 
            sa_sigaction = 0x56103deecc68}, sa_mask = {__val = {
              94627758689228, 130, 94627758689228, 21, 21, 94627783616832, 
              94627757011758, 94627782048680, 94627782048624, 21, 
              94627757016068, 94627782048680, 94627783617680, 94627783620680, 
              139700313404864, 139700313408672}}, sa_flags = -2089302714, 
          sa_restorer = 0x56103f6db7b0}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x000056103dd4bdfa in ExceptionalCondition (
    conditionName=conditionName@entry=0x56103deecc68 "!(((list) == ((List *) ((void *)0)) || ((((const Node*)((list)))->type) == T_List)))", 
    errorType=errorType@entry=0x56103dda101d "FailedAssertion", 
    fileName=fileName@entry=0x56103df14bcc "list.c", 
    lineNumber=lineNumber@entry=130) at assert.c:54
No locals.
#3  0x000056103daff132 in lappend (list=0x56103f69f128, datum=0x56103f6dac90)
    at list.c:130
No locals.
#4  lappend (list=0x56103f69f128, datum=datum@entry=0x56103f6dac90)
    at list.c:128
No locals.
#5  0x000056103da32420 in EventTriggerCollectSimpleCommand (address=..., 
    secondaryObject=..., parsetree=parsetree@entry=0x56103f55c490)
    at event_trigger.c:1694
        oldcxt = 0x56103f74cc20
        command = 0x56103f6dac90
#6  0x000056103dc2ae15 in ProcessUtilitySlow (
    pstate=pstate@entry=0x56103f74ce50, pstmt=pstmt@entry=0x56103f6c2bb0, 
    queryString=queryString@entry=0x56103f55b098 "CREATE TABLE drop_chunks_table_id AS SELECT hypertable_id\n      FROM create_hypertable('public.drop_chunk_test4', 'time', chunk_time_interval => 1);", 
    context=context@entry=PROCESS_UTILITY_TOPLEVEL, params=params@entry=0x0, 
    queryEnv=queryEnv@entry=0x0, completionTag=0x7ffc0331c3f0 "SELECT 1", 
    dest=0x56103f6c2ca8) at utility.c:1706
        save_exception_stack = 0x7ffc0331c2b0
        save_context_stack = 0x0
        local_sigjmp_buf = {{__jmpbuf = {94627784085072, 
              -3459988120805284725, 0, 94627783519152, 94627782045848, 
              140720362079216, -7195661582427986805, -3459993715947576181}, 
            __mask_was_saved = 0, __saved_mask = {__val = {94627756720477, 
                139700153822448, 94627756868088, 94627753317936, 0, 
                140720362077888, 139640024280504, 139700153822749, 
                139700153822376, 2249, 94626719465476, 139700153822376, 
                16612149938518046976, 139700153822448, 140720362077888, 
                94627783514864}}}}
        parsetree = 0x56103f55c490
        isTopLevel = true
        isCompleteQuery = true
        needCleanup = true
        commandCollected = false
        address = {classId = 1259, objectId = 22668, objectSubId = 0}
        secondaryObject = {classId = 0, objectId = 0, objectSubId = 0}
        __func__ = "ProcessUtilitySlow"
#7  0x000056103dc2a0a1 in standard_ProcessUtility (pstmt=0x56103f6c2bb0, 
    queryString=0x56103f55b098 "CREATE TABLE drop_chunks_table_id AS SELECT hypertable_id\n      FROM create_hypertable('public.drop_chunk_test4', 'time', chunk_time_interval => 1);", context=PROCESS_UTILITY_TOPLEVEL, params=0x0, 
    queryEnv=0x0, dest=0x56103f6c2ca8, 
    completionTag=0x7ffc0331c3f0 "SELECT 1") at utility.c:927
        parsetree = 0x56103f55c490
        isTopLevel = <optimized out>
        isAtomicContext = false
        pstate = 0x56103f74ce50
        __func__ = "standard_ProcessUtility"
#8  0x00007f0e832547b0 in loader_process_utility_hook (pstmt=0x56103f6c2bb0, 
    query_string=0x56103f55b098 "CREATE TABLE drop_chunks_table_id AS SELECT hypertable_id\n      FROM create_hypertable('public.drop_chunk_test4', 'time', chunk_time_interval => 1);", context=PROCESS_UTILITY_TOPLEVEL, params=0x0, 
    queryEnv=0x0, dest=0x56103f6c2ca8, 
    completion_tag=0x7ffc0331c3f0 "SELECT 1")
    at /home/runner/work/timescaledb/timescaledb/src/loader/loader.c:502
        is_distributed_database = false
        dist_uuid = 0x0
        process_utility = 0x56103dc29f60 <standard_ProcessUtility>
        __func__ = "loader_process_utility_hook"
#9  0x00007f0e7a1c593c in prev_ProcessUtility (args=0x7ffc0331c110)
    at /home/runner/work/timescaledb/timescaledb/src/process_utility.c:89
No locals.
#10 0x00007f0e7a1d4499 in timescaledb_ddl_command_start (
    pstmt=0x56103f6c2bb0, 
    query_string=0x56103f55b098 "CREATE TABLE drop_chunks_table_id AS SELECT hypertable_id\n      FROM create_hypertable('public.drop_chunk_test4', 'time', chunk_time_interval => 1);", context=PROCESS_UTILITY_TOPLEVEL, params=0x0, 
    queryEnv=0x0, dest=0x56103f6c2ca8, 
    completion_tag=0x7ffc0331c3f0 "SELECT 1")
    at /home/runner/work/timescaledb/timescaledb/src/process_utility.c:4030
        args = {hcache = 0x0, pstmt = 0x56103f6c2bb0, queryEnv = 0x0, 
          parse_state = 0x56103f74cd38, parsetree = 0x56103f55c490, 
          query_string = 0x56103f55b098 "CREATE TABLE drop_chunks_table_id AS SELECT hypertable_id\n      FROM create_hypertable('public.drop_chunk_test4', 'time', chunk_time_interval => 1);", context = PROCESS_UTILITY_TOPLEVEL, 
          params = 0x0, dest = 0x56103f6c2ca8, hypertable_list = 0x0, 
          completion_tag = 0x7ffc0331c3f0 "SELECT 1"}
        altering_timescaledb = false
        result = DDL_CONTINUE
#11 0x000056103dc26fe6 in PortalRunUtility (portal=0x56103f5c8a88, 
    pstmt=0x56103f6c2bb0, isTopLevel=<optimized out>, 
    setHoldSnapshot=<optimized out>, dest=0x56103f6c2ca8, 
    completionTag=0x7ffc0331c3f0 "SELECT 1") at pquery.c:1175
        utilityStmt = <optimized out>
        snapshot = 0x56103f5e7690
#12 0x000056103dc27b91 in PortalRunMulti (portal=portal@entry=0x56103f5c8a88, 
    isTopLevel=isTopLevel@entry=true, 
    setHoldSnapshot=setHoldSnapshot@entry=false, 
    dest=dest@entry=0x56103f6c2ca8, altdest=altdest@entry=0x56103f6c2ca8, 
    completionTag=completionTag@entry=0x7ffc0331c3f0 "SELECT 1")
    at pquery.c:1328
        pstmt = 0x56103f6c2bb0
        active_snapshot_set = false
        stmtlist_item = 0x56103f6c2c48
#13 0x000056103dc28949 in PortalRun (portal=portal@entry=0x56103f5c8a88, 
    count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true, 
    run_once=run_once@entry=true, dest=dest@entry=0x56103f6c2ca8, 
    altdest=altdest@entry=0x56103f6c2ca8, 
    completionTag=0x7ffc0331c3f0 "SELECT 1") at pquery.c:796
        save_exception_stack = 0x7ffc0331c5e0
        save_context_stack = 0x0
        local_sigjmp_buf = {{__jmpbuf = {0, -3459988120752855925, 
              94627782494856, 94627782045848, 2, 94627782494856, 
              -7195661580238560117, -3459993714855615349}, 
            __mask_was_saved = 0, __saved_mask = {__val = {5334492781, 
                94627782506440, 94627758990957, 94627782503216, 0, 0, 
                140720362079095, 94627782503064, 1, 94627758990957, 
                94627782494856, 1, 94627782045568, 94627782051072, 112, 
                94627782045848}}}}
        result = <optimized out>
        nprocessed = <optimized out>
        saveTopTransactionResourceOwner = 0x56103f594d90
        saveTopTransactionContext = 0x56103f5e7540
        saveActivePortal = 0x0
        saveResourceOwner = 0x56103f594d90
        savePortalContext = 0x0
        saveMemoryContext = 0x56103f5e7540
        __func__ = "PortalRun"
#14 0x000056103dc24598 in exec_simple_query (
    query_string=0x56103f55b098 "CREATE TABLE drop_chunks_table_id AS SELECT hypertable_id\n      FROM create_hypertable('public.drop_chunk_test4', 'time', chunk_time_interval => 1);") at postgres.c:1215
        parsetree = 0x56103f55c4c8
        portal = 0x56103f5c8a88
        snapshot_set = <optimized out>
        commandTag = <optimized out>
        completionTag = "SELECT 1\000\000\000\000\002\000\000\000\000\000\000\000\002\000\000\000\n\000\000\000\020V\000\000\000\000\000\000\000\000\000\000\210\037\360=\020V\000\000Q\000\000\000\000\000\000\000\230\260U?\020V\000"
        querytree_list = <optimized out>
        plantree_list = <optimized out>
        receiver = <optimized out>
        format = 0
        dest = DestRemote
        oldcontext = 0x56103f5e7540
        parsetree_list = 0x56103f55c528
        parsetree_item = 0x56103f55c500
        save_log_statement_stats = false
        was_logged = false
        use_implicit_block = false
        msec_str = "SELECT 1\000\000\000\000\002\000\000\000\000\000\000\000\002\000\000\000\n\000\000\000\020V\000"
        __func__ = "exec_simple_query"
#15 0x000056103dc25e21 in PostgresMain (argc=<optimized out>, 
    argv=argv@entry=0x56103f58e868, dbname=<optimized out>, 
    username=<optimized out>) at postgres.c:4236
        query_string = 0x56103f55b098 "CREATE TABLE drop_chunks_table_id AS SELECT hypertable_id\n      FROM create_hypertable('public.drop_chunk_test4', 'time', chunk_time_interval => 1);"
        firstchar = <optimized out>
        input_message = {
          data = 0x56103f55b098 "CREATE TABLE drop_chunks_table_id AS SELECT hypertable_id\n      FROM create_hypertable('public.drop_chunk_test4', 'time', chunk_time_interval => 1);", len = 149, maxlen = 1024, cursor = 149}
        local_sigjmp_buf = {{__jmpbuf = {94627758612360, 
              -7195661580033039221, 644700629, 94627782255960, 
              94627760148576, 94627760149600, -7195661580062399349, 
              -3459993708454058869}, __mask_was_saved = 1, __saved_mask = {
              __val = {0, 94627758607693, 0, 140720362081584, 
                140720362080512, 94627760149600, 94627757131887, 
                140720362085265, 140720362085218, 140720362090449, 0, 0, 0, 
                94627782045568, 16612149938518046976, 94627760138880}}}}
        send_ready_for_query = false
        disable_idle_in_transaction_timeout = false
        __func__ = "PostgresMain"
#16 0x000056103db9c6f2 in BackendRun (port=0x56103f583e40, 
    port=0x56103f583e40) at postmaster.c:4431
        av = 0x56103f58e868
        maxac = <optimized out>
        ac = 1
        i = 1
        av = <optimized out>
        maxac = <optimized out>
        ac = <optimized out>
        i = <optimized out>
        __func__ = "BackendRun"
        __errno_location = <optimized out>
        __errno_location = <optimized out>
        __errno_location = <optimized out>
#17 BackendStartup (port=0x56103f583e40) at postmaster.c:4122
        bn = <optimized out>
        pid = <optimized out>
        bn = <optimized out>
        pid = <optimized out>
        __func__ = "BackendStartup"
        __errno_location = <optimized out>
        __errno_location = <optimized out>
        save_errno = <optimized out>
        __errno_location = <optimized out>
        __errno_location = <optimized out>
#18 ServerLoop () at postmaster.c:1704
        port = 0x56103f583e40
        i = <optimized out>
        rmask = {fds_bits = {16, 0 <repeats 15 times>}}
        selres = <optimized out>
        now = <optimized out>
        readmask = {fds_bits = {48, 0 <repeats 15 times>}}
        nSockets = 6
        last_lockfile_recheck_time = 1628799198
        last_touch_time = 1628799198
        __func__ = "ServerLoop"
#19 0x000056103db9d562 in PostmasterMain (argc=argc@entry=8, 
    argv=argv@entry=0x56103f5542d0) at postmaster.c:1377
        opt = <optimized out>
        status = <optimized out>
        userDoption = <optimized out>
        listen_addr_saved = <optimized out>
        i = <optimized out>
        output_config_variable = <optimized out>
        __func__ = "PostmasterMain"
#20 0x000056103d8c6f6d in main (argc=8, argv=0x56103f5542d0) at main.c:228
        do_check_root = <optimized out>
```

**Comment by svenklemm** [comment]
Closing this since I have not seen this appear in recent versions.
