### ISSUE TITLE
Multi-threaded COPY insertions result in segfault

### ISSUE THREAD

**Issue by nixxholas** [timescale/timescaledb#3538]
**Relevant system information:**
 - OS: Ubuntu 20.04 LTS
 - PostgreSQL version (output of `postgres --version`): Ubuntu 13.4-1.pgdg20.04+1
 - TimescaleDB version (output of `\dx` in `psql`): 2.4.1
 - Installation method: apt install

**Describe the bug**

**To Reproduce**
1. 8-16 instances of our same application utilising the rust-postgres library performs a COPY operation (Data is in binary format) to 3 tables concurrently with separate workers.
2. Segfault occurs on bigger batches of COPY

**Expected behavior**
COPY should happen without any problems.

**Actual behavior**
Segmentation fault occurs, postgres instance would die and enter recovery mode before coming back alive.

Traces are here from 2 data nodes.
   ```
PID: 552348 (postgres)
           UID: 107 (postgres)
           GID: 115 (postgres)
        Signal: 11 (SEGV)
     Timestamp: Mon 2021-08-30 11:59:50 CEST (38min ago)
  Command Line: postgres: 13/main: si_admin sol_indexer 192.168.100.1(35084) COPY
    Executable: /usr/lib/postgresql/13/bin/postgres
 Control Group: /system.slice/system-postgresql.slice/postgresql@13-main.service
          Unit: postgresql@13-main.service
         Slice: system-postgresql.slice
       Boot ID: 2ac9abe0823346cdb7b3462b97b98b0f
    Machine ID: 170c427ac6144e4eb2c2e2acd5f1effe
      Hostname: sfm-dn-5-p
       Storage: /var/lib/systemd/coredump/core.postgres.107.2ac9abe0823346cdb7b3462b97b98b0f.552348.1630317590000000000000.lz4
       Message: Process 552348 (postgres) of user 107 dumped core.

                Stack trace of thread 552348:
                #0  0x0000561ba51c9988 n/a (n/a + 0x0)
                #1  0x0000561ba4577ce3 n/a (postgres + 0xc3ce3)
                #2  0x0000561ba469697f CatalogTupleUpdate (postgres + 0x1e297f)
                #3  0x00007f6acd6a8755 ts_catalog_update_tid_only (timescaledb-2.4.1.so + 0x25755)
                #4  0x00007f6acd6a877d ts_catalog_update_tid (timescaledb-2.4.1.so + 0x2577d)
                #5  0x00007f6acd6abb22 chunk_tuple_update_status (timescaledb-2.4.1.so + 0x28b22)
                #6  0x00007f6acd6d54fa ts_scanner_scan (timescaledb-2.4.1.so + 0x524fa)
                #7  0x00007f6acd6ab49a chunk_scan_internal (timescaledb-2.4.1.so + 0x2849a)
                #8  0x00007f6acd6e8698 ts_chunk_insert_state_destroy (timescaledb-2.4.1.so + 0x65698)
                #9  0x00007f6acd6beec0 ts_dimension_slice_free (timescaledb-2.4.1.so + 0x3bec0)
                #10 0x00007f6acd6bf660 ts_dimension_vec_free (timescaledb-2.4.1.so + 0x3c660)
                #11 0x00007f6acd6d5db9 subspace_store_internal_node_free (timescaledb-2.4.1.so + 0x52db9)
                #12 0x00007f6acd6beec0 ts_dimension_slice_free (timescaledb-2.4.1.so + 0x3bec0)
                #13 0x00007f6acd6bf660 ts_dimension_vec_free (timescaledb-2.4.1.so + 0x3c660)
                #14 0x00007f6acd6d60ac subspace_store_internal_node_free (timescaledb-2.4.1.so + 0x530ac)
                #15 0x00007f6acd6b96b4 copy_chunk_state_destroy (timescaledb-2.4.1.so + 0x366b4)
                #16 0x00007f6acd6d0c24 process_copy (timescaledb-2.4.1.so + 0x4dc24)
                #17 0x00007f6acd6d2929 process_ddl_command_start (timescaledb-2.4.1.so + 0x4f929)
                #18 0x0000561ba48d9baf n/a (postgres + 0x425baf)
                #19 0x0000561ba48d9cc8 n/a (postgres + 0x425cc8)
                #20 0x0000561ba48da127 PortalRun (postgres + 0x426127)
                #21 0x0000561ba48d5d87 n/a (postgres + 0x421d87)
                #22 0x0000561ba48d79fc PostgresMain (postgres + 0x4239fc)
                #23 0x0000561ba485fa6c n/a (postgres + 0x3aba6c)
                #24 0x0000561ba48609cf PostmasterMain (postgres + 0x3ac9cf)
                #25 0x0000561ba45e068a main (postgres + 0x12c68a)
                #26 0x00007f6b17b7d0b3 __libc_start_main (libc.so.6 + 0x270b3)
                #27 0x0000561ba45e072e _start (postgres + 0x12c72e)

GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/lib/postgresql/13/bin/postgres...
(No debugging symbols found in /usr/lib/postgresql/13/bin/postgres)
[New LWP 552348]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `postgres: 13/main: si_admin sol_indexer 192.168.100.1(35084) COPY             '.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000561ba51c9988 in ?? ()
```

Another one.
```
PID: 164055 (postgres)
           UID: 107 (postgres)
           GID: 115 (postgres)
        Signal: 11 (SEGV)
     Timestamp: Mon 2021-08-30 12:17:28 CEST (22min ago)
  Command Line: postgres: 13/main: si_admin sol_indexer 192.168.100.1(48200) COPY
    Executable: /usr/lib/postgresql/13/bin/postgres
 Control Group: /system.slice/system-postgresql.slice/postgresql@13-main.service
          Unit: postgresql@13-main.service
         Slice: system-postgresql.slice
       Boot ID: 87cb361e285a49a3b0345899b3f441a5
    Machine ID: 6e0a95aa10054267929c7cc8d5569aba
      Hostname: sfm-dn-7-p
       Storage: /var/lib/systemd/coredump/core.postgres.107.87cb361e285a49a3b0345899b3f441a5.164055.1630318648000000000000.lz4
       Message: Process 164055 (postgres) of user 107 dumped core.

                Stack trace of thread 164055:
                #0  0x0000562b3ea47fa8 n/a (n/a + 0x0)
                #1  0x0000562b3d1ffce3 n/a (postgres + 0xc3ce3)
                #2  0x0000562b3d31e97f CatalogTupleUpdate (postgres + 0x1e297f)
                #3  0x00007f5f9a0f5755 ts_catalog_update_tid_only (timescaledb-2.4.1.so + 0x25755)
                #4  0x00007f5f9a0f577d ts_catalog_update_tid (timescaledb-2.4.1.so + 0x2577d)
                #5  0x00007f5f9a0f8b22 chunk_tuple_update_status (timescaledb-2.4.1.so + 0x28b22)
                #6  0x00007f5f9a1224fa ts_scanner_scan (timescaledb-2.4.1.so + 0x524fa)
                #7  0x00007f5f9a0f849a chunk_scan_internal (timescaledb-2.4.1.so + 0x2849a)
                #8  0x00007f5f9a135698 ts_chunk_insert_state_destroy (timescaledb-2.4.1.so + 0x65698)
                #9  0x00007f5f9a10bec0 ts_dimension_slice_free (timescaledb-2.4.1.so + 0x3bec0)
                #10 0x00007f5f9a10c660 ts_dimension_vec_free (timescaledb-2.4.1.so + 0x3c660)
                #11 0x00007f5f9a122db9 subspace_store_internal_node_free (timescaledb-2.4.1.so + 0x52db9)
                #12 0x00007f5f9a10bec0 ts_dimension_slice_free (timescaledb-2.4.1.so + 0x3bec0)
                #13 0x00007f5f9a10c660 ts_dimension_vec_free (timescaledb-2.4.1.so + 0x3c660)
                #14 0x00007f5f9a1230ac subspace_store_internal_node_free (timescaledb-2.4.1.so + 0x530ac)
                #15 0x00007f5f9a1066b4 copy_chunk_state_destroy (timescaledb-2.4.1.so + 0x366b4)
                #16 0x00007f5f9a11dc24 process_copy (timescaledb-2.4.1.so + 0x4dc24)
                #17 0x00007f5f9a11f929 process_ddl_command_start (timescaledb-2.4.1.so + 0x4f929)
                #18 0x0000562b3d561baf n/a (postgres + 0x425baf)
                #19 0x0000562b3d561cc8 n/a (postgres + 0x425cc8)
                #20 0x0000562b3d562127 PortalRun (postgres + 0x426127)
                #21 0x0000562b3d55dd87 n/a (postgres + 0x421d87)
                #22 0x0000562b3d55f9fc PostgresMain (postgres + 0x4239fc)
                #23 0x0000562b3d4e7a6c n/a (postgres + 0x3aba6c)
                #24 0x0000562b3d4e89cf PostmasterMain (postgres + 0x3ac9cf)
                #25 0x0000562b3d26868a main (postgres + 0x12c68a)
                #26 0x00007f5fe45ca0b3 __libc_start_main (libc.so.6 + 0x270b3)
                #27 0x0000562b3d26872e _start (postgres + 0x12c72e)

GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/lib/postgresql/13/bin/postgres...
(No debugging symbols found in /usr/lib/postgresql/13/bin/postgres)
[New LWP 164055]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `postgres: 13/main: si_admin sol_indexer 192.168.100.1(48200) COPY             '.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000562b3ea47fa8 in ?? ()
```

**Comment by gayyappan** [comment]
@nixxholas Is there anything else happening in the background for this table - specifically 1) Is compression enabled and 2) do you have a compression policy that might compress chunks that you are copying data into?

**Comment by nixxholas** [comment]
> @nixxholas Is there anything else happening in the background for this table - specifically 1) Is compression enabled and 2) do you have a compression policy that might compress chunks that you are copying data into?
> 
> Are you able to share the core dump file? Want to see if I can get some more info from it.

Noted. @BingHuang-Chin need your assistance on this.

**Comment by NunoFilipeSantos** [comment]
@nixxholas can you provide more information?

**Comment by NunoFilipeSantos** [comment]
@nixxholas and @binghuang-chin can you please provide more information? Otherwise, we can advise updating to our latest version, closing this issue, and re-opening it if you can still reproduce it. Thank you!
