### ISSUE TITLE
Compression job running after inserting data fails

### ISSUE THREAD

**Issue by hardikm10** [timescale/timescaledb#3656]
Relevant system information:
OS: [e.g. Ubuntu 16.04, Windows 10 x64, etc]: Docker / timescale/timescaledb:2.4.2-pg13

PostgreSQL version (output of postgres --version): 13.4
TimescaleDB version (output of \dx in psql): 2.4.2
Installation method: [e.g., "using Docker", "apt install", "source"] : "Using Docker"

**Describe the bug**
Calling run_job(compression_job_id) fails with the error "ERROR: cannot fetch toast data without an active snapshot"
if there were inserts into the compressed chunks.

**To Reproduce**
```
drop table sensor_data;

create table sensor_data(
time timestamptz not null,
sensor_id integer not null,
cpu double precision null,
temperature double precision null );

select from create_hypertable('sensor_data','time');

INSERT INTO sensor_data
SELECT
time + (INTERVAL '1 minute' * random()) AS time,
sensor_id,
random() AS cpu,
random()* 100 AS temperature
FROM
generate_series(now() - INTERVAL '1 months', now() - INTERVAL '1 week', INTERVAL '10 minute') AS g1(time),
generate_series(1, 100, 1 ) AS g2(sensor_id)
ORDER BY
time;

\d+ sensor_data

alter table sensor_data set (timescaledb.compress, timescaledb.compress_orderby = 'time DESC');
select add_compression_policy('sensor_data','1 minute'::INTERVAL);

--- Wait for all the chunks to be compressed ----
-- Use below to confirm above--
SELECT c.chunk_name,c.range_start,c.range_end,c.is_compressed,pg_size_pretty(d.total_bytes) FROM public.chunks_detailed_size('public.sensor_data') d, timescaledb_information.chunks c WHERE d.chunk_name=c.chunk_name order by c.range_start;

-- Insert into the first chunk which is already compressed--
insert
	into
	sensor_data
select
	time + (interval '1 minute' * random()) as time,
	sensor_id,
	random() as cpu,
	random()* 100 as temperature
from
	generate_series('2021-09-02 00:00:00+00'::timestamptz, '2021-09-08 00:00:00+00'::timestamptz, interval '10 minute') as g1(time),
	generate_series(1, 100, 1 ) as g2(sensor_id)
order by
	time;

CALL run_job(1000);

postgres=# call run_job(1000);
ERROR:  cannot fetch toast data without an active snapshot
```

**Expected behavior**
The job should run and compress the chunks.

**Actual behavior**
The job fails to run if called manually using 'CALL run_job'.

**Comment by mkindahl** [comment]
The error is reported from inside `init_toast_snapshot` when there is no snapshot returned from `GetOldestSnapshot()`, which means that there is no snapshot at all. This function is called from two locations: `toast_delete_datum` and `toast_fetch_datum_slice`,  which seems to be called when deleting or scanning tuples in a table that has a TOAST table (which a compressed chunk has).

- `toast_delete_datum` is called from `toast_tuple_cleanup`, which finally is called from `heap_toast_insert_or_update`.
- `toast_fetch_datum_slice` is called from `table_relation_fetch_toast_slice` which is called when detoasting a tuple in the toast table for the compressed table.

Inside the procedure `policy_compression_execute` (and `policy_recompression_execute`) we have the following sequence:

```
	if (ActiveSnapshotSet())
		PopActiveSnapshot();
	/* process each chunk in a new transaction */
	int total_chunks = list_length(chunkid_lst), num_chunks = 0;
	foreach (lc, chunkid_lst)
	{
		CommitTransactionCommand();
		StartTransactionCommand();
                       .
                       .
                       .
	}
```

So, we pop the active snapshot, potentially leaving no snapshot at all, and then commit the transaction and start a new one. I wonder if we should have a `PushActiveSnapshot(GetTransactionSnapshot())` after having started the new transaction since we potentially can have a call to `heap_toast_insert_or_update` or `table_relation_fetch_toast_slice`  as part of the recompress policy execution.

**Comment by hardikm10** [comment]
Adding here for completeness, a segfault also occurs on CALL run_job in some cases: 

For example, after some drop_chunk, reinsert into compressed chunk and logging out and logging again, the test service was segfaulting (not necessary that this order has to be followed) , and here's the backtrace:

```
(gdb) bt
#0  0x000055c198311fa6 in GetActiveSnapshot () at utils/time/./build/../src/backend/utils/time/snapmgr.c:845
#1  InitializeParallelDSM (pcxt=0x55c199cff2a8) at access/transam/./build/../src/backend/access/transam/parallel.c:220
#2  0x000055c1982f2e87 in _bt_begin_parallel (request=1, isconcurrent=<optimized out>, buildstate=0x7ffc70db5950) at access/nbtree/./build/../src/backend/access/nbtree/nbtsort.c:1545
#3  _bt_spools_heapscan (indexInfo=0x55c199cff198, buildstate=0x7ffc70db5950, index=..., heap=0x7fbeac74fcf8) at access/nbtree/./build/../src/backend/access/nbtree/nbtsort.c:394
#4  btbuild (heap=0x7fbeac74fcf8, index=0x7fbeac753498, indexInfo=0x55c199cff198) at access/nbtree/./build/../src/backend/access/nbtree/nbtsort.c:326
#5  0x000055c198356995 in index_build (heapRelation=0x7fbeac74fcf8, indexRelation=0x7fbeac753498, indexInfo=0x55c199cff198, isreindex=<optimized out>, parallel=<optimized out>) at catalog/./build/../src/backend/catalog/index.c:2962
#6  0x000055c198357397 in reindex_index (indexId=41860, skip_constraint_checks=<optimized out>, persistence=<optimized out>, options=0) at catalog/./build/../src/backend/catalog/index.c:3587
#7  0x000055c198357835 in reindex_relation (relid=relid@entry=41856, flags=flags@entry=0, options=options@entry=0) at catalog/./build/../src/backend/catalog/index.c:3810
#8  0x00007fbeac8586b9 in decompress_chunk (out_table=41856, in_table=<optimized out>) at /build/timescaledb/tsl/src/compression/compression.c:1097
#9  decompress_chunk_impl (uncompressed_hypertable_relid=41851, uncompressed_chunk_relid=41856, if_compressed=<optimized out>) at /build/timescaledb/tsl/src/compression/compress_utils.c:337
#10 0x00007fbeac882d9e in tsl_recompress_chunk_wrapper.isra.0 (uncompressed_chunk=0x55c199cfebb8) at /build/timescaledb/tsl/src/compression/compress_utils.c:576
#11 0x00007fbeac84a9a9 in policy_compression_execute (config=<optimized out>, job_id=1001) at /build/timescaledb/tsl/src/bgw_policy/job.c:610
#12 policy_compression_proc (fcinfo=<optimized out>) at /build/timescaledb/tsl/src/bgw_policy/compression_api.c:149
#13 policy_compression_proc (fcinfo=<optimized out>) at /build/timescaledb/tsl/src/bgw_policy/compression_api.c:142
#14 0x000055c198403a36 in ExecuteCallStmt (stmt=stmt@entry=0x55c199d49b28, params=<optimized out>, atomic=atomic@entry=false, dest=dest@entry=0x55c1989d25a0 <donothingDR.lto_priv.0>)
    at commands/./build/../src/backend/commands/functioncmds.c:2232
#15 0x00007fbeac84937b in job_execute_procedure (funcexpr=0x55c199d4a518) at /build/timescaledb/tsl/src/bgw_policy/job.c:751
#16 job_execute (job=<optimized out>) at /build/timescaledb/tsl/src/bgw_policy/job.c:832
#17 0x00007fbeac84957f in job_run (fcinfo=<optimized out>) at /build/timescaledb/tsl/src/bgw_policy/job_api.c:305
#18 0x000055c198403a36 in ExecuteCallStmt (stmt=<optimized out>, params=<optimized out>, atomic=<optimized out>, dest=<optimized out>) at commands/./build/../src/backend/commands/functioncmds.c:2232
#19 0x000055c1986010e6 in standard_ProcessUtility (pstmt=0x55c199c3f088, queryString=<optimized out>, context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, dest=0x55c199c3f530, qc=0x7ffc70db7600)
    at tcop/./build/../src/backend/tcop/utility.c:817
#20 0x00007fbecf1c2be6 in pgss_ProcessUtility (pstmt=0x55c199c3f088, queryString=0x55c199c3e4b8 "call run_job(1001);", context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, dest=0x55c199c3f530, qc=0x7ffc70db7600)
    at ./build/../contrib/pg_stat_statements/pg_stat_statements.c:1156
#21 0x00007fbeac925ce7 in ?? () from /usr/lib/postgresql/13/lib/plugins/pgextwlist.so
#22 0x00007fbeac8df737 in prev_ProcessUtility (args=<optimized out>) at /build/timescaledb/src/process_utility.c:90
#23 0x00007fbeac8ec78e in timescaledb_ddl_command_start (pstmt=0x55c199c3f088, query_string=<optimized out>, context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=<optimized out>, dest=0x55c199c3f530, completion_tag=0x7ffc70db7600)
    at /build/timescaledb/src/process_utility.c:4078
#24 0x000055c198601ca3 in ProcessUtility (qc=0x7ffc70db7600, dest=0x55c199c3f530, queryEnv=<optimized out>, params=<optimized out>, context=PROCESS_UTILITY_TOPLEVEL, queryString=<optimized out>, pstmt=0x55c199c3f088)
    at tcop/./build/../src/backend/tcop/utility.c:520
#25 PortalRunUtility (portal=portal@entry=0x55c199ce36b8, pstmt=pstmt@entry=0x55c199c3f088, isTopLevel=isTopLevel@entry=true, setHoldSnapshot=setHoldSnapshot@entry=false, dest=0x55c199c3f530, qc=0x7ffc70db7600)
    at tcop/./build/../src/backend/tcop/pquery.c:1145
#26 0x000055c198601e25 in PortalRunMulti (portal=portal@entry=0x55c199ce36b8, isTopLevel=isTopLevel@entry=true, setHoldSnapshot=setHoldSnapshot@entry=false, dest=dest@entry=0x55c199c3f530, altdest=altdest@entry=0x55c199c3f530,
    qc=qc@entry=0x7ffc70db7600) at tcop/./build/../src/backend/tcop/pquery.c:1308
#27 0x000055c19860232e in PortalRun (portal=0x55c199ce36b8, count=9223372036854775807, isTopLevel=<optimized out>, run_once=<optimized out>, dest=0x55c199c3f530, altdest=0x55c199c3f530, qc=0x7ffc70db7600)
    at tcop/./build/../src/backend/tcop/pquery.c:786
#28 0x000055c1985faff3 in exec_simple_query (query_string=0x55c199c3e4b8 "call run_job(1001);") at tcop/./build/../src/backend/tcop/postgres.c:1239
#29 0x000055c1985fd727 in PostgresMain (argc=<optimized out>, argv=<optimized out>, dbname=<optimized out>, username=<optimized out>) at tcop/./build/../src/backend/tcop/postgres.c:4339
#30 0x000055c19857beb8 in BackendRun (port=0x55c199c892c0) at postmaster/./build/../src/backend/postmaster/postmaster.c:4526
#31 BackendStartup (port=0x55c199c892c0) at postmaster/./build/../src/backend/postmaster/postmaster.c:4210
#32 ServerLoop () at postmaster/./build/../src/backend/postmaster/postmaster.c:1739
#33 0x000055c19857cdb4 in PostmasterMain (argc=<optimized out>, argv=<optimized out>) at postmaster/./build/../src/backend/postmaster/postmaster.c:1412
#34 0x000055c19827e989 in main (argc=17, argv=0x55c199c37030) at main/./build/../src/backend/main/main.c:210
```
