### ISSUE TITLE
Disabling materialized_only on continuous aggregates that have a HAVING clause crashes

### ISSUE THREAD

**Issue by gayyappan** [timescale/timescaledb#3696]
Crash on PG13.4 , on master code.

Steps to reproduce.

Create a continuous aggregate with a HAVING clause and change default materialized_only option.
```
create table raw_data(time timestamptz, search_query text, cnt integer, cnt2 integer);
select create_hypertable('raw_data','time', chunk_time_interval=>'15 days'::interval);
insert into raw_data select '2000-01-01','Q1';

CREATE MATERIALIZED VIEW search_query_count_3 WITH (timescaledb.continuous)
AS
 SELECT  search_query,count(search_query) as count, sum(cnt),
         time_bucket(INTERVAL '1 minute', time) AS bucket
 FROM raw_data
 WHERE search_query is not null AND LENGTH(TRIM(both from search_query))>0
 GROUP BY cnt +cnt2 , bucket, search_query
 HAVING cnt + cnt2 + sum(cnt) > 2 or count(cnt2) > 10;

insert into raw_data select '2000-01-01 00:00+0','Q1', 1, 100;
insert into raw_data select '2000-01-01 00:00+0','Q1', 2, 200;
insert into raw_data select '2000-01-01 00:00+0','Q1', 3, 300;
insert into raw_data select '2000-01-02 00:00+0','Q2', 10, 10;
insert into raw_data select '2000-01-02 00:00+0','Q2', 20, 20;

--refresh search_query_count_3---
CALL refresh_continuous_aggregate('search_query_count_3', NULL, NULL);
SELECT * FROM search_query_count_3 ORDER BY 1, 2, 3;
```

This aborts due to an assertion failure
```
alter materialized view search_query_count_3 set (timescaledb.materialized_only = 'true');

```

**Comment by gayyappan** [comment]
```
#0  0x00007f4462165fb7 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f4462167921 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x0000564bfe21b83b in ExceptionalCondition (
    conditionName=0x7f4458701300 "list_length(view_query->targetList) == list_length(user_query->targetList)", 
    errorType=0x7f44587002fa "FailedAssertion", 
    fileName=0x7f4458700468 "/home/gayyappa/gitrepo/timescaledb/tsl/src/continuous_aggs/create.c", lineNumber=1965) at assert.c:67
#3  0x00007f44586a82ad in cagg_update_view_definition (agg=0x564c001db2a0, 
    mat_ht=0x564c00442d88)
    at /home/gayyappa/gitrepo/timescaledb/tsl/src/continuous_aggs/create.c:1965
#4  0x00007f44586ab3d0 in continuous_agg_update_options (
    agg=0x564c001db2a0, with_clause_options=0x564c0044d978)
    at /home/gayyappa/gitrepo/timescaledb/tsl/src/continuous_aggs/options.c:80
#5  0x00007f445898afb3 in process_altercontinuousagg_set_with (
    cagg=0x564c001db2a0, view_relid=42390, defelems=0x564c00113958)
    at /home/gayyappa/gitrepo/timescaledb/src/process_utility.c:3120
#6  0x00007f445898b287 in process_altertable_start_matview (
    args=0x7ffe605f5e40)
    at /home/gayyappa/gitrepo/timescaledb/src/process_utility.c:3184
#7  0x00007f445898b584 in process_altertable_start (args=0x7ffe605f5e40)
```
