### ISSUE TITLE
Segfault in compress_chunk -> GetActiveSnapshot

### ISSUE THREAD

**Issue by lukepalmer** [timescale/timescaledb#3740]
**Relevant system information:**
 - OS: EL7
 - PostgreSQL version (output of `postgres --version`): 12.8
 - TimescaleDB version (output of `\dx` in `psql`): 2.4.2
 - Installation method: rpm

**Describe the bug**
#0  0x00000000008b8897 in GetActiveSnapshot () at snapmgr.c:845
#1  0x00000000004fc3a0 in InitializeParallelDSM (pcxt=pcxt@entry=0x12d3890) at parallel.c:213
#2  0x00000000004e4608 in _bt_begin_parallel (request=2, isconcurrent=<optimized out>, buildstate=0x7fffffffc000) at nbtsort.c:1417
#3  _bt_spools_heapscan (indexInfo=0x12bdbe0, buildstate=0x7fffffffc000, index=..., heap=0xf49b20) at nbtsort.c:408
#4  btbuild (heap=0xf49b20, index=0xf59300, indexInfo=0x12bdbe0) at nbtsort.c:340
#5  0x000000000052b7f6 in index_build (heapRelation=heapRelation@entry=0xf49b20, indexRelation=indexRelation@entry=0xf59300, 
    indexInfo=indexInfo@entry=0x12bdbe0, isreindex=isreindex@entry=true, parallel=parallel@entry=true) at index.c:2971
#6  0x000000000052df33 in reindex_index (indexId=indexId@entry=89825582, skip_constraint_checks=<optimized out>, 
    persistence=persistence@entry=112 'p', options=options@entry=0) at index.c:3596
#7  0x000000000052e3ce in reindex_relation (relid=relid@entry=89825576, flags=flags@entry=0, options=options@entry=0) at index.c:3819
#8  0x00007ff7b3ec6333 in compress_chunk (in_table=77888536, out_table=89825576, 
    column_compression_info=column_compression_info@entry=0x12ae988, num_compression_infos=num_compression_infos@entry=105)
    at /home/builder/rpmbuild/BUILD/timescaledb/tsl/src/compression/compression.c:309
#9  0x00007ff7b3ec9f41 in compress_chunk_impl (chunk_relid=<optimized out>, hypertable_relid=<optimized out>)
    at /home/builder/rpmbuild/BUILD/timescaledb/tsl/src/compression/compress_utils.c:254
#10 tsl_compress_chunk_wrapper (chunk=chunk@entry=0xda8970, if_not_compressed=if_not_compressed@entry=true)
    at /home/builder/rpmbuild/BUILD/timescaledb/tsl/src/compression/compress_utils.c:366
#11 0x00007ff7b3ebebf5 in policy_compression_execute (job_id=1000, config=<optimized out>)
    at /home/builder/rpmbuild/BUILD/timescaledb/tsl/src/bgw_policy/job.c:612
#12 0x00007ff7b3ebc615 in policy_compression_proc (fcinfo=0x7fffffffc830)
    at /home/builder/rpmbuild/BUILD/timescaledb/tsl/src/bgw_policy/compression_api.c:149
#13 0x00000000005c1c64 in ExecuteCallStmt (stmt=stmt@entry=0xdaabc8, params=<optimized out>, atomic=atomic@entry=false, 
    dest=dest@entry=0x9fffa0 <donothingDR>) at functioncmds.c:2411
#14 0x00007ff7b3ebf1aa in job_execute_procedure (funcexpr=0xdaa738) at /home/builder/rpmbuild/BUILD/timescaledb/tsl/src/bgw_policy/job.c:751
#15 job_execute (job=<optimized out>) at /home/builder/rpmbuild/BUILD/timescaledb/tsl/src/bgw_policy/job.c:832
#16 0x00007ff7b3ebfb4b in job_run (fcinfo=<optimized out>) at /home/builder/rpmbuild/BUILD/timescaledb/tsl/src/bgw_policy/job_api.c:305
#17 0x00000000005c1c64 in ExecuteCallStmt (stmt=stmt@entry=0xd80700, params=params@entry=0x0, atomic=atomic@entry=false, 
    dest=dest@entry=0xd80d60) at functioncmds.c:2411
#18 0x0000000000767e36 in standard_ProcessUtility (pstmt=0xd80cd0, queryString=0xd7fbe0 "CALL run_job(1000);", 
    context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, dest=0xd80d60, completionTag=0x7fffffffdac0 "") at utility.c:652

**To Reproduce**
> SET client_min_messages TO DEBUG1;
> select add_compression_policy('foo', INTERVAL '5d');
> CALL run_job(<N>);
(bunch of chunks compressed succesfully)
DEBUG:  building index "compress_hyper_6_60_chunk__compressed_hypertable_6_foobar__" on table "compress_hyper_6_60_chunk" with request for 2 parallel workers
Observe segfault.

**Expected behavior**
No segfault

**Actual behavior**
Segfault :(

**Additional context**
I can reproduce this consistently. 
Not sure if relevant but a bunch fo similar data compresses just fine, and only the last one that fails says "...with request for 2 parallel workers"

**Comment by lukepalmer** [comment]
I can no longer reproduce on 2.5.0. Closing, thank you.
