### ISSUE TITLE
[Bug]: pqRowProcessor segfault

### ISSUE THREAD

**Issue by svenklemm** [timescale/timescaledb#3964]
### What type of bug is this?

Crash

### What subsystems and features are affected?

Multi-node

### What happened?

.

### TimescaleDB version affected

2.5.1

### PostgreSQL version used

14.1

### What operating system did you use?

Archlinux 2021.12.01 x64

### What installation method did you use?

Source

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
#0  pqRowProcessor (conn=0x555a06d84b60, errmsgp=0x7ffe93064060) at fe-exec.c:1156
        isbinary = false
        val = 0x8 <error: Cannot access memory at address 0x8>
        clen = 8
        res = 0x555a06dc2cb0
        nfields = 1
        columns = 0x555a06d7b760
        tup = 0x555a07837878
        i = 0
#1  0x00007fd3b582b281 in getAnotherTuple (conn=0x555a06d84b60, msgLength=14) at fe-protocol3.c:840
        result = 0x555a06dc2cb0
        nfields = 1
        errmsg = 0x0
        rowbuf = 0x555a06d7b760
        tupnfields = 1
        vlen = 8
        i = 1
#2  0x00007fd3b582a60f in pqParseInput3 (conn=0x555a06d84b60) at fe-protocol3.c:387
        id = 68 'D'
        msgLength = 14
        avail = 3836
#3  0x00007fd3b5821a24 in parseInput (conn=0x555a06d84b60) at fe-exec.c:1942
No locals.
#4  0x00007fd3b5821a4d in PQisBusy (conn=0x555a06d84b60) at fe-exec.c:1957
No locals.
#5  0x00007fd3b58f1006 in get_single_response_nonblocking (set=0x555a077dfff0) at /home/sven/projects/timescaledb/tsl/src/remote/async.c:632
        req = 0x555a06f43750
        pg_conn = 0x555a06d84b60
        lc__state = {l = 0x555a077e0010, i = 0}
        lc = 0x555a077e0028
#6  0x00007fd3b58f1447 in async_request_set_wait_any_response_deadline (set=0x555a077dfff0, endtime=-9223372036854775808) at /home/sven/projects/timescaledb/tsl/src/remote/async.c:762
        response = 0x0
#7  0x00007fd3b58f15cd in async_request_set_wait_any_result (set=0x555a077dfff0) at /home/sven/projects/timescaledb/tsl/src/remote/async.c:815
        res = 0x555a06ee9a30
#8  0x00007fd3b59004d3 in row_by_row_fetcher_complete (fetcher=0x555a077df690) at /home/sven/projects/timescaledb/tsl/src/remote/row_by_row_fetcher.c:164
        res = 0x0
        i = 0
        _save_exception_stack = 0x7ffe93065460
        _save_context_stack = 0x0
        _local_sigjmp_buf = {{__jmpbuf = {0, 1308322263334289265, 93845111850816, 0, 0, 0, 1308322263216848753, 1329218325025423217}, __mask_was_saved = 0, __saved_mask = {__val = {9897720114400148480, 140547261124424, 0,
                93845111850816, 0, 0, 93845150692320, 140731365081936, 140547260897731, 90194313217, 93845150212080, 140731365081968, 93845151578784, 93845161114832, 93845151116256, 140731365082256}}}}
        _do_rethrow = false
        response = 0x0
        oldcontext = 0x555a06ec7aa0
        fetch_req_wrapper = 0x555a077dfff0
        __func__ = "row_by_row_fetcher_complete"
#9  0x00007fd3b5900b5f in row_by_row_fetcher_fetch_data (df=0x555a077df690) at /home/sven/projects/timescaledb/tsl/src/remote/row_by_row_fetcher.c:252
        fetcher = 0x555a077df690
#10 0x00007fd3b58db799 in fetch_data (ass=0x555a07164b70) at /home/sven/projects/timescaledb/tsl/src/fdw/data_node_scan_exec.c:163
        dnss = 0x555a07164b70
        fetcher = 0x555a077df690
#11 0x00007fd3b58dbfe1 in fetch_data (ass=0x555a07164b70) at /home/sven/projects/timescaledb/tsl/src/nodes/async_append.c:248
No locals.
#12 0x00007fd3b58dbf27 in iterate_data_nodes_and_exec (aas=0x555a07164170, dn_exec=0x7fd3b58dbfc1 <fetch_data>) at /home/sven/projects/timescaledb/tsl/src/nodes/async_append.c:229
        dnss = 0x555a07164b70
        lc__state = {l = 0x555a07167938, i = 0}
        lc = 0x555a07167950
#13 0x00007fd3b58dc0d3 in async_append_exec (node=0x555a07164170) at /home/sven/projects/timescaledb/tsl/src/nodes/async_append.c:269
        slot = 0x5704c93b14
        state = 0x555a07164170
        econtext = 0x555a07164388
#14 0x0000555a04c0b4d0 in ExecCustomScan (pstate=0x555a07164170) at nodeCustom.c:115
        node = 0x555a07164170
#15 0x0000555a04bec7f7 in ExecProcNodeFirst (node=0x555a07164170) at execProcnode.c:463
No locals.
#16 0x0000555a04bfc960 in ExecProcNode (node=0x555a07164170) at ../../../src/include/executor/executor.h:257
No locals.
#17 0x0000555a04bfced4 in fetch_input_tuple (aggstate=0x555a07163b70) at nodeAgg.c:581
        slot = 0x555a07164040
#18 0x0000555a04c00380 in agg_retrieve_direct (aggstate=0x555a07163b70) at nodeAgg.c:2364
        node = 0x555a076889e8
        econtext = 0x555a071640d8
        tmpcontext = 0x555a07163fa8
        peragg = 0x555a077cd5c8
        pergroups = 0x555a077cd878
        outerslot = 0x555a07163b70
        firstSlot = 0x555a07167990
        result = 0x6104bcec54
        hasGroupingSets = false
        numGroupingSets = 1
        currentSet = 21850
        nextSetSize = 0
        numReset = 1
        i = 1
#19 0x0000555a04bfff46 in ExecAgg (pstate=0x555a07163b70) at nodeAgg.c:2179
        node = 0x555a07163b70
        result = 0x0
#20 0x0000555a04bec7f7 in ExecProcNodeFirst (node=0x555a07163b70) at execProcnode.c:463
No locals.
#21 0x0000555a04c347b8 in ExecProcNode (node=0x555a07163b70) at ../../../src/include/executor/executor.h:257
No locals.
#22 0x0000555a04c36ee4 in ExecSetParamPlan (node=0x555a077d45f8, econtext=0x555a077d2e48) at nodeSubplan.c:1118
        subplan = 0x555a07691728
        planstate = 0x555a07163b70
        subLinkType = EXPR_SUBLINK
        estate = 0x555a06ec7bc0
        dir = ForwardScanDirection
        oldcontext = 0x555a0707bc20
        slot = 0x555a06ec7aa0
        pvar = 0x0
        l = 0x0
        found = false
        astate = 0x0
        __func__ = "ExecSetParamPlan"
#23 0x0000555a04bd7585 in ExecEvalParamExec (state=0x555a077d3c40, op=0x555a077d3d88, econtext=0x555a077d2e48) at execExprInterp.c:2414
        prm = 0x555a06ec7e38
#24 0x0000555a04bd4a42 in ExecInterpExpr (state=0x555a077d3c40, econtext=0x555a077d2e48, isnull=0x7ffe93064adf) at execExprInterp.c:1062
        op = 0x555a077d3d88
        resultslot = 0x0
        innerslot = 0x0
        outerslot = 0x0
        scanslot = 0x0
        dispatch_table = {0x555a04bd3779 <ExecInterpExpr+166>, 0x555a04bd37a0 <ExecInterpExpr+205>, 0x555a04bd37e8 <ExecInterpExpr+277>, 0x555a04bd3833 <ExecInterpExpr+352>, 0x555a04bd387e <ExecInterpExpr+427>,
          0x555a04bd393b <ExecInterpExpr+616>, 0x555a04bd39f8 <ExecInterpExpr+805>, 0x555a04bd3ab5 <ExecInterpExpr+994>, 0x555a04bd3af0 <ExecInterpExpr+1053>, 0x555a04bd3b2b <ExecInterpExpr+1112>, 0x555a04bd3b66 <ExecInterpExpr+1171>,
          0x555a04bd3b9d <ExecInterpExpr+1226>, 0x555a04bd3ccc <ExecInterpExpr+1529>, 0x555a04bd3dfb <ExecInterpExpr+1832>, 0x555a04bd3f2a <ExecInterpExpr+2135>, 0x555a04bd3fe2 <ExecInterpExpr+2319>,
          0x555a04bd40ee <ExecInterpExpr+2587>, 0x555a04bd4136 <ExecInterpExpr+2659>, 0x555a04bd41a3 <ExecInterpExpr+2768>, 0x555a04bd427b <ExecInterpExpr+2984>, 0x555a04bd42b2 <ExecInterpExpr+3039>,
          0x555a04bd42e9 <ExecInterpExpr+3094>, 0x555a04bd42f7 <ExecInterpExpr+3108>, 0x555a04bd4388 <ExecInterpExpr+3253>, 0x555a04bd43f6 <ExecInterpExpr+3363>, 0x555a04bd4404 <ExecInterpExpr+3377>,
          0x555a04bd4495 <ExecInterpExpr+3522>, 0x555a04bd4503 <ExecInterpExpr+3632>, 0x555a04bd4547 <ExecInterpExpr+3700>, 0x555a04bd45e8 <ExecInterpExpr+3861>, 0x555a04bd462d <ExecInterpExpr+3930>,
          0x555a04bd469b <ExecInterpExpr+4040>, 0x555a04bd470c <ExecInterpExpr+4153>, 0x555a04bd478d <ExecInterpExpr+4282>, 0x555a04bd47de <ExecInterpExpr+4363>, 0x555a04bd4832 <ExecInterpExpr+4447>,
          0x555a04bd4869 <ExecInterpExpr+4502>, 0x555a04bd48a0 <ExecInterpExpr+4557>, 0x555a04bd48e9 <ExecInterpExpr+4630>, 0x555a04bd4961 <ExecInterpExpr+4750>, 0x555a04bd49d9 <ExecInterpExpr+4870>,
          0x555a04bd4a22 <ExecInterpExpr+4943>, 0x555a04bd4a59 <ExecInterpExpr+4998>, 0x555a04bd4a90 <ExecInterpExpr+5053>, 0x555a04bd4ad0 <ExecInterpExpr+5117>, 0x555a04bd4bf2 <ExecInterpExpr+5407>,
          0x555a04bd4c5d <ExecInterpExpr+5514>, 0x555a04bd4e91 <ExecInterpExpr+6078>, 0x555a04bd4f84 <ExecInterpExpr+6321>, 0x555a04bd5068 <ExecInterpExpr+6549>, 0x555a04bd5144 <ExecInterpExpr+6769>,
          0x555a04bd5174 <ExecInterpExpr+6817>, 0x555a04bd51a4 <ExecInterpExpr+6865>, 0x555a04bd51d4 <ExecInterpExpr+6913>, 0x555a04bd5204 <ExecInterpExpr+6961>, 0x555a04bd523b <ExecInterpExpr+7016>,
          0x555a04bd526b <ExecInterpExpr+7064>, 0x555a04bd541d <ExecInterpExpr+7498>, 0x555a04bd5566 <ExecInterpExpr+7827>, 0x555a04bd5596 <ExecInterpExpr+7875>, 0x555a04bd55cd <ExecInterpExpr+7930>,
          0x555a04bd5604 <ExecInterpExpr+7985>, 0x555a04bd563b <ExecInterpExpr+8040>, 0x555a04bd56c4 <ExecInterpExpr+8177>, 0x555a04bd56c6 <ExecInterpExpr+8179>, 0x555a04bd56c6 <ExecInterpExpr+8179>,
          0x555a04bd4b61 <ExecInterpExpr+5262>, 0x555a04bd57a4 <ExecInterpExpr+8401>, 0x555a04bd57d4 <ExecInterpExpr+8449>, 0x555a04bd5706 <ExecInterpExpr+8243>, 0x555a04bd573d <ExecInterpExpr+8298>,
          0x555a04bd576d <ExecInterpExpr+8346>, 0x555a04bd5804 <ExecInterpExpr+8497>, 0x555a04bd5834 <ExecInterpExpr+8545>, 0x555a04bd58e4 <ExecInterpExpr+8721>, 0x555a04bd5914 <ExecInterpExpr+8769>,
          0x555a04bd59ce <ExecInterpExpr+8955>, 0x555a04bd5a05 <ExecInterpExpr+9010>, 0x555a04bd5a5d <ExecInterpExpr+9098>, 0x555a04bd5b1f <ExecInterpExpr+9292>, 0x555a04bd5bdf <ExecInterpExpr+9484>,
          0x555a04bd5c98 <ExecInterpExpr+9669>, 0x555a04bd5d48 <ExecInterpExpr+9845>, 0x555a04bd5e8f <ExecInterpExpr+10172>, 0x555a04bd5f9d <ExecInterpExpr+10442>, 0x555a04bd6095 <ExecInterpExpr+10690>,
          0x555a04bd61d9 <ExecInterpExpr+11014>, 0x555a04bd62e4 <ExecInterpExpr+11281>, 0x555a04bd63d9 <ExecInterpExpr+11526>, 0x555a04bd6410 <ExecInterpExpr+11581>, 0x555a04bd6447 <ExecInterpExpr+11636>}
```

**Comment by svenklemm** [comment]
Fixed by #3948
