### ISSUE TITLE
[Bug]: remote_connection_drain malloc segfault

### ISSUE THREAD

**Issue by svenklemm** [timescale/timescaledb#3965]
### What type of bug is this?

Crash

### TimescaleDB version affected

master (0dd4329)

### PostgreSQL version used

14.1

### What operating system did you use?

Archlinux 2021.12.01 x64

### What installation method did you use?

Source

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
#0  0x00007fd3bedf8449 in malloc () from /usr/lib/libc.so.6
#1  0x00007fd3b583f9a0 in PQmakeEmptyPGresult (conn=0x555a06e4a220, status=PGRES_COMMAND_OK) at fe-exec.c:150
#2  0x00007fd3b584b15e in pqParseInput3 (conn=0x555a06e4a220) at fe-protocol3.c:214
#3  0x00007fd3b5842a24 in parseInput (conn=0x555a06e4a220) at fe-exec.c:1942
#4  0x00007fd3b5842a4d in PQisBusy (conn=0x555a06e4a220) at fe-exec.c:1957
#5  0x00007fd3b5916114 in remote_connection_drain (conn=0x555a06da3300, endtime=694977520705482, result=0x7ffe930653a0) at /home/sven/projects/timescaledb/tsl/src/remote/connection.c:1749
#6  0x00007fd3b5911ce3 in async_request_cleanup_result (req=0x555a06d2d4f0, endtime=694977520705482) at /home/sven/projects/timescaledb/tsl/src/remote/async.c:545
#7  0x00007fd3b5923ff1 in exec_cleanup_command (conn=0x555a06da3300, query=0x7fd3b595072f "ROLLBACK TRANSACTION") at /home/sven/projects/timescaledb/tsl/src/remote/txn.c:276
#8  0x00007fd3b5924672 in remote_txn_abort (entry=0x555a073bba30) at /home/sven/projects/timescaledb/tsl/src/remote/txn.c:423
#9  0x00007fd3b5919d11 in dist_txn_xact_callback_abort () at /home/sven/projects/timescaledb/tsl/src/remote/dist_txn.c:181
#10 0x00007fd3b591a5bb in dist_txn_xact_callback_2pc (event=XACT_EVENT_ABORT, arg=0x0) at /home/sven/projects/timescaledb/tsl/src/remote/dist_txn.c:481
#11 0x00007fd3b591a6b0 in dist_txn_xact_callback (event=XACT_EVENT_ABORT, arg=0x0) at /home/sven/projects/timescaledb/tsl/src/remote/dist_txn.c:523
#12 0x0000555a04a01c5f in CallXactCallbacks (event=XACT_EVENT_ABORT) at xact.c:3586
#13 0x0000555a04a00db8 in AbortTransaction () at xact.c:2768
#14 0x0000555a04a01357 in CommitTransactionCommand () at xact.c:3058
#15 0x0000555a04e57230 in finish_xact_command () at postgres.c:2721
#16 0x0000555a04e548e1 in exec_simple_query (query_string=0x555a06c8eda0 "ROLLBACK;") at postgres.c:1239
#17 0x0000555a04e596e5 in PostgresMain (argc=1, argv=0x7ffe93065800, dbname=0x555a06cc1920 "smith", username=0x555a06cc1900 "sven") at postgres.c:4486
#18 0x0000555a04d7ffff in BackendRun (port=0x555a06cb8e80) at postmaster.c:4530
#19 0x0000555a04d7f866 in BackendStartup (port=0x555a06cb8e80) at postmaster.c:4252
#20 0x0000555a04d7b5ef in ServerLoop () at postmaster.c:1745
#21 0x0000555a04d7ad64 in PostmasterMain (argc=3, argv=0x555a06c88650) at postmaster.c:1417
#22 0x0000555a04c6c989 in main (argc=3, argv=0x555a06c88650) at main.c:209
```

### How can we reproduce the bug?

This was found using sqlsmith with the setup described in our wiki.

**Comment by svenklemm** [comment]
Fixed by #3948
