### ISSUE TITLE
[Bug]: remote COPY malloc segfault

### ISSUE THREAD

**Issue by svenklemm** [timescale/timescaledb#3966]
### TimescaleDB version affected

master (0dd4329)

### PostgreSQL version used

14.1

### What operating system did you use?

Archlinux 2021.12.01 x64

### What installation method did you use?

Source

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
#0  0x00007fd3bedf8449 in malloc () from /usr/lib/libc.so.6
#1  0x00007fd3b581e9a0 in PQmakeEmptyPGresult (conn=0x555a06ef3360, status=PGRES_COPY_IN) at fe-exec.c:150
#2  0x00007fd3b582c449 in getCopyStart (conn=0x555a06ef3360, copytype=PGRES_COPY_IN) at fe-protocol3.c:1503
#3  0x00007fd3b582a6b6 in pqParseInput3 (conn=0x555a06ef3360) at fe-protocol3.c:410
#4  0x00007fd3b5821a24 in parseInput (conn=0x555a06ef3360) at fe-exec.c:1942
#5  0x00007fd3b5821b55 in PQgetResult (conn=0x555a06ef3360) at fe-exec.c:2027
#6  0x00007fd3b5822288 in PQexecFinish (conn=0x555a06ef3360) at fe-exec.c:2357
#7  0x00007fd3b5821f95 in PQexec (conn=0x555a06ef3360, query=0x555a06f03290 "COPY public.metrics_dist (\"time\", device_id, v0, v1, v2, v3) FROM STDIN WITH (FORMAT binary)") at fe-exec.c:2199
#8  0x00007fd3b58f5ad1 in remote_connection_begin_copy (conn=0x555a06d8ffd0, copycmd=0x555a06f03290 "COPY public.metrics_dist (\"time\", device_id, v0, v1, v2, v3) FROM STDIN WITH (FORMAT binary)", binary=true, err=0x7ffe93064cd0)
    at /home/sven/projects/timescaledb/tsl/src/remote/connection.c:2097
#9  0x00007fd3b58fb596 in start_remote_copy_on_new_connection (state=0x555a06f031c0, connection=0x555a06d8ffd0) at /home/sven/projects/timescaledb/tsl/src/remote/dist_copy.c:241
#10 0x00007fd3b58fb78c in create_connection_list_for_chunk (state=0x555a06f031c0, chunk_id=65583, chunk_data_nodes=0x555a073c0898, userid=69369) at /home/sven/projects/timescaledb/tsl/src/remote/dist_copy.c:265
#11 0x00007fd3b58fbbf0 in get_connections_for_chunk (context=0x555a06f031c0, chunk_id=65583, chunk_data_nodes=0x555a073c0898, userid=69369) at /home/sven/projects/timescaledb/tsl/src/remote/dist_copy.c:325
#12 0x00007fd3b58fdd29 in remote_copy_send_slot (context=0x555a06f031c0, slot=0x555a06e254c8, cis=0x555a06ddfaf0) at /home/sven/projects/timescaledb/tsl/src/remote/dist_copy.c:943
#13 0x00007fd3b58dfc70 in data_node_copy_exec (node=0x555a072d5c10) at /home/sven/projects/timescaledb/tsl/src/nodes/data_node_copy.c:201
#14 0x0000555a04c0b4d0 in ExecCustomScan (pstate=0x555a072d5c10) at nodeCustom.c:115
#15 0x0000555a04bec7f7 in ExecProcNodeFirst (node=0x555a072d5c10) at execProcnode.c:463
#16 0x00007fd3b59d485c in ExecProcNode (node=0x555a072d5c10) at /usr/local/pg14_stable/include/postgresql/server/executor/executor.h:257
#17 0x00007fd3b59d5dd3 in ExecModifyTable (pstate=0x555a072d54b8) at /home/sven/projects/timescaledb/src/nodes/hypertable_insert.c:657
#18 0x00007fd3b59d4fe7 in hypertable_insert_exec (node=0x555a072d4fd0) at /home/sven/projects/timescaledb/src/nodes/hypertable_insert.c:161
#19 0x0000555a04c0b4d0 in ExecCustomScan (pstate=0x555a072d4fd0) at nodeCustom.c:115
#20 0x0000555a04bec7f7 in ExecProcNodeFirst (node=0x555a072d4fd0) at execProcnode.c:463
#21 0x0000555a04be0427 in ExecProcNode (node=0x555a072d4fd0) at ../../../src/include/executor/executor.h:257
#22 0x0000555a04be2fe7 in ExecutePlan (estate=0x555a06f181b0, planstate=0x555a072d4fd0, use_parallel_mode=false, operation=CMD_INSERT, sendTuples=false, numberTuples=0, direction=ForwardScanDirection, dest=0x555a06e972d8,
    execute_once=true) at execMain.c:1551
#23 0x0000555a04be0b4e in standard_ExecutorRun (queryDesc=0x555a071b95a0, direction=ForwardScanDirection, count=0, execute_once=true) at execMain.c:361
#24 0x0000555a04be093d in ExecutorRun (queryDesc=0x555a071b95a0, direction=ForwardScanDirection, count=0, execute_once=true) at execMain.c:305
#25 0x0000555a04e5a8ed in ProcessQuery (plan=0x555a06e97240,
    sourceText=0x555a06c8eda0 "insert into public.metrics_dist values (\n(select time from public.dist_chunk_copy limit 1 offset 4)\n  , \n96, \n46, \ncase when (41 is not NULL) \n    or (EXISTS (\n      select  \n          ref_0.v0 as c0, \n          ref_0.v1 as c1, \n          ref_0.v3 as c2\n        from \n          public.metrics as ref_0\n        where false)) then 93 else 93 end\n  , \ncast(nullif(cast(null as float8),\n  cast(null as float8)) as float8), \ncast(null as float8))", params=0x0, queryEnv=0x0, dest=0x555a06e972d8, qc=0x7ffe930655e0) at pquery.c:160
#26 0x0000555a04e5c478 in PortalRunMulti (portal=0x555a06d10f50, isTopLevel=true, setHoldSnapshot=false, dest=0x555a06e972d8, altdest=0x555a06e972d8, qc=0x7ffe930655e0) at pquery.c:1274
#27 0x0000555a04e5b972 in PortalRun (portal=0x555a06d10f50, count=9223372036854775807, isTopLevel=true, run_once=true, dest=0x555a06e972d8, altdest=0x555a06e972d8, qc=0x7ffe930655e0) at pquery.c:788
#28 0x0000555a04e5488a in exec_simple_query (
    query_string=0x555a06c8eda0 "insert into public.metrics_dist values (\n(select time from public.dist_chunk_copy limit 1 offset 4)\n  , \n96, \n46, \ncase when (41 is not NULL) \n    or (EXISTS (\n      select  \n          ref_0.v0 as c0, \n          ref_0.v1 as c1, \n          ref_0.v3 as c2\n        from \n          public.metrics as ref_0\n        where false)) then 93 else 93 end\n  , \ncast(nullif(cast(null as float8),\n  cast(null as float8)) as float8), \ncast(null as float8))") at postgres.c:1214
#29 0x0000555a04e596e5 in PostgresMain (argc=1, argv=0x7ffe93065800, dbname=0x555a06cd51c8 "smith", username=0x555a06cd51a8 "sven") at postgres.c:4486
#30 0x0000555a04d7ffff in BackendRun (port=0x555a06cb8e80) at postmaster.c:4530
#31 0x0000555a04d7f866 in BackendStartup (port=0x555a06cb8e80) at postmaster.c:4252
#32 0x0000555a04d7b5ef in ServerLoop () at postmaster.c:1745
#33 0x0000555a04d7ad64 in PostmasterMain (argc=3, argv=0x555a06c88650) at postmaster.c:1417
#34 0x0000555a04c6c989 in main (argc=3, argv=0x555a06c88650) at main.c:209
```

### Query triggering the bug

```bash
insert into public.metrics_dist values (
(select time from public.dist_chunk_copy limit 1 offset 4)
  ,
96,
46,
case when (41 is not NULL)
    or (EXISTS (
      select
          ref_0.v0 as c0,
          ref_0.v1 as c1,
          ref_0.v3 as c2
        from
          public.metrics as ref_0
        where false)) then 93 else 93 end
  ,
cast(nullif(cast(null as float8),
  cast(null as float8)) as float8),
cast(null as float8))
```

**Comment by svenklemm** [comment]
Fixed by #3948
