### ISSUE TITLE
[Bug]: cursor fetcher malloc segfault

### ISSUE THREAD

**Issue by svenklemm** [timescale/timescaledb#3967]
### TimescaleDB version affected

master (0dd4329)

### PostgreSQL version used

14.1

### What operating system did you use?

Archlinux 2021.12.01 x64

### What installation method did you use?

Source

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
#0  0x00007fd3bedf8449 in malloc () from /usr/lib/libc.so.6
#1  0x00007fd3b581e9a0 in PQmakeEmptyPGresult (conn=0x555a06d8ab30, status=PGRES_COMMAND_OK) at fe-exec.c:150
#2  0x00007fd3b582a15e in pqParseInput3 (conn=0x555a06d8ab30) at fe-protocol3.c:214
#3  0x00007fd3b5821a24 in parseInput (conn=0x555a06d8ab30) at fe-exec.c:1942
#4  0x00007fd3b5821a4d in PQisBusy (conn=0x555a06d8ab30) at fe-exec.c:1957
#5  0x00007fd3b58f1006 in get_single_response_nonblocking (set=0x7ffe93064350) at /home/sven/projects/timescaledb/tsl/src/remote/async.c:632
#6  0x00007fd3b58f1447 in async_request_set_wait_any_response_deadline (set=0x7ffe93064350, endtime=-9223372036854775808) at /home/sven/projects/timescaledb/tsl/src/remote/async.c:762
#7  0x00007fd3b58f15cd in async_request_set_wait_any_result (set=0x7ffe93064350) at /home/sven/projects/timescaledb/tsl/src/remote/async.c:815
#8  0x00007fd3b58f0a3c in async_request_wait_any_result (req=0x555a06de2f20) at /home/sven/projects/timescaledb/tsl/src/remote/async.c:462
#9  0x00007fd3b58f0ded in async_request_wait_ok_command (req=0x555a06de2f20) at /home/sven/projects/timescaledb/tsl/src/remote/async.c:570
#10 0x00007fd3b58f70d2 in cursor_fetcher_wait_until_open (df=0x555a06ee1b38) at /home/sven/projects/timescaledb/tsl/src/remote/cursor_fetcher.c:127
#11 0x00007fd3b58f71ac in remote_cursor_init_with_params (conn=0x555a06d832f0, rel=0x7fd3b576d278, tupdesc=0x7fd3b576d5a8, ss=0x555a06e106a8, retrieved_attrs=0x555a070b9ec8,
    stmt=0x555a070b9a90 "SELECT device FROM public.dist_chunk_copy WHERE _timescaledb_internal.chunks_in(public.dist_chunk_copy.*, ARRAY[16, 18]) AND ((device IS NOT NULL)) ORDER BY device DESC NULLS FIRST LIMIT 1", params=0x0)
    at /home/sven/projects/timescaledb/tsl/src/remote/cursor_fetcher.c:147
#12 0x00007fd3b58f7304 in cursor_fetcher_create_for_scan (conn=0x555a06d832f0, ss=0x555a06e106a8, retrieved_attrs=0x555a070b9ec8,
    stmt=0x555a070b9a90 "SELECT device FROM public.dist_chunk_copy WHERE _timescaledb_internal.chunks_in(public.dist_chunk_copy.*, ARRAY[16, 18]) AND ((device IS NOT NULL)) ORDER BY device DESC NULLS FIRST LIMIT 1", params=0x0)
    at /home/sven/projects/timescaledb/tsl/src/remote/cursor_fetcher.c:196
#13 0x00007fd3b58d14f5 in create_data_fetcher (ss=0x555a06e106a8, fsstate=0x555a06e107c0) at /home/sven/projects/timescaledb/tsl/src/fdw/scan_exec.c:133
#14 0x00007fd3b58db724 in create_fetcher (ass=0x555a06e106a8) at /home/sven/projects/timescaledb/tsl/src/fdw/data_node_scan_exec.c:145
#15 0x00007fd3b58dbf9b in init (ass=0x555a06e106a8) at /home/sven/projects/timescaledb/tsl/src/nodes/async_append.c:236
#16 0x00007fd3b58dbf27 in iterate_data_nodes_and_exec (aas=0x555a06d5ba38, dn_exec=0x7fd3b58dbf7b <init>) at /home/sven/projects/timescaledb/tsl/src/nodes/async_append.c:229
#17 0x00007fd3b58dc0a7 in async_append_exec (node=0x555a06d5ba38) at /home/sven/projects/timescaledb/tsl/src/nodes/async_append.c:264
#18 0x0000555a04c0b4d0 in ExecCustomScan (pstate=0x555a06d5ba38) at nodeCustom.c:115
#19 0x0000555a04bec7f7 in ExecProcNodeFirst (node=0x555a06d5ba38) at execProcnode.c:463
#20 0x0000555a04c2013f in ExecProcNode (node=0x555a06d5ba38) at ../../../src/include/executor/executor.h:257
#21 0x0000555a04c203a4 in ExecLimit (pstate=0x555a06d5b788) at nodeLimit.c:96
#22 0x0000555a04bec7f7 in ExecProcNodeFirst (node=0x555a06d5b788) at execProcnode.c:463
#23 0x0000555a04c347b8 in ExecProcNode (node=0x555a06d5b788) at ../../../src/include/executor/executor.h:257
#24 0x0000555a04c36ee4 in ExecSetParamPlan (node=0x555a06edbec8, econtext=0x555a06edb3d0) at nodeSubplan.c:1118
#25 0x0000555a04bd7585 in ExecEvalParamExec (state=0x555a06edb620, op=0x555a06edb6b0, econtext=0x555a06edb3d0) at execExprInterp.c:2414
#26 0x0000555a04bd4a42 in ExecInterpExpr (state=0x555a06edb620, econtext=0x555a06edb3d0, isnull=0x7ffe93064a9f) at execExprInterp.c:1062
#27 0x0000555a04bd64cc in ExecInterpExprStillValid (state=0x555a06edb620, econtext=0x555a06edb3d0, isNull=0x7ffe93064a9f) at execExprInterp.c:1824
#28 0x0000555a04c31102 in ExecEvalExprSwitchContext (state=0x555a06edb620, econtext=0x555a06edb3d0, isNull=0x7ffe93064a9f) at ../../../src/include/executor/executor.h:339
#29 0x0000555a04c3117a in ExecProject (projInfo=0x555a06edb618) at ../../../src/include/executor/executor.h:373
#30 0x0000555a04c313c0 in ExecResult (pstate=0x555a06edb2b8) at nodeResult.c:136
#31 0x0000555a04bec7f7 in ExecProcNodeFirst (node=0x555a06edb2b8) at execProcnode.c:463
#32 0x0000555a04c347b8 in ExecProcNode (node=0x555a06edb2b8) at ../../../src/include/executor/executor.h:257
#33 0x0000555a04c36ee4 in ExecSetParamPlan (node=0x555a06ee1a20, econtext=0x555a06edfb40) at nodeSubplan.c:1118
#34 0x0000555a04bd7585 in ExecEvalParamExec (state=0x555a06edfcf8, op=0x555a06ee0ac8, econtext=0x555a06edfb40) at execExprInterp.c:2414
#35 0x0000555a04bd4a42 in ExecInterpExpr (state=0x555a06edfcf8, econtext=0x555a06edfb40, isnull=0x7ffe93064f3f) at execExprInterp.c:1062
#36 0x0000555a04bd64cc in ExecInterpExprStillValid (state=0x555a06edfcf8, econtext=0x555a06edfb40, isNull=0x7ffe93064f3f) at execExprInterp.c:1824
#37 0x0000555a04c31102 in ExecEvalExprSwitchContext (state=0x555a06edfcf8, econtext=0x555a06edfb40, isNull=0x7ffe93064f3f) at ../../../src/include/executor/executor.h:339
#38 0x0000555a04c3117a in ExecProject (projInfo=0x555a06edfcf0) at ../../../src/include/executor/executor.h:373
#39 0x0000555a04c313c0 in ExecResult (pstate=0x555a06edfa28) at nodeResult.c:136
#40 0x0000555a04bec7f7 in ExecProcNodeFirst (node=0x555a06edfa28) at execProcnode.c:463
#41 0x00007fd3b59d21e3 in ExecProcNode (node=0x555a06edfa28) at /usr/local/pg14_stable/include/postgresql/server/executor/executor.h:257
#42 0x00007fd3b59d2353 in chunk_dispatch_exec (node=0x555a06edcc50) at /home/sven/projects/timescaledb/src/nodes/chunk_dispatch_state.c:78
#43 0x0000555a04c0b4d0 in ExecCustomScan (pstate=0x555a06edcc50) at nodeCustom.c:115
#44 0x0000555a04bec7f7 in ExecProcNodeFirst (node=0x555a06edcc50) at execProcnode.c:463
#45 0x00007fd3b59d485c in ExecProcNode (node=0x555a06edcc50) at /usr/local/pg14_stable/include/postgresql/server/executor/executor.h:257
#46 0x00007fd3b59d5dd3 in ExecModifyTable (pstate=0x555a06edc3f8) at /home/sven/projects/timescaledb/src/nodes/hypertable_insert.c:657
#47 0x00007fd3b59d4fe7 in hypertable_insert_exec (node=0x555a06edbfe0) at /home/sven/projects/timescaledb/src/nodes/hypertable_insert.c:161
#48 0x0000555a04c0b4d0 in ExecCustomScan (pstate=0x555a06edbfe0) at nodeCustom.c:115
#49 0x0000555a04bec7f7 in ExecProcNodeFirst (node=0x555a06edbfe0) at execProcnode.c:463
#50 0x0000555a04be0427 in ExecProcNode (node=0x555a06edbfe0) at ../../../src/include/executor/executor.h:257
#51 0x0000555a04be2fe7 in ExecutePlan (estate=0x555a06d59e80, planstate=0x555a06edbfe0, use_parallel_mode=false, operation=CMD_INSERT, sendTuples=false, numberTuples=0, direction=ForwardScanDirection, dest=0x555a070c06c0,
    execute_once=true) at execMain.c:1551
#52 0x0000555a04be0b4e in standard_ExecutorRun (queryDesc=0x555a070609a0, direction=ForwardScanDirection, count=0, execute_once=true) at execMain.c:361
#53 0x0000555a04be093d in ExecutorRun (queryDesc=0x555a070609a0, direction=ForwardScanDirection, count=0, execute_once=true) at execMain.c:305
#54 0x0000555a04e5a8ed in ProcessQuery (plan=0x555a070bf168,
    sourceText=0x555a06c8eda0 "insert into public.metrics values (\ncase when EXISTS (\n    select  \n        ref_0.value as c0, \n        ref_0.time as c1, \n        70 as c2\n      from \n        public.conditions as ref_0\n      where ref_0.value > pg_catalog.float4mi(\n          cast(cast(null as float4) as float4),\n          cast(cast(null as float4) as float4))\n      limit 92) then cast(null as timestamptz) else cast(null as timestamptz) end\n  , \n31, \n(select pg_catalog.max(device) from public.dist_chunk_copy)\n  , \ncast(coalesce(55,\n  70) as int4), \ncast(null as float8), \ndefault)", params=0x0, queryEnv=0x0, dest=0x555a070c06c0, qc=0x7ffe930655e0) at pquery.c:160
#55 0x0000555a04e5c478 in PortalRunMulti (portal=0x555a06d00f40, isTopLevel=true, setHoldSnapshot=false, dest=0x555a070c06c0, altdest=0x555a070c06c0, qc=0x7ffe930655e0) at pquery.c:1274
#56 0x0000555a04e5b972 in PortalRun (portal=0x555a06d00f40, count=9223372036854775807, isTopLevel=true, run_once=true, dest=0x555a070c06c0, altdest=0x555a070c06c0, qc=0x7ffe930655e0) at pquery.c:788
#57 0x0000555a04e5488a in exec_simple_query (
    query_string=0x555a06c8eda0 "insert into public.metrics values (\ncase when EXISTS (\n    select  \n        ref_0.value as c0, \n        ref_0.time as c1, \n        70 as c2\n      from \n        public.conditions as ref_0\n      where ref_0.value > pg_catalog.float4mi(\n          cast(cast(null as float4) as float4),\n          cast(cast(null as float4) as float4))\n      limit 92) then cast(null as timestamptz) else cast(null as timestamptz) end\n  , \n31, \n(select pg_catalog.max(device) from public.dist_chunk_copy)\n  , \ncast(coalesce(55,\n  70) as int4), \ncast(null as float8), \ndefault)") at postgres.c:1214
#58 0x0000555a04e596e5 in PostgresMain (argc=1, argv=0x7ffe93065800, dbname=0x555a06cc1330 "smith", username=0x555a06cc1310 "sven") at postgres.c:4486
#59 0x0000555a04d7ffff in BackendRun (port=0x555a06cb8e80) at postmaster.c:4530
#60 0x0000555a04d7f866 in BackendStartup (port=0x555a06cb8e80) at postmaster.c:4252
#61 0x0000555a04d7b5ef in ServerLoop () at postmaster.c:1745
#62 0x0000555a04d7ad64 in PostmasterMain (argc=3, argv=0x555a06c88650) at postmaster.c:1417
```

### Query triggering the bug

```bash
insert into public.metrics values (
case when EXISTS (
    select
        ref_0.value as c0,
        ref_0.time as c1,
        70 as c2
      from
        public.conditions as ref_0
      where ref_0.value > pg_catalog.float4mi(
          cast(cast(null as float4) as float4),
          cast(cast(null as float4) as float4))
      limit 92) then cast(null as timestamptz) else cast(null as timestamptz) end
  ,
31,
(select pg_catalog.max(device) from public.dist_chunk_copy)
  ,
cast(coalesce(55,
  70) as int4),
cast(null as float8),
default)
```

**Comment by svenklemm** [comment]
Fixed by #3948
