### ISSUE TITLE
[Bug]: Segfault in ts_tablespace_attach

### ISSUE THREAD

**Issue by mfundul** [timescale/timescaledb#4366]
### What type of bug is this?

Crash

### What subsystems and features are affected?

Other

### What happened?

In PostgreSQL version 12.0, but not the latest versions, `ts_tablespace_attach()` can crash the server.

### TimescaleDB version affected

2.6.1

### PostgreSQL version used

12.0

### What operating system did you use?

Ubuntu 20.04 x64

### What installation method did you use?

Source

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
=================================================================
==postgres==61585==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000010 (pc 0x562e44d668cb bp 0x7ffc85063b70 sp 0x7ffc85063b60 T0)
==postgres==61585==The signal is caused by a WRITE memory access.
==postgres==61585==Hint: address points to the zero page.
    #0 0x562e44d668ca in EventTriggerAlterTableRelid /home/mfundul/Development/timescale/postgresql-12.0/src/backend/commands/event_trigger.c:1749
    #1 0x562e44e10277 in AlterTableInternal /home/mfundul/Development/timescale/postgresql-12.0/src/backend/commands/tablecmds.c:3528
    #2 0x7f7f89f4f0c8 in ts_tablespace_attach /home/mfundul/Development/timescale/timescaledb/src/ts_catalog/tablespace.c:506
    #3 0x562e44f0cbdf in ExecMakeTableFunctionResult /home/mfundul/Development/timescale/postgresql-12.0/src/backend/executor/execSRF.c:233
    #4 0x562e44f4b849 in FunctionNext /home/mfundul/Development/timescale/postgresql-12.0/src/backend/executor/nodeFunctionscan.c:95
    #5 0x562e44f0af55 in ExecScanFetch /home/mfundul/Development/timescale/postgresql-12.0/src/backend/executor/execScan.c:133
    #6 0x562e44f0b0b5 in ExecScan /home/mfundul/Development/timescale/postgresql-12.0/src/backend/executor/execScan.c:200
    #7 0x562e44f4c2cb in ExecFunctionScan /home/mfundul/Development/timescale/postgresql-12.0/src/backend/executor/nodeFunctionscan.c:270
    #8 0x562e44f05dd5 in ExecProcNodeFirst /home/mfundul/Development/timescale/postgresql-12.0/src/backend/executor/execProcnode.c:445
    #9 0x562e44ee7b85 in ExecProcNode ../../../src/include/executor/executor.h:239
    #10 0x562e44eedc45 in ExecutePlan /home/mfundul/Development/timescale/postgresql-12.0/src/backend/executor/execMain.c:1646
    #11 0x562e44ee8c97 in standard_ExecutorRun /home/mfundul/Development/timescale/postgresql-12.0/src/backend/executor/execMain.c:364
    #12 0x562e44ee87f9 in ExecutorRun /home/mfundul/Development/timescale/postgresql-12.0/src/backend/executor/execMain.c:308
    #13 0x562e44d4d6ec in ExecCreateTableAs /home/mfundul/Development/timescale/postgresql-12.0/src/backend/commands/createas.c:354
    #14 0x562e4546b860 in ProcessUtilitySlow /home/mfundul/Development/timescale/postgresql-12.0/src/backend/tcop/utility.c:1498
    #15 0x562e45468bfc in standard_ProcessUtility /home/mfundul/Development/timescale/postgresql-12.0/src/backend/tcop/utility.c:927
    #16 0x7f7f93822c17 in loader_process_utility_hook /home/mfundul/Development/timescale/timescaledb/src/loader/loader.c:577
    #17 0x7f7f89ef0860 in prev_ProcessUtility /home/mfundul/Development/timescale/timescaledb/src/process_utility.c:90
    #18 0x7f7f89f02796 in timescaledb_ddl_command_start /home/mfundul/Development/timescale/timescaledb/src/process_utility.c:4296
    #19 0x562e45466e62 in ProcessUtility /home/mfundul/Development/timescale/postgresql-12.0/src/backend/tcop/utility.c:356
    #20 0x562e45464bc8 in PortalRunUtility /home/mfundul/Development/timescale/postgresql-12.0/src/backend/tcop/pquery.c:1175
    #21 0x562e4546515a in PortalRunMulti /home/mfundul/Development/timescale/postgresql-12.0/src/backend/tcop/pquery.c:1321
    #22 0x562e454635af in PortalRun /home/mfundul/Development/timescale/postgresql-12.0/src/backend/tcop/pquery.c:796
    #23 0x562e4545542d in exec_simple_query /home/mfundul/Development/timescale/postgresql-12.0/src/backend/tcop/postgres.c:1215
    #24 0x562e4545e8e1 in PostgresMain /home/mfundul/Development/timescale/postgresql-12.0/src/backend/tcop/postgres.c:4236
    #25 0x562e45293945 in BackendRun /home/mfundul/Development/timescale/postgresql-12.0/src/backend/postmaster/postmaster.c:4431
    #26 0x562e452925a3 in BackendStartup /home/mfundul/Development/timescale/postgresql-12.0/src/backend/postmaster/postmaster.c:4122
    #27 0x562e4528b0d9 in ServerLoop /home/mfundul/Development/timescale/postgresql-12.0/src/backend/postmaster/postmaster.c:1704
    #28 0x562e45289cbd in PostmasterMain /home/mfundul/Development/timescale/postgresql-12.0/src/backend/postmaster/postmaster.c:1377
    #29 0x562e45020e01 in main /home/mfundul/Development/timescale/postgresql-12.0/src/backend/main/main.c:228
    #30 0x7f7f96457082 in __libc_start_main ../csu/libc-start.c:308
    #31 0x562e447413bd in _start (/usr/local/pgsql/postgresql-12.0/bin/postgres+0x36c3bd)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/mfundul/Development/timescale/postgresql-12.0/src/backend/commands/event_trigger.c:1749 in EventTriggerAlterTableRelid
==postgres==61585==ABORTING
```

### How can we reproduce the bug?

```bash
1. git checkout 2.6.1
2. Build and install timescaledb against PostgreSQL 12.0
3. git checkout 8c5c7bb4ad6eff5a8c650447c5e7b625389ad40f test/sql/tablespace.sql
4. make installcheck TESTS="tablespace"
```

**Comment by svenklemm** [comment]
Seems to be upstream bug that got fixed in 12.5
