### ISSUE TITLE
[Bug]: transparent decompression error on updating uncompressed chunck

### ISSUE THREAD

**Issue by sitrsn** [timescale/timescaledb#4680]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Access node, Compression, Distributed hypertable

### What happened?

Hi,
We have a hypertable distibuted in 3 postgre server, 1 acess node and 2 nodes.
We setted a weekly compression policy for values older then 3 month.

Application written in c# .net 6.0, using nuget package Npgsql 6.0.3 for data access

Sometimes (often but not always) application breaks while updating a row in an uncompressed chunk.

Npgsql.PostgresException (0x80004005): XX000: [data_node_2]: transparent decompression only supports tableoid system column
   at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|211_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.<ReadMessage>g__ReadMessageSequential|44_0(NpgsqlConnector connector, Boolean async)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteScalar(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteScalar()

i did step by step debugging, to get the values of the query causing the issue

BUT when i replay the query manually in pgAdmin4 i do not reproduce the issue and get : 
UPDATE 1
Query returned successfully in 503 msec.

I am out of idea, hope you can give me some clue/advice

### TimescaleDB version affected

2.5.1

### PostgreSQL version used

12.12

### What operating system did you use?

Win10 

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
CREATE TABLE ABC.itemtx(tx_id integer,item_type smallint,item_stamp timestamp without time zone,value numeric (20,6))
SELECT create_hypertable('ABC.itemtx', 'item_stamp')
CREATE UNIQUE INDEX  ABC_itemtx_IDX ON ABC.itemtx(tx_id, item_type, item_stamp)

sample insert command : 
INSERT INTO ABC.itemtx(tx_id, item_type, item_stamp, value)
	VALUES (123, 2, '2022-09-08T06:59:37+00:00', 10100);

sample update command : 
UPDATE ABC.itemtx
	SET  value=0
	WHERE tx_id=123 and  item_type=2 and  item_stamp='2022-09-08T06:59:37+00:00'
```

**Comment by svenklemm** [comment]
This works for me on latest version.
