### ISSUE TITLE
[Bug]: Assertion hit in add_baserel_cache_entry_for_chunk

### ISSUE THREAD

**Issue by jnidzwetzki** [timescale/timescaledb#4708]
### What type of bug is this?

Crash

### What subsystems and features are affected?

Query planner

### What happened?

SQLSmith found the following assertion hit when running with seed `11872767`.

```
[...]
#2  0x000055edd1a3c53c in ExceptionalCondition (conditionName=0x7f16f8ddd02d "entry->type == chunk_reltype", 
    errorType=0x7f16f8ddcc47 "FailedAssertion", fileName=0x7f16f8ddcfa8 "/home/jan/timescaledb/src/planner/planner.c", lineNumber=176)
    at assert.c:69
[...]

(gdb) frame 3
#3  0x00007f16f8da8baf in add_baserel_cache_entry_for_chunk (chunk_reloid=20516, chunk_status=1, hypertable=0x55edd29171a8, 
    chunk_reltype=TS_REL_CHUNK_CHILD) at /home/jan/timescaledb/src/planner/planner.c:176
176			Assert(entry->type == chunk_reltype);
(gdb) print entry->type
$1 = TS_REL_CHUNK
(gdb) print chunk_reltype
$2 = TS_REL_CHUNK_CHILD
````

### TimescaleDB version affected

2.8.0  and 2.9.0-dev (424f6f7648e88907b9373ef44ec851787db21080)

### PostgreSQL version used

14.2

### What operating system did you use?

Debian 11

### What installation method did you use?

Source

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

Tested with TimescaleDB 2.8.0

```bash
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f170444b537 in __GI_abort () at abort.c:79
#2  0x000055edd1a3c53c in ExceptionalCondition (conditionName=0x7f16f8ddd02d "entry->type == chunk_reltype", 
    errorType=0x7f16f8ddcc47 "FailedAssertion", fileName=0x7f16f8ddcfa8 "/home/jan/timescaledb/src/planner/planner.c", lineNumber=176)
    at assert.c:69
#3  0x00007f16f8da8baf in add_baserel_cache_entry_for_chunk (chunk_reloid=20516, chunk_status=1, hypertable=0x55edd29171a8, 
    chunk_reltype=TS_REL_CHUNK_CHILD) at /home/jan/timescaledb/src/planner/planner.c:176
#4  0x00007f16f8db1a36 in ts_plan_expand_hypertable_chunks (ht=0x55edd29171a8, root=0x55edd29ada38, rel=0x55edd2b671c0)
    at /home/jan/timescaledb/src/planner/expand_hypertable.c:1358
#5  0x00007f16f8daa14f in reenable_inheritance (root=0x55edd29ada38, rel=0x55edd2b68448, rti=3, rte=0x55edd29ab8b8)
    at /home/jan/timescaledb/src/planner/planner.c:941
#6  0x00007f16f8daa9b7 in timescaledb_set_rel_pathlist (root=0x55edd29ada38, rel=0x55edd2b68448, rti=3, rte=0x55edd29ab8b8)
    at /home/jan/timescaledb/src/planner/planner.c:1164
#7  0x000055edd1723a15 in set_rel_pathlist (root=0x55edd29ada38, rel=0x55edd2b68448, rti=3, rte=0x55edd29ab8b8) at allpaths.c:541
#8  0x000055edd172359b in set_base_rel_pathlists (root=0x55edd29ada38) at allpaths.c:353
#9  0x000055edd17232e9 in make_one_rel (root=0x55edd29ada38, joinlist=0x55edd2b6b310) at allpaths.c:223
#10 0x000055edd17603f9 in query_planner (root=0x55edd29ada38, qp_callback=0x55edd176601f <standard_qp_callback>, qp_extra=0x7ffdb2f2d280)
    at planmain.c:276
#11 0x000055edd1762b60 in grouping_planner (root=0x55edd29ada38, tuple_fraction=56) at planner.c:1442
#12 0x000055edd1762230 in subquery_planner (glob=0x55edd29ab508, parse=0x55edd2899f08, parent_root=0x0, hasRecursion=false, 
    tuple_fraction=0) at planner.c:1019
#13 0x000055edd1760a47 in standard_planner (parse=0x55edd2899f08, 
    query_string=0x55edd2720a90 "select  \n  pg_catalog.pg_my_temp_schema() as c0, \n  subq_0.c0 as c1, \n  subq_0.c0 as c2, \n  subq_0.c1 as c3, \n  subq_0.c2 as c4, \n  case when EXISTS (\n      select  \n          subq_0.c1 as c0, \n      "..., cursorOptions=2048, 
    boundParams=0x0) at planner.c:400
#14 0x00007f16f8da95d9 in timescaledb_planner (parse=0x55edd2899f08, 
    query_string=0x55edd2720a90 "select  \n  pg_catalog.pg_my_temp_schema() as c0, \n  subq_0.c0 as c1, \n  subq_0.c0 as c2, \n  subq_0.c1 as c3, \n  subq_0.c2 as c4, \n  case when EXISTS (\n      select  \n          subq_0.c1 as c0, \n      "..., cursor_opts=2048, 
    bound_params=0x0) at /home/jan/timescaledb/src/planner/planner.c:578
#15 0x000055edd17607dd in planner (parse=0x55edd2899f08, 
    query_string=0x55edd2720a90 "select  \n  pg_catalog.pg_my_temp_schema() as c0, \n  subq_0.c0 as c1, \n  subq_0.c0 as c2, \n  subq_0.c1 as c3, \n  subq_0.c2 as c4, \n  case when EXISTS (\n      select  \n          subq_0.c1 as c0, \n      "..., cursorOptions=2048, 
    boundParams=0x0) at planner.c:269
#16 0x000055edd18992e1 in pg_plan_query (querytree=0x55edd2899f08, 
    query_string=0x55edd2720a90 "select  \n  pg_catalog.pg_my_temp_schema() as c0, \n  subq_0.c0 as c1, \n  subq_0.c0 as c2, \n  subq_0.c1 as c3, \n  subq_0.c2 as c4, \n  case when EXISTS (\n      select  \n          subq_0.c1 as c0, \n      "..., cursorOptions=2048, 
    boundParams=0x0) at postgres.c:847
#17 0x000055edd189942b in pg_plan_queries (querytrees=0x55edd29a9068, 
    query_string=0x55edd2720a90 "select  \n  pg_catalog.pg_my_temp_schema() as c0, \n  subq_0.c0 as c1, \n  subq_0.c0 as c2, \n  subq_0.c1 as c3, \n  subq_0.c2 as c4, \n  case when EXISTS (\n      select  \n          subq_0.c1 as c0, \n      "..., cursorOptions=2048, 
    boundParams=0x0) at postgres.c:939
#18 0x000055edd189979c in exec_simple_query (
    query_string=0x55edd2720a90 "select  \n  pg_catalog.pg_my_temp_schema() as c0, \n  subq_0.c0 as c1, \n  subq_0.c0 as c2, \n  subq_0.c1 as c3, \n  subq_0.c2 as c4, \n  case when EXISTS (\n      select  \n          subq_0.c1 as c0, \n      "...) at postgres.c:1133
#19 0x000055edd189e126 in PostgresMain (argc=1, argv=0x7ffdb2f2de50, dbname=0x55edd2751cb0 "test2", username=0x55edd2751c90 "jan")
    at postgres.c:4486
#20 0x000055edd17d4c6d in BackendRun (port=0x55edd27489b0) at postmaster.c:4530
#21 0x000055edd17d459f in BackendStartup (port=0x55edd27489b0) at postmaster.c:4252
#22 0x000055edd17d0781 in ServerLoop () at postmaster.c:1745
#23 0x000055edd17cffce in PostmasterMain (argc=3, argv=0x55edd27199f0) at postmaster.c:1417
#24 0x000055edd16cdcce in main (argc=3, argv=0x55edd27199f0) at main.c:209
```

### How can we reproduce the bug?

```bash
\i [...]/tsl/test/shared/sql/include/shared_setup.sql

select  
  pg_catalog.pg_my_temp_schema() as c0, 
  subq_0.c0 as c1, 
  subq_0.c0 as c2, 
  subq_0.c1 as c3, 
  subq_0.c2 as c4, 
  case when EXISTS (
      select  
          subq_0.c1 as c0, 
          ref_1.v2 as c1
        from 
          public.metrics_space as ref_1
        where case when (select hypertable_schema from timescaledb_information.dimensions limit 1 offset 6)
                 <> (select hypertable_schema from timescaledb_information.compression_settings limit 1 offset 4)
                 then cast(null as money) else cast(null as money) end
             = pg_catalog.flt8_mul_cash(
            cast(ref_1.v2 as float8),
            cast(cast(null as money) as money))
        limit 49) then 97 else 97 end
     as c5
from 
  (select  
        sample_2.materialization_id as c0, 
        sample_0.block_chunks as c1, 
        sample_2.materialization_id as c2
      from 
        _timescaledb_catalog.hypertable_data_node as sample_0 tablesample system (6.1) 
          inner join _timescaledb_internal._hyper_3_13_chunk as ref_0
              right join public.metrics_compressed as sample_1 tablesample bernoulli (7.6) 
              on (false)
            inner join _timescaledb_catalog.continuous_aggs_materialization_invalidation_log as sample_2 tablesample system (3.2) 
            on (cast(null as point) <@ cast(null as box))
          on (sample_0.node_hypertable_id is NULL)
      where (select num_dimensions from timescaledb_information.hypertables limit 1 offset 1)
           > sample_0.node_hypertable_id) as subq_0
where pg_catalog.timeofday() ~>~ cast(null as text)
limit 56;
```

**Comment by svenklemm** [comment]
Hmm this seems to be misconception in the cache setup. We use the relid as cache key but a chunk can appear multiple times in  a plan in different contexts.
