### ISSUE TITLE
[Bug] Failed assertion: !(prev_first_lsn < cur_txn->first_lsn)

### ISSUE THREAD

**Issue by akuzm** [timescale/timescaledb#4869]
Saw it in the tests https://github.com/timescale/timescaledb/actions/runs/3298142386/jobs/5439872915

```

Core was generated by `postgres: walsender cluster_super_user ::1(39476) idle                        '.
Program terminated with signal SIGABRT, Aborted.
#0  __pthread_kill_implementation (no_tid=0, signo=6, 
    threadid=139782623379968) at ./nptl/pthread_kill.c:44
(gdb) START_REPLICATION SLOT "ts_copy_1_1_202294_sync_195048" LOGICAL 0/5C45A9B8 (proto_version '1', publication_names '"ts_copy_1_1"')

(gdb) #0  __pthread_kill_implementation (no_tid=0, signo=6, 
    threadid=139782623379968) at ./nptl/pthread_kill.c:44
        tid = <optimized out>
        ret = 0
        pd = 0x7f21ad9cc200
        old_mask = {__val = {0, 0, 5, 5, 139782623379840, 139782627464295, 0, 
            18405958705985703168, 16712, 139782627518285, 94892604321731, 0, 
            140736533436408, 76, 94892604043968, 139782627469663}}
        ret = <optimized out>
        pd = <optimized out>
        old_mask = <optimized out>
        ret = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
        resultvar = <optimized out>
        resultvar = <optimized out>
        __arg3 = <optimized out>
        __arg2 = <optimized out>
        __arg1 = <optimized out>
        _a3 = <optimized out>
        _a2 = <optimized out>
        _a1 = <optimized out>
        __futex = <optimized out>
        resultvar = <optimized out>
        __arg3 = <optimized out>
        __arg2 = <optimized out>
        __arg1 = <optimized out>
        _a3 = <optimized out>
        _a2 = <optimized out>
        _a1 = <optimized out>
        __futex = <optimized out>
        __private = <optimized out>
        __oldval = <optimized out>
        result = <optimized out>
#1  __pthread_kill_internal (signo=6, threadid=139782623379968)
    at ./nptl/pthread_kill.c:78
No locals.
#2  __GI___pthread_kill (threadid=139782623379968, signo=signo@entry=6)
    at ./nptl/pthread_kill.c:89
No locals.
#3  0x00007f21ada0f476 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/posix/raise.c:26
        ret = <optimized out>
#4  0x00007f21ad9f57f3 in __GI_abort () at ./stdlib/abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x7, sa_sigaction = 0x7}, 
          sa_mask = {__val = {94892594802717, 94892596275864, 94892596275076, 
              693, 94892596275076, 527, 8240, 128, 755914244609, 16, 
              94892594504626, 4294967296, 4, 140736533436684, 0, 
              139779710648320}}, sa_flags = -1380026720, 
          sa_restorer = 0x7f21adbe3600 <_IO_file_jumps>}
        sigs = {__val = {32, 139782625586400, 7, 4294967296, 459561500672, 
            139782625588896, 139782625572352, 139782623904298, 
            94892605446056, 0, 1396259400, 94892594451206, 206158430248, 
            140736533436640, 140736533436448, 18405958705985703168}}
#5  0x0000564de7623d6a in ExceptionalCondition (
    conditionName=conditionName@entry=0x564de77e2a98 "!(prev_first_lsn < cur_txn->first_lsn)", errorType=errorType@entry=0x564de767b01d "FailedAssertion", 
    fileName=fileName@entry=0x564de77e2784 "reorderbuffer.c", 
    lineNumber=lineNumber@entry=693) at assert.c:54
No locals.
#6  0x0000564de748c01a in AssertTXNLsnOrder (rb=rb@entry=0x564de80a17a8)
    at reorderbuffer.c:693
        cur_txn = <optimized out>
        iter = {cur = <optimized out>, end = 0x564de80a17b0}
        prev_first_lsn = <optimized out>
        prev_base_snap_lsn = 0
#7  0x0000564de748c899 in ReorderBufferTXNByXid (rb=rb@entry=0x564de80a17a8, 
    xid=<optimized out>, xid@entry=14152, create=create@entry=true, 
    is_new=is_new@entry=0x0, lsn=lsn@entry=1396259400, 
    create_as_top=create_as_top@entry=true) at reorderbuffer.c:572
        txn = 0x564de80c4620
        ent = 0x564de8096a70
        found = false
#8  0x0000564de7490ca5 in ReorderBufferAddNewTupleCids (rb=0x564de80a17a8, 
    xid=14152, lsn=lsn@entry=1396259400, node=..., tid=..., cmin=4294967295, 
    cmax=10, combocid=4294967295) at reorderbuffer.c:2120
        change = 0x564de80c6538
        txn = <optimized out>
#9  0x0000564de7492e98 in SnapBuildProcessNewCid (builder=0x564de8079af8, 
    xid=14153, lsn=1396259400, xlrec=0x564de80be580) at snapbuild.c:797
        cid = <optimized out>
        __func__ = "SnapBuildProcessNewCid"
#10 0x0000564de7483082 in DecodeHeap2Op (buf=0x7fffc71519a0, 
    ctx=<optimized out>) at decode.c:386
        xlrec = <optimized out>
        info = <optimized out>
        xid = <optimized out>
        builder = <optimized out>
        info = <optimized out>
        xid = <optimized out>
        builder = <optimized out>
        __func__ = "DecodeHeap2Op"
        xlrec = <optimized out>
        __errno_location = <optimized out>
#11 0x0000564de7498145 in XLogSendLogical () at walsender.c:2883
        record = <optimized out>
        errm = 0x0
        flushPtr = 1548097544
        __func__ = "XLogSendLogical"
#12 0x0000564de749aa08 in WalSndLoop (
    send_data=send_data@entry=0x564de74980e0 <XLogSendLogical>)
    at walsender.c:2232
        __func__ = "WalSndLoop"
#13 0x0000564de749b7a9 in StartLogicalReplication (cmd=0x564de7f7fa50)
    at walsender.c:1134
        buf = {data = 0x0, len = 3, maxlen = 1024, cursor = 87}
        buf = <optimized out>
        __func__ = "StartLogicalReplication"
        __errno_location = <optimized out>
#14 exec_replication_command (
    cmd_string=cmd_string@entry=0x564de7f03c88 "START_REPLICATION SLOT \"ts_copy_1_1_202294_sync_195048\" LOGICAL 0/5C45A9B8 (proto_version '1', publication_names '\"ts_copy_1_1\"')") at walsender.c:1602
        cmd = 0x564de7f7fa50
        parse_rc = <optimized out>
        cmd_node = 0x564de7f7fa50
        cmd_context = 0x564de7f7e9f0
        old_context = 0x564de7f03b70
        __func__ = "exec_replication_command"
#15 0x0000564de74f9803 in PostgresMain (argc=<optimized out>, 
    argv=argv@entry=0x564de7f84f60, dbname=<optimized out>, 
    username=<optimized out>) at postgres.c:4277
        query_string = 0x564de7f03c88 "START_REPLICATION SLOT \"ts_copy_1_1_202294_sync_195048\" LOGICAL 0/5C45A9B8 (proto_version '1', publication_names '\"ts_copy_1_1\"')"
        firstchar = <optimized out>
        input_message = {
          data = 0x564de7f03c88 "START_REPLICATION SLOT \"ts_copy_1_1_202294_sync_195048\" LOGICAL 0/5C45A9B8 (proto_version '1', publication_names '\"ts_copy_1_1\"')", len = 130, maxlen = 1024, cursor = 130}
        local_sigjmp_buf = {{__jmpbuf = {94892596249904, 3893797806256018775, 
              1, 94892604279736, 94892596248996, 94892596254696, 
              3893797806094538071, 7308722948649768279}, 
            __mask_was_saved = 1, __saved_mask = {__val = {0, 94892596249773, 
                0, 94892604279736, 94892596249773, 140736533438160, 
                94892594765271, 140736533448972, 140736533448922, 
                140736533454801, 0, 0, 914828034067, 0, 18405958705985703168, 
                94892604210320}}}}
        send_ready_for_query = false
        disable_idle_in_transaction_timeout = <optimized out>
        __func__ = "PostgresMain"
```

**Comment by akuzm** [comment]
https://github.com/timescale/timescaledb/actions/runs/3298313381/jobs/5440267136

**Comment by kgyrtkirk** [comment]
@akuzm unfortunately the run logs are not accessible anymore - do you remember the test name or something to run it again - and see if the problem persists?

The backtrace doesn't seem to be specific to tsdb - what do you think/remember/etc?

**Comment by akuzm** [comment]
No, I don't know more details. I don't see it in the CI logs anymore, so maybe we can close this.
```
ci_stats=> select count(*) from log where log_contents like '%first_lsn%';
 count 
───────
     0
```
