### ISSUE TITLE
Assertion failure in ts_hypertable_has_compression_table in CI

### ISSUE THREAD

**Issue by svenklemm** [timescale/timescaledb#5029]
Link to failed run: 
https://github.com/timescale/timescaledb/actions/runs/3551362759/jobs/5965472913

Looks like the cache entry in the baserel cache is pointing to an entry that is no longer valid

Stacktrace:
```
(gdb) bt full 10
#0  0x00007fb4e5960a7c in pthread_kill () from /home/sven/share/pg14/libc.so.6
No symbol table info available.
#1  0x00007fb4e590c476 in raise () from /home/sven/share/pg14/libc.so.6
No symbol table info available.
#2  0x00007fb4e58f27f3 in abort () from /home/sven/share/pg14/libc.so.6
No symbol table info available.
#3  0x00005591dd4fbf28 in ExceptionalCondition (conditionName=<optimized out>, errorType=<optimized out>, fileName=<optimized out>, lineNumber=<optimized out>) at assert.c:69
No locals.
#4  0x00007fb4dbaf4dab in ts_hypertable_has_compression_table (ht=0x5591df3fc178) at /home/runner/work/timescaledb/timescaledb/src/hypertable.c:2943
No locals.
#5  0x00007fb4dbb79fef in timescaledb_get_relation_info_hook (root=0x5591df554f80, relation_objectid=99834, inhparent=false, rel=0x5591df556610) at /home/runner/work/timescaledb/timescaledb/src/planner/planner.c:1267
        ht = 0x5591df3fc178
#6  0x00005591dd31e33f in build_simple_rel (root=0x5591df554f80, relid=2, parent=0x5591df556320) at relnode.c:307
        rel = 0x5591df556610
        rte = 0x5591df55aa40
        __func__ = "build_simple_rel"
#7  0x00007fb4dbb86872 in ts_plan_expand_hypertable_chunks (ht=0x5591df2eddf0, root=0x5591df554f80, rel=0x5591df556320) at /home/runner/work/timescaledb/timescaledb/src/planner/expand_hypertable.c:1532
        child_rtindex = 2
        child_rel = 0x5591df3b4330
        i = 0
        priv = 0x5591df556f30
        rte = 0x5591df5542f0
        parent_oid = 99596
        inh_oids = 0x5591df55a8e0
        l = 0x0
        oldrelation = 0x7fb4db7d20f0
        parse = 0x5591df54bde0
        rti = 1
        appinfos = 0x5591df55afe0
        oldrc = 0x0
        ctx = {root = 0x5591df554f80, rel = 0x5591df556320, restrictions = 0x5591df558198, chunk_exclusion_func = 0x0, join_conditions = 0x0, propagate_conditions = 0x0, all_quals = 0x5591df558218, join_level = 0}
        first_chunk_index = 2
        __func__ = "ts_plan_expand_hypertable_chunks"
        chunks = 0x5591df5587e8
        num_chunks = 6
#8  0x00007fb4dbb78a11 in reenable_inheritance (root=0x5591df554f80, rel=0x5591df556320, rti=1, rte=0x5591df5542f0) at /home/runner/work/timescaledb/timescaledb/src/planner/planner.c:956
        in_rel = 0x5591df556320
        ht = 0x5591df2eddf0
        in_rte = 0x5591df5542f0
        i = 1
        set_pathlist_for_current_rel = false
        total_pages = 6.9526920593051101e-310
        reenabled_inheritance = false
        __func__ = "reenable_inheritance"
#9  0x00007fb4dbb79956 in timescaledb_set_rel_pathlist (root=0x5591df554f80, rel=0x5591df556320, rti=1, rte=0x5591df5542f0) at /home/runner/work/timescaledb/timescaledb/src/planner/planner.c:1179
        reltype = TS_REL_HYPERTABLE
        ht = 0x5591df2eddf0
(More stack frames follow...)
```
```
(gdb) p *ht
$5 = {fd = {id = 2139062143, schema_name = {
      data = "\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\17
7\177\177\177\177\177\177\177\177"}, table_name = {
      data = "\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\17
7\177\177\177\177\177\177\177\177"}, associated_schema_name = {
      data = "\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\17
7\177\177\177\177\177\177\177\177"}, associated_table_prefix = {
      data = "\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\17
7\177\177\177\177\177\177\177\177"}, num_dimensions = 32639, chunk_sizing_func_schema = {
      data = "\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\17
7\177\177\177\177\177\177\177\177"}, chunk_sizing_func_name = {
      data = "\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\17
7\177\177\177\177\177\177\177\177"}, chunk_target_size = 9187201950435737471, compression_state = 32639, compressed_hypertable_id = 2139062143, replication_factor = 32639}, main_table_relid = 2139062143, chunk_sizing_func = 2139062143,
  space = 0x7f7f7f7f7f7f7f7f, chunk_cache = 0x7f7f7f7f7f7f7f7f, data_nodes = 0x7f7f7f7f7f7f7f7f}
```

**Comment by akuzm** [comment]
I think it was fixed in https://github.com/timescale/timescaledb/pull/5086
Haven't happened after that:
```
ci_stats=> select count(*), max(job_date) from log where log_contents like '%ts_hypertable_has_compression_table%';
 count │             max              
───────┼──────────────────────────────
    53 │ 2022-12-13 00:28:28.42932+00
```
