### ISSUE TITLE
[Bug]: Job crashes on misconfigured guc

### ISSUE THREAD

**Issue by cevian** [timescale/timescaledb#5071]
### What type of bug is this?

Crash

### What subsystems and features are affected?

Background worker

### What happened?

When the `timescaledb.telemetry_level` GUC was erroneusly set to "False" (not off) we got a crash in bgws.

```
#0  pg_get_application_name (application_name=0x7fffb66e2c70 " 2n\266\377\177") at /build/pg_stat_monitor/pg_stat_monitor.c:1139
1139	/build/pg_stat_monitor/pg_stat_monitor.c: No such file or directory.
(gdb) bt
#0  pg_get_application_name (application_name=0x7fffb66e2c70 " 2n\266\377\177") at /build/pg_stat_monitor/pg_stat_monitor.c:1139
#1  0x00007fe856cf2881 in pgss_store (queryid=queryid@entry=0, query=query@entry=0x7fe856cf70a2 "", plan_info=plan_info@entry=0x0, cmd_type=cmd_type@entry=CMD_UNKNOWN, sys_info=sys_info@entry=0x0, error_info=error_info@entry=0x7fffb66e3360,
    total_time=total_time@entry=0, rows=0, bufusage=0x0, walusage=0x0, jstate=0x0, kind=PGSS_ERROR) at /build/pg_stat_monitor/pg_stat_monitor.c:1486
#2  0x00007fe856cf6513 in pgss_store_error (edata=0x55d6e5912aa0 <errordata.lto_priv>, query=0x7fe856cf70a2 "", queryid=0) at /build/pg_stat_monitor/pg_stat_monitor.c:1399
#3  pgsm_emit_log_hook (edata=0x55d6e5912aa0 <errordata.lto_priv>) at /build/pg_stat_monitor/pg_stat_monitor.c:3313
#4  0x000055d6e5629d54 in EmitErrorReport () at utils/error/./build/../src/backend/utils/error/elog.c:1538
#5  0x000055d6e561bb40 in errfinish (filename=<optimized out>, lineno=<optimized out>, funcname=0x55d6e57e41d0 <__func__.29> "parse_and_validate_value") at utils/error/./build/../src/backend/utils/error/elog.c:597
#6  0x000055d6e563a0c7 in parse_and_validate_value (record=0x55d6e6b18010, name=0x55d6e6b1c690 "timescaledb.telemetry_level", value=0x55d6e6ae4210 "False", source=PGC_S_FILE, elevel=19, newval=<optimized out>, newextra=0x7fffb66e3608)
    at utils/misc/./build/../src/backend/utils/misc/guc.c:7242
#7  0x000055d6e563a8c3 in set_config_option (name=0x55d6e6b1c690 "timescaledb.telemetry_level", value=<optimized out>, context=PGC_SIGHUP, source=PGC_S_FILE, action=GUC_ACTION_SET, changeVal=<optimized out>, elevel=19, is_reload=false)
    at utils/misc/./build/../src/backend/utils/misc/guc.c:7960
#8  0x000055d6e563ddc7 in define_custom_variable (variable=0x55d6e6b18010) at utils/misc/./build/../src/backend/utils/misc/guc.c:9042
#9  0x00007fe0a48e353c in _guc_init () at /build/timescaledb/src/guc.c:446
#10 _PG_init () at /build/timescaledb/src/init.c:110
#11 0x000055d6e562c66b in internal_load_library (libname=0x55d6e6b3eb68 "/usr/lib/postgresql/14/lib/timescaledb-2.9.0.so") at utils/fmgr/./build/../src/backend/utils/fmgr/dfmgr.c:290
#12 0x000055d6e562cd67 in load_external_function (filename=<optimized out>, funcname=0x55d6e6a33f34 "ts_bgw_job_entrypoint", signalNotFound=<optimized out>, filehandle=0x0) at utils/fmgr/./build/../src/backend/utils/fmgr/dfmgr.c:119
#13 0x000055d6e5434dbf in LookupBackgroundWorkerFunction (funcname=0x55d6e6a33f34 "ts_bgw_job_entrypoint", libraryname=0x55d6e6a33ed4 "timescaledb-2.9.0") at postmaster/./build/../src/backend/postmaster/bgworker.c:1286
#14 StartBackgroundWorker () at postmaster/./build/../src/backend/postmaster/bgworker.c:862
#15 0x000055d6e54419d1 in do_start_bgworker (rw=<optimized out>) at postmaster/./build/../src/backend/postmaster/postmaster.c:5866
#16 maybe_start_bgworkers () at postmaster/./build/../src/backend/postmaster/postmaster.c:6091
#17 0x000055d6e5441c1d in sigusr1_handler (postgres_signal_arg=<optimized out>) at postmaster/./build/../src/backend/postmaster/postmaster.c:5255
#18 <signal handler called>
#19 0x00007fe859a2c74d in select () from /lib/x86_64-linux-gnu/libc.so.6
#20 0x000055d6e5442b56 in ServerLoop () at postmaster/./build/../src/backend/postmaster/postmaster.c:1709
#21 0x000055d6e54446f7 in PostmasterMain (argc=17, argv=<optimized out>) at postmaster/./build/../src/backend/postmaster/postmaster.c:1417
#22 0x000055d6e515477a in main (argc=17, argv=0x55d6e6a322e0) at main/./build/../src/backend/main/main.c:209
```

### TimescaleDB version affected

2.9.0 

### PostgreSQL version used

14.x

### What operating system did you use?

docker

### What installation method did you use?

Docker

### What platform did you run on?

Amazon Web Services (AWS)

### How can we reproduce the bug?

```bash
see above
```

**Comment by konskov** [comment]
I could not reproduce this locally, setting an erroneous value for the GUC always gave me this waring (as expected):
```
WARNING:  22023: invalid value for parameter "timescaledb.telemetry_level": "false"
HINT:  Available values: off, no_functions, basic.
LOCATION:  parse_and_validate_value, guc.c:6877
```
I need to also try with docker. May I ask how did you set the value for the GUC? Thank you!
