### ISSUE TITLE
Assertion failure in CopyFetcher

### ISSUE THREAD

**Issue by svenklemm** [timescale/timescaledb#5394]
This was found by sqlsmith. sqlsmith was running against the database from regresscheck-shared.

Query:
```
WITH
jennifer_0 AS (select
    pg_catalog.tsmultirange() as c0
  from
    public.metrics_int as ref_0
  where pg_catalog.line(
      cast(case when (select relation_name from timescaledb_experimental.policies limit 1 offset 5)
             !~~* pg_catalog.version() then cast(null as point) else cast(null as point) end
         as point),
      cast(cast(null as point) as point)) = cast(null as line)
  limit 114)
select
    _timescaledb_internal.tsl_loaded() as c0,
    70 as c1,
    sample_1.v3 as c2
  from
    public.matches_reference as sample_0 tablesample system (7.9)
      inner join public.metrics_compressed as sample_1 tablesample bernoulli (9.9)
      on (case when (sample_0.location is NULL)
              or (70 = cast(null as int8)) then cast(null as xid) else cast(null as xid) end
             = sample_1.device_id)
  where pg_catalog.pg_stat_get_bgwriter_buf_written_clean() <> (select time from public.mvcp_hyper limit 1 offset 98)

  limit 96

```

Stacktrace:
````
#0  0x00007fc5fd80864c in ?? () from /usr/lib/libc.so.6
#1  0x00007fc5fd7b8938 in raise () from /usr/lib/libc.so.6
#2  0x00007fc5fd7a253d in abort () from /usr/lib/libc.so.6
#3  0x00005591459455da in ExceptionalCondition (conditionName=0x7fc5f0dc0536 "fetcher->state.eof", errorType=0x7fc5f0dbffe1 "FailedAssertion", fileName=0x7fc5f0dc00c0 "/home/sven/projects/tsmaster/tsl/src/remote/copy_fetcher.c",
    lineNumber=494) at assert.c:69
#4  0x00007fc5f0d8fdb5 in copy_fetcher_complete (fetcher=0x5591462b6588) at /home/sven/projects/tsmaster/tsl/src/remote/copy_fetcher.c:494
#5  0x00007fc5f0d8ff0c in copy_fetcher_fetch_data (df=0x5591462b6588) at /home/sven/projects/tsmaster/tsl/src/remote/copy_fetcher.c:535
#6  0x00007fc5f0d8ff73 in copy_fetcher_store_tuple (df=0x5591462b6588, row=10, slot=0x559146154540) at /home/sven/projects/tsmaster/tsl/src/remote/copy_fetcher.c:547
#7  0x00007fc5f0d900e3 in copy_fetcher_store_next_tuple (df=0x5591462b6588, slot=0x559146154540) at /home/sven/projects/tsmaster/tsl/src/remote/copy_fetcher.c:569
#8  0x00007fc5f0d5a71b in fdw_scan_iterate (ss=0x559146154290, fsstate=0x5591461543a8) at /home/sven/projects/tsmaster/tsl/src/fdw/scan_exec.c:333
#9  0x00007fc5f0d659b7 in data_node_scan_next (node=0x559146154290) at /home/sven/projects/tsmaster/tsl/src/fdw/data_node_scan_exec.c:66
#10 0x0000559145520e6c in ExecScanFetch (node=0x559146154290, accessMtd=0x7fc5f0d65966 <data_node_scan_next>, recheckMtd=0x7fc5f0d659cd <data_node_scan_recheck>) at execScan.c:133
#11 0x0000559145520f0d in ExecScan (node=0x559146154290, accessMtd=0x7fc5f0d65966 <data_node_scan_next>, recheckMtd=0x7fc5f0d659cd <data_node_scan_recheck>) at execScan.c:199
#12 0x00007fc5f0d65a55 in data_node_scan_exec (node=0x559146154290) at /home/sven/projects/tsmaster/tsl/src/fdw/data_node_scan_exec.c:97
#13 0x000055914553ba6d in ExecCustomScan (pstate=0x559146154290) at nodeCustom.c:115
#14 0x0000559145536271 in ExecProcNode (node=0x559146154290) at ../../../src/include/executor/executor.h:257
#15 0x0000559145536ad9 in ExecAppend (pstate=0x559146153e68) at nodeAppend.c:360
#16 0x00007fc5f0d65e0d in ExecProcNode (node=0x559146153e68) at /usr/local/pg14_stable/include/postgresql/server/executor/executor.h:257
#17 0x00007fc5f0d66517 in async_append_exec (node=0x559146153800) at /home/sven/projects/tsmaster/tsl/src/nodes/async_append.c:278
#18 0x000055914553ba6d in ExecCustomScan (pstate=0x559146153800) at nodeCustom.c:115
#19 0x00005591455507c3 in ExecProcNode (node=0x559146153800) at ../../../src/include/executor/executor.h:257
#20 0x0000559145550a2a in ExecLimit (pstate=0x5591461534f8) at nodeLimit.c:96
#21 0x000055914551cb21 in ExecProcNodeFirst (node=0x5591461534f8) at execProcnode.c:464
#22 0x000055914556524f in ExecProcNode (node=0x5591461534f8) at ../../../src/include/executor/executor.h:257
#23 0x0000559145567987 in ExecSetParamPlan (node=0x5591462b6038, econtext=0x559146250608) at nodeSubplan.c:1118
#24 0x0000559145507a2f in ExecEvalParamExec (state=0x5591462b43e0, op=0x5591462b4df0, econtext=0x559146250608) at execExprInterp.c:2414
#25 0x0000559145504ee6 in ExecInterpExpr (state=0x5591462b43e0, econtext=0x559146250608, isnull=0x7ffecd9bb97f) at execExprInterp.c:1062
#26 0x0000559145506971 in ExecInterpExprStillValid (state=0x5591462b43e0, econtext=0x559146250608, isNull=0x7ffecd9bb97f) at execExprInterp.c:1824
#27 0x0000559145561b94 in ExecEvalExprSwitchContext (state=0x5591462b43e0, econtext=0x559146250608, isNull=0x7ffecd9bb97f) at ../../../src/include/executor/executor.h:339
#28 0x0000559145561cd0 in ExecQual (state=0x5591462b43e0, econtext=0x559146250608) at ../../../src/include/executor/executor.h:408
#29 0x0000559145561d93 in ExecResult (pstate=0x5591462504f0) at nodeResult.c:84
#30 0x000055914551cb21 in ExecProcNodeFirst (node=0x5591462504f0) at execProcnode.c:464
#31 0x00005591455507c3 in ExecProcNode (node=0x5591462504f0) at ../../../src/include/executor/executor.h:257
#32 0x0000559145550a2a in ExecLimit (pstate=0x5591462501a8) at nodeLimit.c:96
#33 0x000055914551cb21 in ExecProcNodeFirst (node=0x5591462501a8) at execProcnode.c:464
#34 0x00005591455106fe in ExecProcNode (node=0x5591462501a8) at ../../../src/include/executor/executor.h:257
#35 0x00005591455132c8 in ExecutePlan (estate=0x559146153190, planstate=0x5591462501a8, use_parallel_mode=false, operation=CMD_SELECT, sendTuples=true, numberTuples=0, direction=ForwardScanDirection, dest=0x5591466d44d8,
    execute_once=true) at execMain.c:1551
#36 0x0000559145510e25 in standard_ExecutorRun (queryDesc=0x559146191060, direction=ForwardScanDirection, count=0, execute_once=true) at execMain.c:361
#37 0x00007fc5fdf43507 in pgss_ExecutorRun (queryDesc=0x559146191060, direction=ForwardScanDirection, count=0, execute_once=true) at ts_stat_statements.c:723
#38 0x00007fc5fd349e25 in pgss_ExecutorRun (queryDesc=0x559146191060, direction=ForwardScanDirection, count=0, execute_once=true) at pg_stat_statements.c:1001
#39 0x0000559145510bfb in ExecutorRun (queryDesc=0x559146191060, direction=ForwardScanDirection, count=0, execute_once=true) at execMain.c:303
#40 0x000055914578ec0d in PortalRunSelect (portal=0x559145fec170, forward=true, count=0, dest=0x5591466d44d8) at pquery.c:921
#41 0x000055914578e835 in PortalRun (portal=0x559145fec170, count=9223372036854775807, isTopLevel=true, run_once=true, dest=0x5591466d44d8, altdest=0x5591466d44d8, qc=0x7ffecd9bc040) at pquery.c:765
#42 0x00005591457877f1 in exec_simple_query (
    query_string=0x559145f797c0 "WITH \njennifer_0 AS (select  \n    pg_catalog.tsmultirange() as c0\n  from \n    public.metrics_int as ref_0\n  where pg_catalog.line(\n      cast(case when (select relation_name from timescaledb_experim
ental.policies limit 1 offset 5)\n             !~~* pg_catalog.version() then cast(null as point) else cast(null as point) end\n         as point),\n      cast(cast(null as point) as point)) = cast(null as line)\n  limit 114)\nselect  \n
    _timescaledb_internal.tsl_loaded() as c0, \n    70 as c1, \n    sample_1.v3 as c2\n  from \n    public.matches_reference as sample_0 tablesample system (7.9) \n      inner join public.metrics_compressed as sample_1 tablesample bernou
lli (9.9) \n      on (case when (sample_0.location is NULL) \n              or (70 = cast(null as int8)) then cast(null as xid) else cast(null as xid) end\n             = sample_1.device_id)\n  where pg_catalog.pg_stat_get_bgwriter_buf_w
ritten_clean() <> (select time from public.mvcp_hyper limit 1 offset 98)\n      \n  limit 96\n") at postgres.c:1213
#43 0x000055914578c663 in PostgresMain (argc=1, argv=0x7ffecd9bc260, dbname=0x559145faff48 "smith", username=0x559145faff28 "sven") at postgres.c:4508

````

**Comment by jnidzwetzki** [comment]
Might be related to #5323
