### ISSUE TITLE
Assertion failure in caggs with joins

### ISSUE THREAD

**Issue by svenklemm** [timescale/timescaledb#5468]
To reproduce:
```
--- Schema

CREATE TABLE device(
	id int,
	device_group int
);
CREATE TABLE sensor_data(
	device_id int,
	metric_id int,
	ts timestamptz,
	value double precision,
	CONSTRAINT sensor_uniq UNIQUE (device_id,metric_id,ts)
);

SELECT create_hypertable('sensor_data', 'ts', chunk_time_interval => INTERVAL '7 Days', if_not_exists => true);

--- Example CAGG: Daily average for metrics 1 and 2 for device group 1

CREATE MATERIALIZED VIEW daily_average_metrics_v2 WITH (timescaledb.continuous)
    AS SELECT time_bucket('1 day', ts) as bucket,
               device_id,
	      	  metric_id,
               avg(value)
 	   FROM sensor_data
 	   JOIN device on device.id = sensor_data.device_id
	   WHERE device.device_group = 1 AND metric_id in (1,2)
      GROUP BY device_id, metric_id, bucket;

 SELECT * from daily_average_metrics_v2;
 --- Returns empty rows as expected

INSERT INTO device VALUES (10,1);
INSERT INTO sensor_data VALUES
	(10,1,'2023-03-16 0:1:0.0+00',1),
	(10,1,'2023-03-16 0:2:0.0+00',2),
	(10,1,'2023-03-16 0:3:0.0+00',3),
	(10,1,'2023-03-16 0:4:0.0+00',4),
	(10,1,'2023-03-16 0:5:0.0+00',5);

SELECT * from daily_average_metrics_v2;
--- hits assertion
```

Stacktrace:
```
#3  0x0000562b87af0944 in ExceptionalCondition (conditionName=0x562b87b78378 "lockmode != NoLock || IsBootstrapProcessingMode() || CheckRelationLockedByMe(r, AccessShareLock, true)", errorType=0x562b87b7830b "FailedAssertion",
    fileName=0x562b87b78300 "relation.c", lineNumber=68) at assert.c:69
#4  0x0000562b873c50d6 in relation_open (relationId=3251532, lockmode=0) at relation.c:68
#5  0x0000562b874a4753 in table_open (relationId=3251532, lockmode=0) at table.c:43
#6  0x0000562b878b40a8 in AcquireRewriteLocks (parsetree=0x562b880bcff0, forExecute=true, forUpdatePushedDown=false) at rewriteHandler.c:190
#7  0x0000562b878b42fe in AcquireRewriteLocks (parsetree=0x562b880a8598, forExecute=true, forUpdatePushedDown=false) at rewriteHandler.c:269
#8  0x0000562b878b7024 in ApplyRetrieveRule (parsetree=0x562b87fb57a0, rule=0x562b87f88bd0, rt_index=1, relation=0x7f9e439c4788, activeRIRs=0x562b880bc908) at rewriteHandler.c:1815
#9  0x0000562b878b78b9 in fireRIRrules (parsetree=0x562b87fb57a0, activeRIRs=0x562b880bc908) at rewriteHandler.c:2120
#10 0x0000562b878bb7dd in QueryRewrite (parsetree=0x562b87fb57a0) at rewriteHandler.c:4182
#11 0x0000562b875ff5c9 in ExplainQuery (pstate=0x562b880a8340, stmt=0x562b87fb55c0, params=0x0, dest=0x562b8809c468) at explain.c:260
#12 0x0000562b8793120b in standard_ProcessUtility (pstmt=0x562b87fb5d90, queryString=0x562b87fb4820 "explain SELECT * from daily_average_metrics_v2;", readOnlyTree=false, context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0,
    dest=0x562b8809c468, qc=0x7ffe5a04fcb0) at utility.c:870
#13 0x00007f9e4d702f1d in loader_process_utility_hook (pstmt=0x562b87fb5d90, query_string=0x562b87fb4820 "explain SELECT * from daily_average_metrics_v2;", readonly_tree=false, context=PROCESS_UTILITY_TOPLEVEL, params=0x0,
    queryEnv=0x0, dest=0x562b8809c468, completion_tag=0x7ffe5a04fcb0) at /home/sven/projects/tsmaster/src/loader/loader.c:583
#14 0x00007f9e4d6f97d5 in pgss_ProcessUtility (pstmt=0x562b87fb5d90, queryString=0x562b87fb4820 "explain SELECT * from daily_average_metrics_v2;", readOnlyTree=false, context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0,
    dest=0x562b8809c468, qc=0x7ffe5a04fcb0) at ts_stat_statements.c:993
#15 0x00007f9e438fac43 in prev_ProcessUtility (args=0x7ffe5a04fb50) at /home/sven/projects/tsmaster/src/process_utility.c:97
#16 0x00007f9e43903f05 in timescaledb_ddl_command_start (pstmt=0x562b87fb5d90, query_string=0x562b87fb4820 "explain SELECT * from daily_average_metrics_v2;", readonly_tree=false, context=PROCESS_UTILITY_TOPLEVEL, params=0x0,
    queryEnv=0x0, dest=0x562b8809c468, completion_tag=0x7ffe5a04fcb0) at /home/sven/projects/tsmaster/src/process_utility.c:4468
#17 0x0000562b879307b5 in ProcessUtility (pstmt=0x562b87fb5d90, queryString=0x562b87fb4820 "explain SELECT * from daily_average_metrics_v2;", readOnlyTree=false, context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0,
    dest=0x562b8809c468, qc=0x7ffe5a04fcb0) at utility.c:526
#18 0x0000562b8792f0ca in PortalRunUtility (portal=0x562b8802d310, pstmt=0x562b87fb5d90, isTopLevel=true, setHoldSnapshot=true, dest=0x562b8809c468, qc=0x7ffe5a04fcb0) at pquery.c:1158
#19 0x0000562b8792ee0f in FillPortalStore (portal=0x562b8802d310, isTopLevel=true) at pquery.c:1031
#20 0x0000562b8792e6be in PortalRun (portal=0x562b8802d310, count=9223372036854775807, isTopLevel=true, run_once=true, dest=0x562b87fb6660, altdest=0x562b87fb6660, qc=0x7ffe5a04fef0) at pquery.c:763
#21 0x0000562b87927655 in exec_simple_query (query_string=0x562b87fb4820 "explain SELECT * from daily_average_metrics_v2;") at postgres.c:1250
#22 0x0000562b8792c4e1 in PostgresMain (dbname=0x562b87fe7198 "join_cagg", username=0x562b87fe7170 "postgres") at postgres.c:4593
#23 0x0000562b87853a4c in BackendRun (port=0x562b87fe3ba0) at postmaster.c:4511
#24 0x0000562b878532df in BackendStartup (port=0x562b87fe3ba0) at postmaster.c:4239
#25 0x0000562b8784f1f3 in ServerLoop () at postmaster.c:1806
```

**Comment by ciccerro** [comment]
Postgres version - 14

Timescale version - 2.10.1

This is the generated view from the above cagg

```
SELECT sensor_data.device_id AS bucket,
sensor_data.metric_id AS device_id,
sensor_data.ts AS metric_id,
sensor_data.value AS avg
FROM sensor_data
JOIN device ON device.id = sensor_data.device_id
WHERE _materialized_hypertable_193.bucket < COALESCE(_timescaledb_internal.to_timestamp(_timescaledb_internal.cagg_watermark(193)), '-infinity'::timestamp with time zone)
UNION ALL
SELECT time_bucket('1 day'::interval, sensor_data.ts) AS bucket,
sensor_data.device_id,
sensor_data.metric_id,
avg(sensor_data.value) AS avg
FROM sensor_data
JOIN device ON device.id = sensor_data.device_id
WHERE device.device_group = 1 AND (sensor_data.metric_id = ANY (ARRAY[1, 2])) AND sensor_data.ts >= COALESCE(_timescaledb_internal.to_timestamp(_timescaledb_internal.cagg_watermark(193)), '-infinity'::timestamp with time zone)
GROUP BY sensor_data.device_id, sensor_data.metric_id, (time_bucket('1 day'::interval, sensor_data.ts));
```

Data types to not match the definition

```
SELECT sensor_data.device_id AS bucket,
sensor_data.metric_id AS device_id,
sensor_data.ts AS metric_id,
sensor_data.value AS avg
FROM sensor_data
```

Should this not be

```
SELECT _materialized_hypertable_193.bucket AS bucket,
_materialized_hypertable_193.device_id AS device_id,
_materialized_hypertable_193.meter_id AS metric_id,
_materialized_hypertable_193.avg AS avg
FROM sensor_data
```

Cagg's with join don't seem to produce corresponding views that are valid.

**Comment by jsteph221** [comment]
This seems to have been fixed and works as of 2.10.3 (possibly same as issue #5602 or #5433)

**Comment by svenklemm** [comment]
Works with recent versions.
