### ISSUE TITLE
Segfault when creating cagg

### ISSUE THREAD

**Issue by svenklemm** [timescale/timescaledb#5500]
The following cagg creation call segfaults:

```
CREATE MATERIALIZED VIEW cagg1 with (timescaledb.continuous) AS SELECT 1 GROUP BY 1 WITH NO DATA; 
```
Stacktrace:
```
#0  0x00007fbbe8ca68ec in ?? () from /usr/lib/libc.so.6
#1  0x00007fbbe8c57ea8 in raise () from /usr/lib/libc.so.6
#2  0x00007fbbe8c4153d in abort () from /usr/lib/libc.so.6
#3  0x000055744c0ad944 in ExceptionalCondition (conditionName=0x7fbbdf389679 "list != NIL", errorType=0x7fbbdf3895ff "FailedAssertion", fileName=0x7fbbdf389638 "/usr/local/pg15_stable/include/postgresql/server/nodes/pg_list.h",
    lineNumber=258) at assert.c:69
#4  0x00007fbbdf311a1e in list_nth_cell (list=0x0, n=0) at /usr/local/pg15_stable/include/postgresql/server/nodes/pg_list.h:258
#5  0x00007fbbdf314788 in cagg_validate_query (query=0x55744cb410d8, finalized=true, cagg_schema=0x55744cc249b8 "public", cagg_name=0x55744cb40278 "cagg1") at /home/sven/projects/tsmaster/tsl/src/continuous_aggs/create.c:1236
#6  0x00007fbbdf318f71 in tsl_process_continuous_agg_viewstmt (node=0x55744cb40740, query_string=0x55744cb3f820 "CREATE MATERIALIZED VIEW cagg1 with (timescaledb.continuous) AS SELECT 1 GROUP BY 1 WITH NO DATA;", pstmt=0x55744cb40f58,
    with_clause_options=0x55744cb00890) at /home/sven/projects/tsmaster/tsl/src/continuous_aggs/create.c:2819
#7  0x00007fbbdf41b3d6 in process_create_table_as (args=0x7ffeb4591ce0) at /home/sven/projects/tsmaster/src/process_utility.c:4063
#8  0x00007fbbdf41b798 in process_ddl_command_start (args=0x7ffeb4591ce0) at /home/sven/projects/tsmaster/src/process_utility.c:4214
#9  0x00007fbbdf41bec0 in timescaledb_ddl_command_start (pstmt=0x55744cb40f58, query_string=0x55744cb3f820 "CREATE MATERIALIZED VIEW cagg1 with (timescaledb.continuous) AS SELECT 1 GROUP BY 1 WITH NO DATA;", readonly_tree=false,
    context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, dest=0x55744cb40ff0, completion_tag=0x7ffeb4592090) at /home/sven/projects/tsmaster/src/process_utility.c:4457
#10 0x000055744beed7b5 in ProcessUtility (pstmt=0x55744cb40f58, queryString=0x55744cb3f820 "CREATE MATERIALIZED VIEW cagg1 with (timescaledb.continuous) AS SELECT 1 GROUP BY 1 WITH NO DATA;", readOnlyTree=false,
    context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, dest=0x55744cb40ff0, qc=0x7ffeb4592090) at utility.c:526
#11 0x000055744beec0ca in PortalRunUtility (portal=0x55744cbbb050, pstmt=0x55744cb40f58, isTopLevel=true, setHoldSnapshot=false, dest=0x55744cb40ff0, qc=0x7ffeb4592090) at pquery.c:1158
#12 0x000055744beec351 in PortalRunMulti (portal=0x55744cbbb050, isTopLevel=true, setHoldSnapshot=false, dest=0x55744cb40ff0, altdest=0x55744cb40ff0, qc=0x7ffeb4592090) at pquery.c:1315
#13 0x000055744beeb791 in PortalRun (portal=0x55744cbbb050, count=9223372036854775807, isTopLevel=true, run_once=true, dest=0x55744cb40ff0, altdest=0x55744cb40ff0, qc=0x7ffeb4592090) at pquery.c:791
#14 0x000055744bee4655 in exec_simple_query (query_string=0x55744cb3f820 "CREATE MATERIALIZED VIEW cagg1 with (timescaledb.continuous) AS SELECT 1 GROUP BY 1 WITH NO DATA;") at postgres.c:1250
#15 0x000055744bee94e1 in PostgresMain (dbname=0x55744cb72ec8 "pr5497", username=0x55744cb72ea0 "postgres") at postgres.c:4593
#16 0x000055744be10a4c in BackendRun (port=0x55744cb6fae0) at postmaster.c:4511
#17 0x000055744be102df in BackendStartup (port=0x55744cb6fae0) at postmaster.c:4239
#18 0x000055744be0c1f3 in ServerLoop () at postmaster.c:1806
#19 0x000055744be0b96b in PostmasterMain (argc=4, argv=0x55744caf9120) at postmaster.c:1478
#20 0x000055744bd01833 in main (argc=4, argv=0x55744caf9120) at main.c:202
```

**Comment by RafiaSabih** [comment]
Thanks @svenklemm for reporting this. I can reproduce it. The check is missing for the NULL list.
