### ISSUE TITLE
Assertion failure in UnregisterSnapshotFromOwner

### ISSUE THREAD

**Issue by svenklemm** [timescale/timescaledb#5706]
Found by sqlsmith. sqlsmith was run against the regresscheck-shared database.

Query:
```
delete from public.metrics_tstz
where
public.metrics_tstz.time is NULL
returning
  pg_catalog.current_query() as c0,
  pg_catalog.inet_client_addr() as c1,
  public.metrics_tstz.v2 as c2,
  public.metrics_tstz.v1 as c3,
  pg_catalog.pg_wal_replay_resume() as c4
```

Stacktrace:
```
#0  0x00007fe40c68c8ec in ?? () from /usr/lib/libc.so.6
#1  0x00007fe40c63dea8 in raise () from /usr/lib/libc.so.6
#2  0x00007fe40c62753d in abort () from /usr/lib/libc.so.6
#3  0x000056360e2d2944 in ExceptionalCondition (conditionName=0x56360e50b942 "snapshot->regd_count > 0", errorType=0x56360e50b5a1 "FailedAssertion", fileName=0x56360e50b597 "snapmgr.c", lineNumber=887) at assert.c:69
#4  0x000056360e33223e in UnregisterSnapshotFromOwner (snapshot=0x56360e651fa0 <CurrentSnapshotData>, owner=0x56360eddcab0) at snapmgr.c:887
#5  0x000056360e3321eb in UnregisterSnapshot (snapshot=0x56360e651fa0 <CurrentSnapshotData>) at snapmgr.c:874
#6  0x000056360de992e4 in standard_ExecutorEnd (queryDesc=0x56360f29d250) at execMain.c:498
#7  0x00007fe40cde53ed in pgss_ExecutorEnd (queryDesc=0x56360f29d250) at ts_stat_statements.c:909
#8  0x00007fe40c1cb00e in pgss_ExecutorEnd (queryDesc=0x56360f29d250) at pg_stat_statements.c:1071
#9  0x000056360de991d4 in ExecutorEnd (queryDesc=0x56360f29d250) at execMain.c:464
#10 0x000056360e10f7fe in ProcessQuery (plan=0x56360ef34040,
    sourceText=0x56360ed43820 "delete from public.metrics_tstz\nwhere \npublic.metrics_tstz.time is NULL\nreturning \n  pg_catalog.current_query() as c0, \n  pg_catalog.inet_client_addr() as c1, \n  public.metrics_tstz.v2 as c2, \n  publ
ic.metrics_tstz.v1 as c3, \n  pg_catalog.pg_wal_replay_resume() as c4", params=0x0, queryEnv=0x0, dest=0x56360ee679e8, qc=0x7ffd51d9f090) at pquery.c:194
#11 0x000056360e11129a in PortalRunMulti (portal=0x56360edbcf90, isTopLevel=true, setHoldSnapshot=true, dest=0x56360ee679e8, altdest=0x56360e612a80 <donothingDR>, qc=0x7ffd51d9f090) at pquery.c:1277
#12 0x000056360e110dbd in FillPortalStore (portal=0x56360edbcf90, isTopLevel=true) at pquery.c:1026
#13 0x000056360e1106be in PortalRun (portal=0x56360edbcf90, count=9223372036854775807, isTopLevel=true, run_once=true, dest=0x56360ef344a0, altdest=0x56360ef344a0, qc=0x7ffd51d9f2d0) at pquery.c:763
#14 0x000056360e109655 in exec_simple_query (
    query_string=0x56360ed43820 "delete from public.metrics_tstz\nwhere \npublic.metrics_tstz.time is NULL\nreturning \n  pg_catalog.current_query() as c0, \n  pg_catalog.inet_client_addr() as c1, \n  public.metrics_tstz.v2 as c2, \n  pu
blic.metrics_tstz.v1 as c3, \n  pg_catalog.pg_wal_replay_resume() as c4") at postgres.c:1250
#15 0x000056360e10e4e1 in PostgresMain (dbname=0x56360ed78e10 "smith", username=0x56360ed78df0 "sven") at postgres.c:4593
#16 0x000056360e035a4c in BackendRun (port=0x56360ed73a00) at postmaster.c:4511
#17 0x000056360e0352df in BackendStartup (port=0x56360ed73a00) at postmaster.c:4239
#18 0x000056360e0311f3 in ServerLoop () at postmaster.c:1806
#19 0x000056360e03096b in PostmasterMain (argc=4, argv=0x56360ecfd120) at postmaster.c:1478
#20 0x000056360df26833 in main (argc=4, argv=0x56360ecfd120) at main.c:202
```

**Comment by svenklemm** [comment]
Closing since this is stale issue
