### ISSUE TITLE
Assertion failure in decompress_get_free_batch_state_id

### ISSUE THREAD

**Issue by svenklemm** [timescale/timescaledb#5708]
Found by sqlsmith. sqlsmith was run against the regresscheck-shared database.

Query:
```
select

    pg_catalog.max(
      cast(cast(null as date) as date)) over (partition by sample_0.v1,sample_0.time order by sample_0.v1,sample_0.device_id) as c0
from
  public.metrics as sample_0 tablesample system (2.2)
where EXISTS (
  select
      ref_0.v1 as c0,
      ref_0.v1 as c1,
      81 as c2,
      sample_0.v2 as c3,
      ref_0.device_id as c4,
      sample_0.v1 as c5,
      ref_0.v0 as c6,
      ref_0.v2 as c7,

        pg_catalog.max(
          cast(case when cast(null as lseg) ?-| cast(null as lseg) then cast(null as date) else cast(null as date) end
             as date)) over (partition by sample_0.time order by sample_0.v2,ref_0.time,ref_0.time) as c8,
      sample_0.v3 as c9,
      _timescaledb_internal.materialization_invalidation_log_delete(
        cast(sample_0.v1 as int4)) as c10,
      ref_0.v0 as c11,
      sample_0.device_id as c12,
      sample_0.v3 as c13,
      sample_0.v1 as c14,
      ref_0.time as c15,
      pg_catalog.pg_stat_force_next_flush() as c16,
      pg_catalog.pg_control_init() as c17
    from
      public.metrics_space_compressed as ref_0
    where ref_0.v0 is NULL
    limit 127)
limit 79
```

Stacktrace:
```
#0  0x00007fe40c68c8ec in ?? () from /usr/lib/libc.so.6
#1  0x00007fe40c63dea8 in raise () from /usr/lib/libc.so.6
#2  0x00007fe40c62753d in abort () from /usr/lib/libc.so.6
#3  0x000056360e2d2944 in ExceptionalCondition (conditionName=0x7fe402d72c40 "next_free_batch < chunk_state->n_batch_states", errorType=0x7fe402d7281f "FailedAssertion",
    fileName=0x7fe402d729d0 "/home/sven/projects/tsmaster/tsl/src/nodes/decompress_chunk/exec.c", lineNumber=226) at assert.c:69
#4  0x00007fe402d2122e in decompress_get_free_batch_state_id (chunk_state=0x56360ef6baf8) at /home/sven/projects/tsmaster/tsl/src/nodes/decompress_chunk/exec.c:226
#5  0x00007fe402d257d3 in decompress_batch_open_next_batch (chunk_state=0x56360ef6baf8) at /home/sven/projects/tsmaster/tsl/src/nodes/decompress_chunk/sorted_merge.c:106
#6  0x00007fe402d25aa1 in decompress_sorted_merge_init (chunk_state=0x56360ef6baf8) at /home/sven/projects/tsmaster/tsl/src/nodes/decompress_chunk/sorted_merge.c:191
#7  0x00007fe402d22050 in decompress_chunk_exec (node=0x56360ef6baf8) at /home/sven/projects/tsmaster/tsl/src/nodes/decompress_chunk/exec.c:632
#8  0x000056360dec40aa in ExecCustomScan (pstate=0x56360ef6baf8) at nodeCustom.c:115
#9  0x000056360dede7b0 in ExecProcNode (node=0x56360ef6baf8) at ../../../src/include/executor/executor.h:259
#10 0x000056360dedecc0 in ExecMergeAppend (pstate=0x56360ef42bc8) at nodeMergeAppend.c:230
#11 0x000056360deebd43 in ExecProcNode (node=0x56360ef42bc8) at ../../../src/include/executor/executor.h:259
#12 0x000056360deebff8 in ExecResult (pstate=0x56360ef42a18) at nodeResult.c:115
#13 0x000056360def7013 in ExecProcNode (node=0x56360ef42a18) at ../../../src/include/executor/executor.h:259
#14 0x000056360def90d9 in begin_partition (winstate=0x56360ef424d0) at nodeWindowAgg.c:1113
#15 0x000056360defb41a in ExecWindowAgg (pstate=0x56360ef424d0) at nodeWindowAgg.c:2131
#16 0x000056360ded8db1 in ExecProcNode (node=0x56360ef424d0) at ../../../src/include/executor/executor.h:259
#17 0x000056360ded9018 in ExecLimit (pstate=0x56360ef421c8) at nodeLimit.c:96
#18 0x000056360deef8fb in ExecProcNode (node=0x56360ef421c8) at ../../../src/include/executor/executor.h:259
#19 0x000056360def01fa in ExecScanSubPlan (node=0x56360f8da698, econtext=0x56360f8d98d8, isNull=0x56360f8da1ed) at nodeSubplan.c:323
#20 0x000056360deefb90 in ExecSubPlan (node=0x56360f8da698, econtext=0x56360f8d98d8, isNull=0x56360f8da1ed) at nodeSubplan.c:89
#21 0x000056360de9331f in ExecEvalSubPlan (state=0x56360f8da1e8, op=0x56360f8da2c0, econtext=0x56360f8d98d8) at execExprInterp.c:3961
#22 0x000056360de8e059 in ExecInterpExpr (state=0x56360f8da1e8, econtext=0x56360f8d98d8, isnull=0x7ffd51d9e98f) at execExprInterp.c:1566
#23 0x000056360dea955b in ExecEvalExprSwitchContext (state=0x56360f8da1e8, econtext=0x56360f8d98d8, isNull=0x7ffd51d9e98f) at ../../../src/include/executor/executor.h:341
#24 0x000056360dea9697 in ExecQual (state=0x56360f8da1e8, econtext=0x56360f8d98d8) at ../../../src/include/executor/executor.h:410
#25 0x000056360dea9a97 in ExecScan (node=0x56360f8d96c0, accessMtd=0x56360deec70a <SampleNext>, recheckMtd=0x56360deec742 <SampleRecheck>) at execScan.c:227
#26 0x000056360deec793 in ExecSampleScan (pstate=0x56360f8d96c0) at nodeSamplescan.c:87
#27 0x000056360dea547a in ExecProcNodeFirst (node=0x56360f8d96c0) at execProcnode.c:464
#28 0x000056360debe8f7 in ExecProcNode (node=0x56360f8d96c0) at ../../../src/include/executor/executor.h:259
#29 0x000056360debf0fa in ExecAppend (pstate=0x56360f8d6238) at nodeAppend.c:347
#30 0x000056360dea547a in ExecProcNodeFirst (node=0x56360f8d6238) at execProcnode.c:464
#31 0x000056360deee924 in ExecProcNode (node=0x56360f8d6238) at ../../../src/include/executor/executor.h:259
#32 0x000056360deeeb70 in ExecSort (pstate=0x56360f8d6020) at nodeSort.c:149
#33 0x000056360dea547a in ExecProcNodeFirst (node=0x56360f8d6020) at execProcnode.c:464
#34 0x000056360def7013 in ExecProcNode (node=0x56360f8d6020) at ../../../src/include/executor/executor.h:259
#35 0x000056360def90d9 in begin_partition (winstate=0x56360f8d5ad8) at nodeWindowAgg.c:1113
#36 0x000056360defb41a in ExecWindowAgg (pstate=0x56360f8d5ad8) at nodeWindowAgg.c:2131
#37 0x000056360dea547a in ExecProcNodeFirst (node=0x56360f8d5ad8) at execProcnode.c:464
#38 0x000056360ded8db1 in ExecProcNode (node=0x56360f8d5ad8) at ../../../src/include/executor/executor.h:259
#39 0x000056360ded9018 in ExecLimit (pstate=0x56360f8d58c0) at nodeLimit.c:96
#40 0x000056360dea547a in ExecProcNodeFirst (node=0x56360f8d58c0) at execProcnode.c:464
#41 0x000056360de9883c in ExecProcNode (node=0x56360f8d58c0) at ../../../src/include/executor/executor.h:259
#42 0x000056360de9b6ed in ExecutePlan (estate=0x56360ef41e00, planstate=0x56360f8d58c0, use_parallel_mode=false, operation=CMD_SELECT, sendTuples=true, numberTuples=0, direction=ForwardScanDirection, dest=0x56360efba388,
    execute_once=true) at execMain.c:1636
#43 0x000056360de98f63 in standard_ExecutorRun (queryDesc=0x56360f498e40, direction=ForwardScanDirection, count=0, execute_once=true) at execMain.c:363
#44 0x00007fe40cde4526 in pgss_ExecutorRun (queryDesc=0x56360f498e40, direction=ForwardScanDirection, count=0, execute_once=true) at ts_stat_statements.c:725
#45 0x00007fe40c1cacd7 in pgss_ExecutorRun (queryDesc=0x56360f498e40, direction=ForwardScanDirection, count=0, execute_once=true) at pg_stat_statements.c:1008
#46 0x000056360de98d39 in ExecutorRun (queryDesc=0x56360f498e40, direction=ForwardScanDirection, count=0, execute_once=true) at execMain.c:305
#47 0x000056360e110abe in PortalRunSelect (portal=0x56360edc4fa0, forward=true, count=0, dest=0x56360efba388) at pquery.c:924
#48 0x000056360e1106e0 in PortalRun (portal=0x56360edc4fa0, count=9223372036854775807, isTopLevel=true, run_once=true, dest=0x56360efba388, altdest=0x56360efba388, qc=0x7ffd51d9f2d0) at pquery.c:768
```

**Comment by svenklemm** [comment]
No longer fails in recent versions
