### ISSUE TITLE
Assertion failure when using MERGE on hypertables

### ISSUE THREAD

**Issue by svenklemm** [timescale/timescaledb#5730]
Found by sqlsmith

Query:
```
MERGE INTO public.metrics as target_0
USING public.sensors as ref_0
ON target_0.v1 = ref_0.sensor_id
WHEN NOT MATCHED AND 70 > (select pg_catalog.min(device_id) from public.metrics_space_compressed)
   THEN INSERT VALUES ( pg_catalog.transaction_timestamp(), 51, 9, 87, cast(null as float8), cast(null as float8))
```

Stacktrace:
```
#0  0x00007f5d4a6b18ec in ?? () from /usr/lib/libc.so.6
#1  0x00007f5d4a662ea8 in raise () from /usr/lib/libc.so.6
#2  0x00007f5d4a64c53d in abort () from /usr/lib/libc.so.6
#3  0x000055f32ff73944 in ExceptionalCondition (conditionName=0x55f330102cd8 "resultnum >= 0 && resultnum < resultslot->tts_tupleDescriptor->natts", errorType=0x55f330102933 "FailedAssertion",
    fileName=0x55f330102bb2 "execExprInterp.c", lineNumber=676) at assert.c:69
#4  0x000055f32fb2d6a3 in ExecInterpExpr (state=0x55f331712a30, econtext=0x55f33170eb10, isnull=0x7fff3c480c3f) at execExprInterp.c:676
#5  0x000055f32fb2faf3 in ExecInterpExprStillValid (state=0x55f331712a30, econtext=0x55f33170eb10, isNull=0x7fff3c480c3f) at execExprInterp.c:1826
#6  0x00007f5d40ec1084 in ExecEvalExprSwitchContext (state=0x55f331712a30, econtext=0x55f33170eb10, isNull=0x7fff3c480c3f) at /usr/local/pg15_stable/include/postgresql/server/executor/executor.h:341
#7  0x00007f5d40ec10fc in ExecProject (projInfo=0x55f331712a28) at /usr/local/pg15_stable/include/postgresql/server/executor/executor.h:375
#8  0x00007f5d40ec256e in ht_ExecMergeNotMatched (context=0x7fff3c480e30, resultRelInfo=0x55f3317078b8, cds=0x55f331708ab0, canSetTag=true) at /home/sven/projects/timescaledb/src/import/ht_hypertable_modify.c:767
#9  0x00007f5d40ec27ac in ht_ExecMerge (context=0x7fff3c480e30, resultRelInfo=0x55f3317078b8, cds=0x55f331708ab0, tupleid=0x0, canSetTag=true) at /home/sven/projects/timescaledb/src/import/ht_hypertable_modify.c:874
#10 0x00007f5d40ec475d in ExecModifyTable (cs_node=0x55f3317072c0, pstate=0x55f3317076a0) at /home/sven/projects/timescaledb/src/nodes/hypertable_modify.c:852
#11 0x00007f5d40ec33fc in hypertable_modify_exec (node=0x55f3317072c0) at /home/sven/projects/timescaledb/src/nodes/hypertable_modify.c:182
#12 0x000055f32fb650aa in ExecCustomScan (pstate=0x55f3317072c0) at nodeCustom.c:115
#13 0x000055f32fb4647a in ExecProcNodeFirst (node=0x55f3317072c0) at execProcnode.c:464
#14 0x000055f32fb3983c in ExecProcNode (node=0x55f3317072c0) at ../../../src/include/executor/executor.h:259
#15 0x000055f32fb3c6ed in ExecutePlan (estate=0x55f3316e0d60, planstate=0x55f3317072c0, use_parallel_mode=false, operation=CMD_MERGE, sendTuples=false, numberTuples=0, direction=ForwardScanDirection, dest=0x55f331674460,
    execute_once=true) at execMain.c:1636
#16 0x000055f32fb39f63 in standard_ExecutorRun (queryDesc=0x55f3314e8780, direction=ForwardScanDirection, count=0, execute_once=true) at execMain.c:363
#17 0x00007f5d4ae09526 in pgss_ExecutorRun (queryDesc=0x55f3314e8780, direction=ForwardScanDirection, count=0, execute_once=true) at ts_stat_statements.c:725
#18 0x00007f5d4a1efcd7 in pgss_ExecutorRun (queryDesc=0x55f3314e8780, direction=ForwardScanDirection, count=0, execute_once=true) at pg_stat_statements.c:1008
#19 0x000055f32fb39d39 in ExecutorRun (queryDesc=0x55f3314e8780, direction=ForwardScanDirection, count=0, execute_once=true) at execMain.c:305
#20 0x000055f32fdb06d9 in ProcessQuery (plan=0x55f3316642e8,
    sourceText=0x55f33139c820 "MERGE INTO public.metrics as target_0\nUSING public.sensors as ref_0\nON target_0.v1 = ref_0.sensor_id \nWHEN NOT MATCHED AND 70 > (select pg_catalog.min(device_id) from public.metrics_space_compressed)\n
    \n   THEN INSERT VALUES ( pg_catalog.transaction_timestamp(), 51, 9, 87, cast(null as float8), cast(null as float8))\n", params=0x0, queryEnv=0x0, dest=0x55f331674460, qc=0x7fff3c481540) at pquery.c:160
#21 0x000055f32fdb229a in PortalRunMulti (portal=0x55f3314145e0, isTopLevel=true, setHoldSnapshot=false, dest=0x55f331674460, altdest=0x55f331674460, qc=0x7fff3c481540) at pquery.c:1277
#22 0x000055f32fdb1791 in PortalRun (portal=0x55f3314145e0, count=9223372036854775807, isTopLevel=true, run_once=true, dest=0x55f331674460, altdest=0x55f331674460, qc=0x7fff3c481540) at pquery.c:791
#23 0x000055f32fdaa655 in exec_simple_query (
    query_string=0x55f33139c820 "MERGE INTO public.metrics as target_0\nUSING public.sensors as ref_0\nON target_0.v1 = ref_0.sensor_id \nWHEN NOT MATCHED AND 70 > (select pg_catalog.min(device_id) from public.metrics_space_compressed)\n
      \n   THEN INSERT VALUES ( pg_catalog.transaction_timestamp(), 51, 9, 87, cast(null as float8), cast(null as float8))\n") at postgres.c:1250
#24 0x000055f32fdaf4e1 in PostgresMain (dbname=0x55f3313ce848 "smith", username=0x55f3313ce828 "sven") at postgres.c:4593
#25 0x000055f32fcd6a4c in BackendRun (port=0x55f3313c6ce0) at postmaster.c:4511
#26 0x000055f32fcd62df in BackendStartup (port=0x55f3313c6ce0) at postmaster.c:4239
#27 0x000055f32fcd21f3 in ServerLoop () at postmaster.c:1806
#28 0x000055f32fcd196b in PostmasterMain (argc=4, argv=0x55f331356120) at postmaster.c:1478
#29 0x000055f32fbc7833 in main (argc=4, argv=0x55f331356120) at main.c:202
```

**Comment by svenklemm** [comment]
Works on recent versions
