### ISSUE TITLE
[Bug]: Server crashes when trying to insert data into distibuted hypertable after dropping node's database

### ISSUE THREAD

**Issue by alexanderlaw** [timescale/timescaledb#5924]
### What type of bug is this?

Crash

### What subsystems and features are affected?

Distributed hypertable

### What happened?

When trying to INSERT data into an distributed hypertable after it's data node's database is dropped, I get a server crash due to accessing an invalid pointer.

(When trying to perform SELECT from the table, I get an error, not crash:
ERROR:  could not connect to "dn1"
DETAIL:  connection to server at "localhost" (::1), port 5432 failed: FATAL:  database "dn1" does not exist)

### TimescaleDB version affected

2.12.0-dev

### PostgreSQL version used

15.3

### What operating system did you use?

Ubuntu 22.04 x86_64

### What installation method did you use?

Source

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
Core was generated by `postgres: law regression [local] INSERT                                       '.
Program terminated with signal SIGSEGV, Segmentation fault.

warning: Section `.reg-xstate/331876' in core file too small.
#0  0x00007f44162176e6 in remote_connection_get_status (conn=0x7f7f7f7f7f7f7f7f)
    at .../timescaledb/tsl/src/remote/connection.c:940
940             return conn->status;
(gdb) bt
#0  0x00007f44162176e6 in remote_connection_get_status (conn=0x7f7f7f7f7f7f7f7f)
    at .../timescaledb/tsl/src/remote/connection.c:940
#1  0x00007f4416223f87 in end_copy_on_failure (state=0x564292161230)
    at .../timescaledb/tsl/src/remote/dist_copy.c:649
#2  0x00007f44162272d5 in remote_copy_send_slot (context=0x564292161230, slot=0x564291e0f268, 
    cis=0x5642920c8fd8) at .../timescaledb/tsl/src/remote/dist_copy.c:1675
#3  0x00007f44161ff3cc in data_node_copy_exec (node=0x5642920cfd28)
    at .../timescaledb/tsl/src/nodes/data_node_copy.c:236
#4  0x00005642902275f5 in ExecCustomScan (pstate=0x5642920cfd28) at nodeCustom.c:115
#5  0x00005642902084f6 in ExecProcNodeFirst (node=0x5642920cfd28) at execProcnode.c:464
#6  0x00007f441631720e in ExecProcNode (node=0x5642920cfd28)
    at .../test_install/include/server/executor/executor.h:262
#7  0x00007f4416318c2f in ExecModifyTable (cs_node=0x5642920cf178, pstate=0x5642920cf678)
    at .../timescaledb/src/nodes/hypertable_modify.c:824
#8  0x00007f44163179b7 in hypertable_modify_exec (node=0x5642920cf178)
    at .../timescaledb/src/nodes/hypertable_modify.c:182
#9  0x00005642902275f5 in ExecCustomScan (pstate=0x5642920cf178) at nodeCustom.c:115
#10 0x00005642902084f6 in ExecProcNodeFirst (node=0x5642920cf178) at execProcnode.c:464
#11 0x00005642901fb5f2 in ExecProcNode (node=0x5642920cf178) at ../../../src/include/executor/executor.h:262
#12 0x00005642901fe4f9 in ExecutePlan (estate=0x5642920cef00, planstate=0x5642920cf178, 
    use_parallel_mode=false, operation=CMD_INSERT, sendTuples=false, numberTuples=0, 
    direction=ForwardScanDirection, dest=0x56429205fbf8, execute_once=true) at execMain.c:1636
#13 0x00005642901fbd29 in standard_ExecutorRun (queryDesc=0x5642920090b0, direction=ForwardScanDirection, 
    count=0, execute_once=true) at execMain.c:363
#14 0x00005642901fbb14 in ExecutorRun (queryDesc=0x5642920090b0, direction=ForwardScanDirection, count=0, 
    execute_once=true) at execMain.c:307
#15 0x0000564290477e35 in ProcessQuery (plan=0x56429205fb60, 
    sourceText=0x564291d3e5b0 "INSERT INTO tbl(t) VALUES('2023-08-01');", params=0x0, queryEnv=0x0, 
    dest=0x56429205fbf8, qc=0x7fffdc68b9b0) at pquery.c:160
#16 0x0000564290479a28 in PortalRunMulti (portal=0x564291db1650, isTopLevel=true, setHoldSnapshot=false, 
    dest=0x56429205fbf8, altdest=0x56429205fbf8, qc=0x7fffdc68b9b0) at pquery.c:1277
#17 0x0000564290478f0b in PortalRun (portal=0x564291db1650, count=9223372036854775807, isTopLevel=true, 
    run_once=true, dest=0x56429205fbf8, altdest=0x56429205fbf8, qc=0x7fffdc68b9b0) at pquery.c:791
#18 0x0000564290471cd4 in exec_simple_query (
    query_string=0x564291d3e5b0 "INSERT INTO tbl(t) VALUES('2023-08-01');") at postgres.c:1250
#19 0x0000564290476c05 in PostgresMain (dbname=0x564291d6d4c8 "regression", username=0x564291d6d4a8 "law")
    at postgres.c:4598
#20 0x000056429039bf8d in BackendRun (port=0x564291d64be0) at postmaster.c:4511
#21 0x000056429039b814 in BackendStartup (port=0x564291d64be0) at postmaster.c:4239
#22 0x00005642903976e7 in ServerLoop () at postmaster.c:1806
#23 0x0000564290396e44 in PostmasterMain (argc=3, argv=0x564291ca6a80) at postmaster.c:1478
#24 0x000056429028aad5 in main (argc=3, argv=0x564291ca6a80) at main.c:202
```

### How can we reproduce the bug?

```bash
CREATE EXTENSION timescaledb;

SELECT add_data_node('dn1', host => 'localhost', database => 'dn1');

CREATE TABLE tbl(t TIMESTAMPTZ NOT NULL);
SELECT create_distributed_hypertable('tbl', 't');

INSERT INTO tbl(t) VALUES('2023-08-01');

DROP DATABASE dn1;

INSERT INTO tbl(t) VALUES('2023-08-01');
```

**Comment by fabriziomello** [comment]
In [2.13.0](https://github.com/timescale/timescaledb/releases/tag/2.13.0) we announced the deprecation of multi-node and it will be complete removed from the upcoming 2.14.0.
