### ISSUE TITLE
[Bug]: Distributed DDL does not quote correctly

### ISSUE THREAD

**Issue by mrksngl** [timescale/timescaledb#5982]
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Data node, Multi-node

### What happened?

As in my last report #5900, I have again a problem with usernames including strange characters, this time the hyphen `-`.
Maybe it's also the database name, or both of them.

So I was experimenting a bit with distributed DDLs and executed
`GRANT CONNECT ON DATABASE "dead-beef" TO "foo-bar"`.

The data node reported
`ERROR:  [dn0]: syntax error at or near "-"`

I know this message all to well, it also happens on the access node (or postgres in general) if I don't put the database or user name into quotes, so I guess this is exactly the case here.

### TimescaleDB version affected

2.11.2

### PostgreSQL version used

14.8

### What operating system did you use?

Base image used by spilo docker image

### What installation method did you use?

Source

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
ERROR:  [dn0]: syntax error at or near "-"
```

### How can we reproduce the bug?

```bash
CREATE DATABASE "dead-beef";
CREATE ROLE "foo-bar";
SET timescaledb_experimental.enable_distributed_ddl to on;
GRANT CONNECT ON DATABASE "dead-beef" to "foo-bar";
```

**Comment by mkindahl** [comment]
@mrksngl Looking at the code, it seems to quote the database correctly for the database name. I also tried to reproduce it following the instructions, but it does not give an error.

I will try some other ways, but in the log on the data node you should be able to see the statement that was attempted. If you could add that to the issue, it would help to pinpoint the problem.

**Comment by mrksngl** [comment]
Ok, my example works for me, too. So it's wrong, sorry about that.

I will investigate the original case (involving a more complex setup) and report again.

**Comment by mrksngl** [comment]
Ok again:

```SQL
CREATE ROLE "foo-bar";
CREATE DATABASE "dead-beef";
\c "dead-beef"
SELECT add_data_node(...);
SET timescaledb_experimental.enable_distributed_ddl to on;
GRANT CONNECT ON DATABASE "dead-beef" to "foo-bar";
```
I have no idea, but it requires that I am connected to the database in question on the access node.

On the data node, I see
```
2023-08-18 11:04:03.987 UTC user=postgres db=dead-beef pid=50804ERROR:  syntax error at or near "-" at character 45
2023-08-18 11:04:03.987 UTC user=postgres db=dead-beef pid=50804STATEMENT:  GRANT connect ON DATABASE "dead-beef" TO foo-bar
```

**Comment by mkindahl** [comment]
@mrksngl Thank you. I was able to reproduce it using the provided instructions. 

```
mats@fury:~$ psql
Expanded display is used automatically.
Null display is "[NULL]".
psql (15.3)
Type "help" for help.

mats=# CREATE ROLE "foo-bar";
CREATE ROLE
mats=# CREATE DATABASE "dead-beef";
CREATE DATABASE
mats=# \c "dead-beef"
You are now connected to database "dead-beef" as user "mats".
dead-beef=# CREATE EXTENSION IF NOT EXISTS timescaledb;
WARNING:  
WELCOME TO
 _____ _                               _     ____________  
|_   _(_)                             | |    |  _  \ ___ \ 
  | |  _ _ __ ___   ___  ___  ___ __ _| | ___| | | | |_/ / 
  | | | |  _ ` _ \ / _ \/ __|/ __/ _` | |/ _ \ | | | ___ \ 
  | | | | | | | | |  __/\__ \ (_| (_| | |  __/ |/ /| |_/ /
  |_| |_|_| |_| |_|\___||___/\___\__,_|_|\___|___/ \____/
               Running version 2.12.0-dev
For more information on TimescaleDB, please visit the following links:

 1. Getting started: https://docs.timescale.com/timescaledb/latest/getting-started
 2. API reference documentation: https://docs.timescale.com/api/latest
 3. How TimescaleDB is designed: https://docs.timescale.com/timescaledb/latest/overview/core-concepts

Note: TimescaleDB collects anonymous reports to better understand and assist our users.
For more information and how to disable, please see our docs https://docs.timescale.com/timescaledb/latest/how-to-guides/configuration/telemetry.

CREATE EXTENSION
dead-beef=# SELECT * FROM add_data_node('data_node_1', host => 'localhost', database => 'data_node_1');
  node_name  |   host    | port |  database   | node_created | database_created | extension_created 
-------------+-----------+------+-------------+--------------+------------------+-------------------
 data_node_1 | localhost | 5432 | data_node_1 | t            | t                | t
(1 row)

dead-beef=# SET timescaledb_experimental.enable_distributed_ddl to on;
SET
dead-beef=# select pg_backend_pid();
 pg_backend_pid 
----------------
         718463
(1 row)

dead-beef=# GRANT CONNECT ON DATABASE "dead-beef" to "foo-bar";
ERROR:  [data_node_1]: syntax error at or near "-"
```

The problem seems to be in `deparse_grant_revoke_on_database`.

```
(gdb) p *command
$18 = {data = 0x562d43870330 "GRANT connect ON DATABASE data_node_1 TO foo-bar ", len = 49, maxlen = 1024, cursor = 0}
(gdb) bt
#0  deparse_grant_revoke_on_database (stmt=stmt@entry=0x562d4379ec28, dbname=dbname@entry=0x562d4387f2f8 "data_node_1") at /home/mats/work/timescale/timescaledb+hacking/tsl/src/deparse.c:1007
#1  0x00007fb3ed92c0d2 in dist_ddl_process_grant_on_database (stmt=0x562d4379ec28) at /home/mats/work/timescale/timescaledb+hacking/tsl/src/remote/dist_ddl.c:582
#2  0x00007fb3ed92c4cd in dist_ddl_process_grant_object (args=<optimized out>) at /home/mats/work/timescale/timescaledb+hacking/tsl/src/remote/dist_ddl.c:668
#3  0x00007fb3ed92c97c in dist_ddl_process_grant (args=<optimized out>) at /home/mats/work/timescale/timescaledb+hacking/tsl/src/remote/dist_ddl.c:704
#4  0x00007fb3ed92d33d in dist_ddl_process (args=args@entry=0x7ffff12afb70) at /home/mats/work/timescale/timescaledb+hacking/tsl/src/remote/dist_ddl.c:967
#5  0x00007fb3ed92d5d4 in dist_ddl_start (args=args@entry=0x7ffff12afb70) at /home/mats/work/timescale/timescaledb+hacking/tsl/src/remote/dist_ddl.c:1208
#6  0x00007fb3ed8af125 in tsl_ddl_command_start (args=0x7ffff12afb70) at /home/mats/work/timescale/timescaledb+hacking/tsl/src/process_utility.c:29
#7  0x00007fb3ed9cf115 in timescaledb_ddl_command_start (pstmt=0x562d4379f1c8, query_string=<optimized out>, readonly_tree=<optimized out>, context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=<optimized out>, dest=0x562d4379f260, 
    completion_tag=0x7ffff12afec0) at /home/mats/work/timescale/timescaledb+hacking/src/process_utility.c:4535
#8  0x0000562d4324a5ce in ProcessUtility (pstmt=pstmt@entry=0x562d4379f1c8, queryString=<optimized out>, readOnlyTree=<optimized out>, context=context@entry=PROCESS_UTILITY_TOPLEVEL, params=<optimized out>, queryEnv=<optimized out>, 
    dest=0x562d4379f260, qc=0x7ffff12afec0) at utility.c:526
#9  0x0000562d43247909 in PortalRunUtility (portal=portal@entry=0x562d438132a0, pstmt=pstmt@entry=0x562d4379f1c8, isTopLevel=isTopLevel@entry=true, setHoldSnapshot=setHoldSnapshot@entry=false, dest=dest@entry=0x562d4379f260, 
    qc=qc@entry=0x7ffff12afec0) at pquery.c:1158
#10 0x0000562d43247c06 in PortalRunMulti (portal=portal@entry=0x562d438132a0, isTopLevel=isTopLevel@entry=true, setHoldSnapshot=setHoldSnapshot@entry=false, dest=dest@entry=0x562d4379f260, altdest=altdest@entry=0x562d4379f260, 
    qc=qc@entry=0x7ffff12afec0) at pquery.c:1315
#11 0x0000562d4324807f in PortalRun (portal=portal@entry=0x562d438132a0, count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true, run_once=run_once@entry=true, dest=dest@entry=0x562d4379f260, 
    altdest=altdest@entry=0x562d4379f260, qc=0x7ffff12afec0) at pquery.c:791
#12 0x0000562d43244068 in exec_simple_query (query_string=query_string@entry=0x562d4379dfc0 "GRANT CONNECT ON DATABASE \"dead-beef\" to \"foo-bar\";") at postgres.c:1250
#13 0x0000562d43245ff4 in PostgresMain (dbname=<optimized out>, username=<optimized out>) at postgres.c:4593
#14 0x0000562d4319a610 in BackendRun (port=port@entry=0x562d437c6660) at postmaster.c:4511
#15 0x0000562d4319d794 in BackendStartup (port=port@entry=0x562d437c6660) at postmaster.c:4239
#16 0x0000562d4319d9cf in ServerLoop () at postmaster.c:1806
#17 0x0000562d4319efa7 in PostmasterMain (argc=argc@entry=1, argv=argv@entry=0x562d43705960) at postmaster.c:1478
#18 0x0000562d430df3a3 in main (argc=1, argv=0x562d43705960) at main.c:202
```

**Comment by fabriziomello** [comment]
In [2.13.0](https://github.com/timescale/timescaledb/releases/tag/2.13.0) we announced the deprecation of multi-node and it will be complete removed from the upcoming 2.14.0.
