### ISSUE TITLE
extensible node type "ChunkDispatchInfo" already exists

### ISSUE THREAD

**Issue by LuboVarga** [timescale/timescaledb#815]
We keep getting error about *extensible node type "ChunkDispatchInfo" already exists* when using quartz scheduler on database with timescaledb support. Tables used by quartd does not have timescaledb schemas. Only on same database, there are some tables with timescaledb schema.

Stacktrace:

> org.postgresql.util.PSQLException: ERROR: extensible node type "ChunkDispatchInfo" already exists
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
	at org.postgresql.core.SetupQueryRunner.run(SetupQueryRunner.java:53)
	at org.postgresql.core.v3.ConnectionFactoryImpl.runInitialQueries(ConnectionFactoryImpl.java:684)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:225)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
	at org.postgresql.Driver.makeConnection(Driver.java:452)
	at org.postgresql.Driver.connect(Driver.java:254)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

I believe that problem is in creation of sql connection, before any application query is done and jdbc driver ([postgresql-42.2.2](https://mvnrepository.com/artifact/org.postgresql/postgresql/42.2.2)) is throwing exception when executing [SET extra_float_digits = 3](https://github.com/pgjdbc/pgjdbc/blob/e44e4e8972ec41bf05dddd4ac6dcfbc42a9842cf/pgjdbc/src/main/java/org/postgresql/core/v3/ConnectionFactoryImpl.java#L730) query.

Have we hit some race condition, does we have bad set-up or what does mean this exception? Google does not know this type of issue and single link it is providing is for file [chunk_dispatch_plan.c](https://github.com/timescale/timescaledb/blob/master/src/chunk_dispatch_plan.c).

**Comment by RobAtticus** [comment]
Are you using the latest version of TimescaleDB? I remember a similar error but it was patched back in the 0.9.0 series if I recall correctly.

**Comment by LuboVarga** [comment]
You are right. We are using 0.9.0 and latest available is 0.11.0. We will upgrade. Thanks.

**Comment by RobAtticus** [comment]
@LuboVarga the current release is 0.12.1. What release mechanism are you seeing where 0.11.0 is the latest?

**Comment by LuboVarga** [comment]
Thanks for note @RobAtticus. I have checked our prod servers and it is being updated from our own yum repository. I will check how does timescaledb rpm find its way to our repo. Probably it was manually uploaded after check by some of my colleague.

**Comment by gbalbinot** [comment]
I had the same issue, I restarted the database and it was gone.

**Comment by rrb3942** [comment]
I am also getting this error message sometimes.

I have a perl script that runs every few minutes and queries a table in Postgres to update some totals on another system. Every once and awhile it will error out with the following:

DBD::Pg::st execute failed: ERROR:  extensible node type "ChunkDispatchInfo" already exists
CONTEXT:  parallel worker at  /scriptpath.pl line 406.
ERROR:  extensible node type "ChunkDispatchInfo" already exists
CONTEXT:  parallel worker at /scriptpath.pl line 406.

This started after I had upgraded timescaledb from version 0.10.1 to 1.0.
I tried restarting the postgres service after the upgrade to see if that would clear it, and it did not.

Let me know if this should be opened under a new issue.

**Comment by RobAtticus** [comment]
@rrb3942 - Have to upgraded all databases that have the extension to the latest version?

**Comment by rrb3942** [comment]
@RobAtticus 

We only have one database on this system, but the tables being used are under a schema.

**Comment by aliensmily** [comment]
> I had the same issue, I restarted the database and it was gone.

worked also for me
